### PR TITLE
Fix #4595: 'Reveal in Files' error

### LINKED ISSUE #4595: 'Reveal in Files' error
### Description
1.Click 'Reveal in Files' in ContextMenu
2.'Files' tab is focused, but the selectedNode is rootNode rather than the revealed node

**OS and Theia version:**
OS: mac
Theia version: 0.4.0

**Diagnostics:**

### PR DESCRIPTION
**Pull request by zixuemeng**
Signed-off-by: Feng Qingxue <948699357@qq.com>

### CODE REVIEW

**Comment by zixuemeng** [comment]
@akosyakov Can you help me to see how to pass the Gitpod check?

**Comment by akosyakov** [comment]
@jbicker Could you review it? please check that the thing fixed by https://github.com/theia-ide/theia/commit/ffbb7dcff84e085fe27661b99b6ade312e9bc29e is still fixed

@zixuemeng ignore it, Gitpod team is looking into it

**Comment by kittaakos** [comment]
This seems to be a bit related to https://github.com/theia-ide/theia/issues/4570. What do you think? I would like to get this generally fixed with all tree widgets and not the navigator only.

https://github.com/theia-ide/theia/blob/e06d5420ee85d4ec41b585c43edb4af001744779/packages/core/src/browser/tree/tree-widget.tsx#L247-L257

vs.

https://github.com/theia-ide/theia/blob/e06d5420ee85d4ec41b585c43edb4af001744779/packages/navigator/src/browser/navigator-widget.tsx#L99-L105

Introducing two new (`protected`) API methods for the initial selection and expansion state would be great.

**Comment by zixuemeng** [comment]
This patch is only for fixing bug https://github.com/theia-ide/theia/issues/4595. I think https://github.com/theia-ide/theia/issues/4570 is an issue about code optimization and a new patch is needed to fix https://github.com/theia-ide/theia/issues/4570.

**Comment by zixuemeng** [comment]
@jbicker Could you help me to review this pr?  Confirm it fix https://github.com/theia-ide/theia/issues/4595 and https://github.com/theia-ide/theia/commit/ffbb7dcff84e085fe27661b99b6ade312e9bc29e.
I'm not familiar with tree-widget enough, so I can't fix https://github.com/theia-ide/theia/issues/4595 and https://github.com/theia-ide/theia/issues/4570 in one patch.  Maybe someone who familiar with tree-widget  can submit a  new patch to fix https://github.com/theia-ide/theia/issues/4570.

**Comment by jbicker** [comment]
I will review it now.

**Comment by akosyakov** [comment]
@jbicker if @zixuemeng has ECA signed off, please proceed with merging his PR, you check ECA here https://www.eclipse.org/legal/ECA.php -> `Validation Tool`

**Comment by zixuemeng** [comment]
I have already signed ECA during submitting https://github.com/theia-ide/theia/pull/4519.

**Pull request merged**
