### PR TITLE
[quality] Do not log the extensions from the `check-hoisting` script

### LINKED ISSUE #3266: [quality] Do not log the extensions from the `check-hoisting` script
It was a bad idea to print all the Theia extensions to the console.
```
 - Checking @theia/bunyan...
 - Checking @theia/callhierarchy...
 - Checking @theia/console...
 - Checking @theia/core...
 - Checking @theia/cpp...
 - Checking @theia/debug...
 - Checking @theia/debug-nodejs...
 - Checking @theia/editor...
 - Checking @theia/editorconfig...
 - Checking @theia/extension-manager...
 - Checking @theia/file-search...
 - Checking @theia/filesystem...
 - Checking @theia/git...
 - Checking @theia/java...
 - Checking @theia/json...
 - Checking @theia/keymaps...
 - Checking @theia/languages...
 - Checking @theia/markers...
 - Checking @theia/merge-conflicts...
 - Checking @theia/messages...
 - Checking @theia/metrics...
 - Checking @theia/mini-browser...
 - Checking @theia/monaco...
 - Checking @theia/navigator...
 - Checking @theia/outline-view...
 - Checking @theia/output...
 - Checking @theia/plugin...
 - Checking @theia/plugin-ext...
 - Checking @theia/plugin-ext-vscode...
 - Checking @theia/preferences...
 - Checking @theia/preview...
 - Checking @theia/process...
 - Checking @theia/python...
 - Checking @theia/search-in-workspace...
 - Checking @theia/task...
 - Checking @theia/terminal...
 - Checking @theia/textmate-grammars...
 - Checking @theia/tslint...
 - Checking @theia/typescript...
 - Checking @theia/userstorage...
 - Checking @theia/variable-resolver...
 - Checking @theia/workspace...
```

It should be removed.

### PR DESCRIPTION
**Pull request by adi7ya**
Fixes #3266

### CODE REVIEW

**Comment by kittaakos** [comment]
@akosyakov, for me https://github.com/theia-ide/theia/pull/3527 has higher priority.
@adi7ya, please [sign](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#sign-your-work) your commit. And make sure you have signed the [ECA](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) too. Otherwise, we cannot accept your patch. Thanks!

**Comment by adi7ya** [comment]
@kittaakos, signed the commit and ECA. Please have a look now. Thanks.

**Comment by kittaakos** [comment]
@adi7ya, can you please rebase from the `master`?

The change you made, is good.

Can you please change the trailing colon (`:`)
https://github.com/theia-ide/theia/blob/6340b339929b5f2706c97b17864a7a5746363a7b/scripts/check-hoisting.ts#L52
either to an ellipsis (`...`) or a period (`.`)?

Then squash the commits. Thanks for the help!

**Comment by adi7ya** [comment]
Hi @kittaakos, I replaced the trailing colon with an ellipsis. Please have a look now. Thanks!

**Pull request merged**
