### PR TITLE
Update readme screenshot

### LINKED ISSUE #4635: update Theia screenshot in README
Should be in similar context, but with up-to-date UI

cc @vince-fugnitto i think you did it last time :)

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #4635

- Updated the readme screenshot to reflect the recent changes to the user interface.
- Updated to use an absolute path instead of relative for the screenshot's source.

<div align='center'>

theia-screenshot

</div>

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov let me know if there is any tweaks you want to make to the screenshot like things you want displayed or not displayed 😃

**Comment by akosyakov** [comment]
I would make to look a bit more like VS Code, i.e. close `Plugin`, `Git History` from the left sidebar, add `Output`, `Debug Console`, `Terminal` to the bottom panel after `Problems` in order similar to VS Code. `Outline` and `Type Hierarchy` on the right sidebar are fine to me. 

And I liked dark browser mode in the previous screenshot.

**Comment by vince-fugnitto** [comment]
@akosyakov I updated the screenshot based on your comments 😃

**Comment by benoitf** [comment]
I think it's misleading people to have extension icon of Theia being the same icon as VS Code extension as you might expect that you're able to use VSCode extensions while it's bring by plug-ins.

So I would be more in favor of having plug-in icon being the same than vscode extension as they're targeting the same files

**Comment by vince-fugnitto** [comment]
> I think it's misleading people to have extension icon of Theia being the same icon as VS Code...

I'd be fine with your proposal of using the vscode extension icon for our plugins widget. 
I don't remember when I read it but I recall some conversation highlighting that our extension widget would become deprecated in the future.

**Comment by benoitf** [comment]
I moved the conversation there https://github.com/theia-ide/theia/pull/4600 as I think here we're talking about screenshots so I don't want to hijack the thread.

Regarding the screenshot, it would be great to have an absolute link to the screenshot from README
I used several tools that are embedding the README.MD file and they're failing to include the image in their rendering.

**Comment by akosyakov** [comment]
Would be nice to update it once more to reflect @svenefftinge changes. The bottom panel is higher in VS Code by default.

**Comment by vince-fugnitto** [comment]
@akosyakov whenever you get the chance to check, I've updated the screenshot for the readme

**Comment by vince-fugnitto** [comment]
thank you @akosyakov !

**Pull request merged**
