### PR TITLE
[monaco] Add `onWillChangeModelOnSave` event

### PR DESCRIPTION
**Pull request by marechal-p**
This commit addresses the issue when some contributions want to actually change
a document, without providing changes to the API and let monaco do.

If someone changes the document after another contribution already provided
edits, it might offset every previously provided edits.

By adding the new event, we can ensure that every change that is done in
one-shot will not interfere with the other ones, by executing them
sequentially, so that we smoothly get from some "Version A" of a document to
"Version B", then from "Version B" to "Version C", etc...

Once the changes are made, people using the API to provide edits to be made by
monaco can be ran concurrently.

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by marechal-p** [comment]
@akosyakov turns out the last patch only fixed part of the issue (waiting for everyone to finish).

Turns out some contributions needs to be ran before the rest. Specifically when someone actually change the model when responding to the event, instead of returning edits to be applied.

This is the case for monaco commands, when we execute such commands (format command, or remove trailing white spaces command, etc...) we do not receive edits but instead the document is modified. In this case we don't want it to run concurrently with contributions providing edits.

Example:

```ts
async function formatDocument() {
    await sleep(2); // simulate heavy processing
    const newContent = "huehuehue";
    setDocumentContent(newContent); // Now past edits will be outdated and invalid
    return;
}

function quickEdit(): IIdentifiedSingleEditOperation[] {
    // This function is synchronous to illustrate the fact that it will return a resolved promise in 1 tick
    const text = getDocumentContent();
    // Process the edits based on the content...
    return Promise.resolved([someEditA, someEditB]);
}
```

We cannot run the two above functions concurrently and expect them to work.

**Comment by akosyakov** [comment]
I don't think we need a new event, we should figure out what is the proper contract for `onWillSaveTextDocument`, i.e. what VS Code expects, since we want to be compatible with that. VS Code has only 2 public APIs for saving `onWillSaveTextDocument` and `onDidSaveTextDocument`. We should have 2 as well and implement them similarly.

@marechal-p please could you study source code of VS Code and https://github.com/editorconfig/editorconfig-vscode? figure out what is the proper contract and implement it?

**Comment by marechal-p** [comment]
@akosyakov I don't like two events either, will look at what VS Code does and try to align Theia on it.

**Comment by marechal-p** [comment]
Ok, update: VS Code doesn't parallelize edits, and instead they manage a list of listeners/callbacks that get triggered one after the other.

In our case, we first dispatch the event to everyone, then wait for them all. But at this point, every edits are computed at the same time, from the same base document model. This can lead to conflicts, where too contributions want to edit the same region.

I don't really know how to handle that, first thought would be to add an alternative API that would address this issue, and deprecate the other one (but keeping it for some time).

My hope is that by the time we get to Theia Beta or 1.0 we will be able to remove bad APIs :/

**Pull request closed without merging**
