### PR TITLE
GH-627: Increased the default timeout for the Git tests.

### LINKED ISSUE #627: [git] Check why tests occasionally timeout and fail on Travis CI
Maybe we just have to increase the default timeout.
Could be other problems too, so the promise cannot be resolved within 2 seconds.

### PR DESCRIPTION
**Pull request by kittaakos**
I have set it to 10 seconds.
Closes #627.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Task: #627.

**Comment by hexa00** [comment]
```
lerna ERR! execute   1) Terminal Backend Contribution is data received from the terminal ws server:

lerna ERR! execute      Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

Funny now it's the terminal test failing I'll have to increase that one too

**Comment by hexa00** [comment]
BTW please merge even if the test do not pass, it will help isolate the real issues we have at the moment. I'll do the same for the terminal tests

**Comment by kittaakos** [comment]
We have the green build; I am merging this PR to the master.

**Pull request merged**
