### PR TITLE
made SearchInWorkspaceClient.onResult() synchronous

### LINKED ISSUE #3914: [search-in-workspace] result tree rendering logic is problematic
As the GIF shows, search-in-workspace backend returns correct data however sometimes not all results are rendered in the tree.

peek 2018-12-28 21-22

### PR DESCRIPTION
**Pull request by elaihau**
- search-in-workspace backend returns correct data however sometimes not all results are rendered in the result tree. This is caused by SearchInWorkspaceClient.onDone() being called before all onResult()s finish.
This change makes SearchInWorkspaceClient.onResult() a synchronous function, which ensures that onDone() runs after onResult()s are completed.

- fixed #3914

Signed-off-by: elaihau <liang.huang@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I noticed something odd, when you perform a search, you'll get the results and the result-info, but after clicking the `eye` icon, the file-count becomes 0.

**Comment by elaihau** [comment]
I tested on gitpod. it happened !!!
I will look into it. Thank you @vince-fugnitto !

**Comment by elaihau** [comment]
I think i know what happened, as you could see from the following GIF, "in 0 files" is an intermediary. While I agree that we should not display that "intermediary" to the user, i believe it should be resolved in a different PR :)

peek 2018-12-31 13-38

**Comment by vince-fugnitto** [comment]
> I think i know what happened, as you could see from the following GIF, "in 0 files" is an intermediary. While I agree that we should not display that "intermediary" to the user, i believe it should be resolved in a different PR :)
> 
> Tested on the Dec 27 2018 version, it also happened.
> 
> peek 2018-12-31 13-38

I wrote the following #3918 to track the issue.

**Pull request merged**
