### PR TITLE
[plugin] Fixed API doc typo

### PR DESCRIPTION
**Pull request by amiramw**

### CODE REVIEW

**Comment by benoitf** [comment]
Hello @amiramw and thanks for the fix.
FYI you need to sign your commit 
https://github.com/theia-ide/theia/pull/3263/checks?check_run_id=25845407

**Comment by marcdumais-work** [comment]
@amiramw You will also need to sign the Eclipse ECA, or if already done, use in your commit, the same email address you used for the ECA.

https://www.eclipse.org/legal/ECA.php

**Comment by amiramw** [comment]
@marcdumais-work I believe with this email I signed it.

**Comment by marcdumais-work** [comment]
Thanks @amiramw . Could you please update the commit message to something a bit more precise. For example: 
 "[plugin] Fixed typo"

**Comment by amiramw** [comment]
any idea why the appveyor is failing? i guess it is not related to my typo fix...

**Comment by benoitf** [comment]
@amiramw yes it's not related. 
thanks for your fix.

**Comment by benoitf** [comment]
I checked on ECA VALIDATION TOOL, email is fine

**Pull request merged**
