### PR TITLE
[layout-restorer] Added command to reset the workbench layout (fixes #618)

### LINKED ISSUE #618: Tabs in the side bar are shown in the reverse order

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

**Comment by svenefftinge** [comment]
reset_layout

**Comment by hexa00** [comment]
Humm this resets the layout but won't it leak ressources associated with it ? 

Like if I had 5 editors, call this and reload will these editors be closed ?  Are they still not in the widget manager ?

**Comment by svenefftinge** [comment]
Yes, they will be closed

**Comment by hexa00** [comment]
Right since all frontend ressources get cleaned on reload...

Backend ressources would be cleaned by the websocket going away I guess.

So LGTM.

**Pull request merged**
