### PR TITLE
fixes gh-976: get rid of requirejs

### PR DESCRIPTION
**Pull request by akosyakov**
To verify:
 - [x] Windows browser
 - [x] Windows electron
 - [x] OS X browser
 - [x] OS X electron
 - [ ] Linux browser
 - [ ] Linux electron

### CODE REVIEW

**Comment by akosyakov** [comment]
please review, one should check that both browser and electron examples are still working

**Comment by simark** [comment]
Hmm, I cleaned my git repo, did a fresh build, cleaned all my browser data, and I still see this included in the html:

      <script type="text/javascript" src="https://www.promisejs.org/polyfills/promise-6.1.0.js" charset="utf-8"></script>

**Comment by akosyakov** [comment]
@simark because it is another PR, for polyfills: https://github.com/theia-ide/theia/pull/1317

**Comment by kittaakos** [comment]
I can see the following warnings and an error in the log. I was trying the browser version on OS X:
```
08:28:05.913 logger.ts:60 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/Microsoft/monaco-editor#faq
log @ logger.ts:60
t.logOnceWebWorkerWarning @ editor.main.js:31
t._getOrCreateWorker @ editor.main.js:31
t._getProxy @ editor.main.js:31
t._withSyncedResources @ editor.main.js:31
t.computeLinks @ editor.main.js:31
(anonymous) @ editor.main.js:31
then @ editor.main.js:31
provideLinks @ editor.main.js:31
(anonymous) @ editor.main.js:31
(anonymous) @ editor.main.js:31
n.Class.derive._oncancel @ editor.main.js:31
t.asWinJsPromise @ editor.main.js:31
(anonymous) @ editor.main.js:31
c @ editor.main.js:31
e.beginCompute @ editor.main.js:31
e.onModelChanged @ editor.main.js:31
(anonymous) @ editor.main.js:31
e.invoke @ editor.main.js:31
e.fire @ editor.main.js:31
t @ editor.main.js:31
(anonymous) @ editor.main.js:31
T @ editor.main.js:31
k @ editor.main.js:31
MonacoEditor.create @ monaco-editor.ts:73
MonacoEditor @ monaco-editor.ts:61
(anonymous) @ monaco-editor-provider.ts:97
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
fulfilled @ monaco-editor-provider.ts:6
Promise.then (async)
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
__awaiter @ monaco-editor-provider.ts:6
MonacoEditorProvider.createMonacoEditor @ monaco-editor-provider.ts:94
MonacoEditorProvider.createEditor @ monaco-editor-provider.ts:88
(anonymous) @ monaco-editor-provider.ts:74
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
fulfilled @ monaco-editor-provider.ts:6
Promise.then (async)
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
__awaiter @ monaco-editor-provider.ts:6
MonacoEditorProvider.get @ monaco-editor-provider.ts:61
(anonymous) @ monaco-frontend-module.ts:53
(anonymous) @ editor-widget-factory.ts:38
step @ editor-widget-factory.ts:6
(anonymous) @ editor-widget-factory.ts:6
fulfilled @ editor-widget-factory.ts:6
Promise.then (async)
step @ editor-widget-factory.ts:6
(anonymous) @ editor-widget-factory.ts:6
__awaiter @ editor-widget-factory.ts:6
EditorWidgetFactory.createEditor @ editor-widget-factory.ts:36
EditorWidgetFactory.createWidget @ editor-widget-factory.ts:33
(anonymous) @ widget-manager.ts:110
step @ widget-manager.ts:6
(anonymous) @ widget-manager.ts:6
fulfilled @ widget-manager.ts:6
Promise.then (async)
step @ widget-manager.ts:6
(anonymous) @ widget-manager.ts:6
__awaiter @ widget-manager.ts:6
WidgetManager.getOrCreateWidget @ widget-manager.ts:100
ShellLayoutRestorer.convertToWidget @ shell-layout-restorer.ts:184
_loop_1 @ shell-layout-restorer.ts:155
(anonymous) @ shell-layout-restorer.ts:154
ShellLayoutRestorer.inflate @ shell-layout-restorer.ts:150
(anonymous) @ shell-layout-restorer.ts:72
step @ shell-layout-restorer.ts:6
(anonymous) @ shell-layout-restorer.ts:6
fulfilled @ shell-layout-restorer.ts:6
Promise.then (async)
step @ shell-layout-restorer.ts:6
(anonymous) @ shell-layout-restorer.ts:6
__awaiter @ shell-layout-restorer.ts:6
ShellLayoutRestorer.initializeLayout @ shell-layout-restorer.ts:68
(anonymous) @ frontend-application.ts:88
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
fulfilled @ frontend-application.ts:6
Promise.then (async)
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
__awaiter @ frontend-application.ts:6
FrontendApplication.start @ frontend-application.ts:86
start @ index.js:22
Promise.then (async)
Object.defineProperty.value @ index.js:54
__webpack_require__ @ bootstrap bf13eeb29b764602482e:659
Object.defineProperty.value @ bootstrap bf13eeb29b764602482e:708
(anonymous) @ bootstrap bf13eeb29b764602482e:708
08:28:05.919 logger.ts:60 Cannot read property 'getConfig' of undefined
log @ logger.ts:60
t.logOnceWebWorkerWarning @ editor.main.js:31
t._getOrCreateWorker @ editor.main.js:31
t._getProxy @ editor.main.js:31
t._withSyncedResources @ editor.main.js:31
t.computeLinks @ editor.main.js:31
(anonymous) @ editor.main.js:31
then @ editor.main.js:31
provideLinks @ editor.main.js:31
(anonymous) @ editor.main.js:31
(anonymous) @ editor.main.js:31
n.Class.derive._oncancel @ editor.main.js:31
t.asWinJsPromise @ editor.main.js:31
(anonymous) @ editor.main.js:31
c @ editor.main.js:31
e.beginCompute @ editor.main.js:31
e.onModelChanged @ editor.main.js:31
(anonymous) @ editor.main.js:31
e.invoke @ editor.main.js:31
e.fire @ editor.main.js:31
t @ editor.main.js:31
(anonymous) @ editor.main.js:31
T @ editor.main.js:31
k @ editor.main.js:31
MonacoEditor.create @ monaco-editor.ts:73
MonacoEditor @ monaco-editor.ts:61
(anonymous) @ monaco-editor-provider.ts:97
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
fulfilled @ monaco-editor-provider.ts:6
Promise.then (async)
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
__awaiter @ monaco-editor-provider.ts:6
MonacoEditorProvider.createMonacoEditor @ monaco-editor-provider.ts:94
MonacoEditorProvider.createEditor @ monaco-editor-provider.ts:88
(anonymous) @ monaco-editor-provider.ts:74
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
fulfilled @ monaco-editor-provider.ts:6
Promise.then (async)
step @ monaco-editor-provider.ts:6
(anonymous) @ monaco-editor-provider.ts:6
__awaiter @ monaco-editor-provider.ts:6
MonacoEditorProvider.get @ monaco-editor-provider.ts:61
(anonymous) @ monaco-frontend-module.ts:53
(anonymous) @ editor-widget-factory.ts:38
step @ editor-widget-factory.ts:6
(anonymous) @ editor-widget-factory.ts:6
fulfilled @ editor-widget-factory.ts:6
Promise.then (async)
step @ editor-widget-factory.ts:6
(anonymous) @ editor-widget-factory.ts:6
__awaiter @ editor-widget-factory.ts:6
EditorWidgetFactory.createEditor @ editor-widget-factory.ts:36
EditorWidgetFactory.createWidget @ editor-widget-factory.ts:33
(anonymous) @ widget-manager.ts:110
step @ widget-manager.ts:6
(anonymous) @ widget-manager.ts:6
fulfilled @ widget-manager.ts:6
Promise.then (async)
step @ widget-manager.ts:6
(anonymous) @ widget-manager.ts:6
__awaiter @ widget-manager.ts:6
WidgetManager.getOrCreateWidget @ widget-manager.ts:100
ShellLayoutRestorer.convertToWidget @ shell-layout-restorer.ts:184
_loop_1 @ shell-layout-restorer.ts:155
(anonymous) @ shell-layout-restorer.ts:154
ShellLayoutRestorer.inflate @ shell-layout-restorer.ts:150
(anonymous) @ shell-layout-restorer.ts:72
step @ shell-layout-restorer.ts:6
(anonymous) @ shell-layout-restorer.ts:6
fulfilled @ shell-layout-restorer.ts:6
Promise.then (async)
step @ shell-layout-restorer.ts:6
(anonymous) @ shell-layout-restorer.ts:6
__awaiter @ shell-layout-restorer.ts:6
ShellLayoutRestorer.initializeLayout @ shell-layout-restorer.ts:68
(anonymous) @ frontend-application.ts:88
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
fulfilled @ frontend-application.ts:6
Promise.then (async)
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
__awaiter @ frontend-application.ts:6
FrontendApplication.start @ frontend-application.ts:86
start @ index.js:22
Promise.then (async)
Object.defineProperty.value @ index.js:54
__webpack_require__ @ bootstrap bf13eeb29b764602482e:659
Object.defineProperty.value @ bootstrap bf13eeb29b764602482e:708
(anonymous) @ bootstrap bf13eeb29b764602482e:708
08:28:09.696 logger.ts:60 Cannot read property 'getConfig' of undefined
log @ logger.ts:60
t.logOnceWebWorkerWarning @ editor.main.js:31
t._getOrCreateWorker @ editor.main.js:31
t._getProxy @ editor.main.js:31
t._getForeignProxy @ editor.main.js:31
t.getProxy @ editor.main.js:31
e._getClient @ jsonMode.js:7
e.getLanguageServiceWorker @ jsonMode.js:7
c @ jsonMode.js:8
e._doValidate @ jsonMode.js:7
r @ jsonMode.js:7
e @ jsonMode.js:7
t @ jsonMode.js:8
(anonymous) @ monaco.contribution.js:7
t._invokeFactory @ loader.js:7
t.complete @ loader.js:7
s._onModuleComplete @ loader.js:7
s._onModuleComplete @ loader.js:7
s._resolve @ loader.js:7
s.defineModule @ loader.js:7
o @ loader.js:7
(anonymous) @ jsonMode.js:8
(anonymous) @ jsonMode.js:8
08:28:09.700 logger.ts:60 TypeError: self.require is not a function
    at editor.main.js:31
    at new n.Class.derive._oncancel (editor.main.js:31)
    at t.e.loadForeignModule (editor.main.js:31)
    at editor.main.js:31
    at then (editor.main.js:31)
    at t._getForeignProxy (editor.main.js:31)
    at t.getProxy (editor.main.js:31)
    at e._getClient (jsonMode.js:7)
    at e.getLanguageServiceWorker (jsonMode.js:7)
    at e.c [as _worker] (jsonMode.js:8)
log @ logger.ts:60
(anonymous) @ jsonMode.js:7
then @ editor.main.js:31
e._doValidate @ jsonMode.js:7
r @ jsonMode.js:7
e @ jsonMode.js:7
t @ jsonMode.js:8
(anonymous) @ monaco.contribution.js:7
t._invokeFactory @ loader.js:7
t.complete @ loader.js:7
s._onModuleComplete @ loader.js:7
s._onModuleComplete @ loader.js:7
s._resolve @ loader.js:7
s.defineModule @ loader.js:7
o @ loader.js:7
(anonymous) @ jsonMode.js:8
(anonymous) @ jsonMode.js:8

```

**Comment by kittaakos** [comment]
I can see this when I start the electron version on OS X. @akosyakov, you did not notice these problems, right?
screen shot 2018-02-21 at 08 33 07

**Comment by akosyakov** [comment]
I've seen browser warnings/errors but they did not seem to break the app. Would it be fine to look at them separately?

For Electron, I have not seen it.

**Comment by akosyakov** [comment]
@kittaakos fine to merge and look at other issues later? Could you approve if so?

**Comment by kittaakos** [comment]
Is it urgent to merge?

**Comment by kittaakos** [comment]
Let me double check the changes from the PR. I try them out again right now. If the PR introduces a problem and removing the `requirejs` dependency is not mandatory for something else, I do not think we should merge this.

**Comment by akosyakov** [comment]
`requirejs` should not be needed at all. I had introduced it to trick webpack into loading monaco in the browser, but it is not an issue since we refactored monaco loading via the dynamic script element.

**Comment by akosyakov** [comment]
no, it is not really urgent, I can have a look at remaining issues, but it won't happen today

**Comment by kittaakos** [comment]
I can confirm, the above-mentioned problem happens on the `master` branch as well. It occurs when one refreshes the browser window.

**Comment by benoitf** [comment]
is that requirejs (or amd loader) shouldn't allow isolation of code for ppl wanted to have code isolation ?

**Comment by akosyakov** [comment]
@benoitf we don't use requirejs for module resolution, for the frontend it is done at the buildtime via webpack, for the backend we use Node.JS module resolution. Please file an issue to discuss code isolation, why you need it and how it can be achieved.

**Pull request merged**
