### PR TITLE
[quality] add some selected rules to dev.tslint.json

### PR DESCRIPTION
**Pull request by marcdumais-work**

### CODE REVIEW

**Comment by akosyakov** [comment]
I think these also could be included:
- https://palantir.github.io/tslint/rules/interface-over-type-literal/
- https://palantir.github.io/tslint/rules/arrow-return-shorthand/
- https://palantir.github.io/tslint/rules/no-shadowed-variable/
- https://palantir.github.io/tslint/rules/no-construct/
- https://palantir.github.io/tslint/rules/no-any/

**Comment by akosyakov** [comment]
Do we agree not to sign off commits? :)

**Comment by marcdumais-work** [comment]
Cool. I'll add them and push an updated PR.

**Comment by marcdumais-work** [comment]
Right - I did not sign the commit. It was an oversight on my part, not a statement :) I'll sigh the updated one, until we come to a conclusion regarding this.

**Pull request merged**
