### PR TITLE
[Plugin-API Make possiblee to disable cancellation token in the rpc-protocol

### LINKED ISSUE #4957: [Plugin-API] Redundant 'CancellationToken' argument is present in each rpc-request
### Description
 
On each rpc-request a new argument 'CancellationToken' is added to the arguments array: 
https://github.com/theia-ide/theia/blob/2a2a6010329850e79b508b2133a62749d2d39e05/packages/plugin-ext/src/api/rpc-protocol.ts#L179-L181

It causes a wrong behavior of `VsCode Git Extention`. On executing some commands, the extension handles received arguments and 'CancellationToken' object influences on the commands result:
https://github.com/Microsoft/vscode/blob/7d39e805fb66a6eac22f19af8bb90f48da863fd5/extensions/git/src/commands.ts#L649-L677

The command handles `resourceStates: SourceControlResourceState[]` It converts the argument to `undefined` and adds to `uri` array. While iterating the array `workspace.openTextDocument(uri)` with `undefined` is applied: https://github.com/Microsoft/vscode/blob/7d39e805fb66a6eac22f19af8bb90f48da863fd5/extensions/git/src/commands.ts#L692

Related Commit: https://github.com/theia-ide/theia/commit/4286ebd7a63f32951ac5a8df85ac788f23a54e0f
Is needed for #4103

@akosyakov  WDYT? 

**OS and Theia version:**

**Diagnostics:**

### PR DESCRIPTION
**Pull request by vinokurig**
Check for an `'disable.cancellation.token'` to to disable creation of cancelation token in the rpc-protocol.
fixes #4957
is needed for https://github.com/theia-ide/theia/pull/4279

### CODE REVIEW

**Comment by vinokurig** [comment]
@akosyakov I've reworked the way of identifying the token. Now, on the client side when a token is present in the arguments we pass a flag, and the on the other side we add add a token only if it is needed. Could you please review.

**Comment by vinokurig** [comment]
@akosyakov
> Please make CancellationToken mandatory here and here, since an implementation assumes that a token is always provided.

`CancellationToken` is not provided in `tasks-main.ts`: 
https://github.com/vinokurig/theia/blob/56e8b2350b7970fac470ee146509f430f7e5ce3c/packages/plugin-ext/src/main/browser/tasks-main.ts#L103-L127
Should I make the `CancellationToken` mandatory only for `LanguagesExt`?

**Comment by akosyakov** [comment]
@vinokurig please check implementation of `TaskExt` as well, it should handle the case then token is not provided

**Comment by vinokurig** [comment]
@akosyakov Fixed `TasksExtImpl` can we go with it?

**Comment by akosyakov** [comment]
@vinokurig yes, if travis is green, please merge

**Pull request merged**
