### PR TITLE
Fix execution of configured tasks

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Fix execution of configured tasks

### What issues does this PR fix or reference?
- fixes for tasks provided by plugins: https://github.com/theia-ide/theia/issues/5064 and  https://github.com/theia-ide/theia/issues/5067

### How to test
Use the components in your devfile

```
- 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
    type: cheEditor
  
  - 
    id: che-incubator/typescript/1.30.2
    type: chePlugin
    memoryLimit: 2048M

``` 
Try to configure some `detected` task and then run it. Also you can try to run the task after refreshing page from `recently used` section
Note: you can not see output for tasks provided by plugins, because of https://github.com/eclipse/che/issues/13876, but you can see events that task has started or completed.

Please see the video:https://youtu.be/3KB1GvwXH_M

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
@evidolob @vince-fugnitto @elaihau 
This is PR for che-7.0.0 branch, not for master branch.

**Comment by akosyakov** [comment]
@vince-fugnitto Why @elaihau cannot review it?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Why @elaihau cannot review it?

He of course can, I was just thinking it wasn't necessary since he's currently at a limited capacity and the feature is `che` specific (che branch).

**Comment by akosyakov** [comment]
Super confusing, @RomanNikitenko how do you are going to consume these changes? Why don't you rebind these services in Che Theia and customize as other clients do?

**Comment by RomanNikitenko** [comment]
@akosyakov 
I don't need to customize something here. I just try to fix the bugs defined in the PR description for 0.8.0 version.  For master branch it's not relevant because the behavior for `detected` tasks was changed.
I described it [here](https://github.com/theia-ide/theia/issues/5747).

thank you for your advice and your wish to help!

**Comment by akosyakov** [comment]
@RomanNikitenko Do you mean that we should do 0.8.1 bug fix release? @elaihau yes? If not what we supposed to do with this branch? If you need to fix something for Che, then we have DI that one can subclass and overwrite bogus classes, and then rollback it after going to 0.9.

**Comment by evidolob** [comment]
We don't need to have release(at least for now), we build Theia from sources.
I write an email for theia-dev eclipse mailing list that we will use that branch for Che 7 release.
I will delete this `che-7.0.0` branch in next few mounts, but first I will ask to create tag from that branch. 
It looks like this PR will be only one fix which doesn't exist in `master` branch.

**Comment by akosyakov** [comment]
@evidolob please announce it on spectrum and join dev meeting to discuss it today

**Comment by akosyakov** [comment]
I've updated an agenda: https://github.com/theia-ide/theia/wiki/Dev-Meetings#agenda-2019-07-23

**Pull request merged**
