### PR TITLE
Aligned keybindings with VSCode

### LINKED ISSUE #5303: [keybindings] Allow removal rules in keybindings
We should support the removal syntax E.g. { "key": "ctrl+3", "command": "-explorer.newFile" } (the - before explorer.newFile) that allows us to remove a specific keybinding.

See: https://code.visualstudio.com/docs/getstarted/keybindings#_removing-a-specific-key-binding-rule

### PR DESCRIPTION
**Pull request by akosyakov**
fixed #5303

It's rebase of https://github.com/theia-ide/theia/pull/5326, since the original PR is opened from a fork without right to commit for maintainers.

### CODE REVIEW

**Comment by akosyakov** [comment]
@vince-fugnitto Could you test whether the keybinding widget still shows context and source properly? There was a merge conflict with it. If it is fine please approve and we can merge it.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto Could you test whether the keybinding widget still shows context and source properly? There was a merge conflict with it. If it is fine please approve and we can merge it.

It seems to work correctly, but the `reset` code in the `keybindings-widget` needs to be adjusted.
It looks like when the keybinding resets (goes back to its default value), the removal rules are not removed from the `keymaps.json`.

Example:
1. update a command's keybinding.
```json
[
    {
        "command": "core.close.tab",
        "keybinding": "alt+a",
        "context": ""
    },
    {
        "command": "-core.close.tab",
        "keybinding": "alt+w",
        "context": ""
    }
]
```

2. Perform a reset (the following remains in the `keymaps.json`).

```json
[
    {
        "command": "-core.close.tab",
        "keybinding": "alt+w",
        "context": ""
    }
]
```
Is it outside the scope of the PR?

**Comment by akosyakov** [comment]
@vince-fugnitto I've seen it, but it does not seem to break keybindings handling? Does it?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I've seen it, but it does not seem to break keybindings handling? Does it?

I'm not sure, but I do know that if I have a custom keybinding that I set, then reset it, I lose the original keybinding due to the removal rule.

For example:
1. I update the keybinding for `Close Tab` from <kbd>alt</kbd>+<kbd>w</kbd> to <kbd>alt</kbd>+<kbd>a</kbd>
2. the keybinding <kbd>alt</kbd>+<kbd>w</kbd> no longer works while <kbd>alt</kbd>+<kbd>a</kbd> now does
3. I reset the `Close Tab` keybinding
4. The removal rule for <kbd>alt</kbd>+<kbd>w</kbd> still exists in the `keymaps.json` meaning I now lost the keybinding

**Comment by akosyakov** [comment]
> The removal rule for alt+w still exists in the keymaps.json meaning I now lost the keybinding

@vince-fugnittoI thought `-` means that a keybinding should not be considered. It should not mean that it should be removed. Checking again...

**Comment by vince-fugnitto** [comment]
> > The removal rule for alt+w still exists in the keymaps.json meaning I now lost the keybinding
> 
> @vince-fugnitto I thought `-` means that a keybinding should not be considered. It should not mean that it should be removed. Checking again...

Sorry if I'm being confusing, when I mean removed I mean that I can no longer use that keybinding as a user, the command becomes useless. I attempt to close tabs using the default keybinding and it no longer works (since it exists in the keymaps as a removal rule).

**Comment by akosyakov** [comment]
@vince-fugnitto tried and was able to reproduce your issue, could you please comment it on the original PR https://github.com/theia-ide/theia/pull/5326, it should be taken care of before merging. I'm closing this PR.

**Pull request closed without merging**
