### PR TITLE
Electron zooming commands

### PR DESCRIPTION
**Pull request by akosyakov**
Fixing follow up bugs after https://github.com/theia-ide/theia/pull/708 and add zooming support.

Fixes https://github.com/theia-ide/theia/issues/702

### CODE REVIEW

**Comment by kittaakos** [comment]
The zoom in/out and reset works. Also, reload window. I did the following to verify it:
```
yarn --version \
&& node --version \
&& npm --version \
&& mkdir zoom \
&& cd zoom \
&& git clone https://github.com/theia-ide/theia.git \
&& cd theia \
&& git checkout origin/ak/electron_commands -B ak/electron_commands \
&& yarn \
&& yarn run rebuild:electron \
&& cd examples/electron \
&& yarn run start
```

Once you have the green builds, please merge. We can renem `RESET_ZOOM` to `ZOOM_RESET` later. Just to have consistent commands.

**Comment by akosyakov** [comment]
@kittaakos can you approve explicitly?

**Comment by kittaakos** [comment]
> after

**Comment by akosyakov** [comment]
It only osx build was not green.

**Pull request merged**
