### PR TITLE
[preview/markdown] Fix reveal of source for empty regions

### LINKED ISSUE #2322: [preview/markdown] Does not open Code Editor if file is empty
Same applies for the region after rendered content. I think it's because it cannot determine a line number in source, but it should just open at the end.

### PR DESCRIPTION
**Pull request by AlexTugarev**
- improves navigation started with double-click in preview widget
- get rid of `throttle-debounce` (one lib is enough!)

Fixes #2322

### CODE REVIEW

**Comment by AlexTugarev** [comment]
'Fixed failing test.

**Comment by kittaakos** [comment]
I am reviewing it now...

**Comment by kittaakos** [comment]
Quick question: when there is an `md` file, let's say with 20 empty lines. Where should be the cursor/selection when opening the Code Editor from the Preview (with the double-click)? Thanks!

**Comment by kittaakos** [comment]
> Where should be the cursor/selection

In line [`0`](https://github.com/theia-ide/theia/pull/2355/files#diff-3e4ceff226a708d0379574d442b85548R268).

**Comment by AlexTugarev** [comment]
> Quick question: when there is an md file, let's say with 20 empty lines. Where should be the cursor/selection when opening the Code Editor from the Preview (with the double-click)? Thanks!

@kittaakos the mapping between source lines and rendered html is only a approximation. the generation of some opening tags is overridden to insert the line information, see [here](https://github.com/theia-ide/theia/blob/master/packages/preview/src/browser/markdown/markdown-preview-handler.ts#L218). in between of two annotated elements in the output, we can just approximate the line number.

the question about empty lines, well you already did answer that. just wanted to add, how it comes, that there would be no line information available.

**Comment by kittaakos** [comment]
Thanks, for the details. I was a bit puzzled:

From the [task](https://github.com/theia-ide/theia/issues/2322#issue-339740762):

> [...] cannot determine a line number in source [...] it should just open at the end.

And it opened in line `0`. But the behavior was in sync with the code. I just did not know what to expect.

**Comment by AlexTugarev** [comment]
You are right @kittaakos! Task and PR diverged, and honestly I just forgot to mention it. :-( 

I solution I've chosen over the previously targeted one is way simpler as it opens at the beginning if no line is found, but it then it syncs editor and preview.

**Pull request merged**
