### PR TITLE
Issue #545 add missing dependencies for the loaders.

### PR DESCRIPTION
**Pull request by lmcbout**
Signed-off-by: Jacques Bouthillier <Jacques.bouthillier@ericsson.com>

### CODE REVIEW

**Comment by lmcbout** [comment]
Good, I will push if the build is successful

**Comment by hexa00** [comment]
It should update yarn.lock too ?

**Comment by lmcbout** [comment]
yarn.lock has been added to this pr, waiting for it to compile now

**Comment by hexa00** [comment]
Thanks please merge after the tests pass

**Comment by lmcbout** [comment]
Just finishing compiling and is successful.

**Pull request merged**
