### PR TITLE
Add "native-keymap" dependency to @theia/core

### PR DESCRIPTION
**Pull request by evidolob**
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
We are removing them on purporse they should be used only for Electron via `@theia/electron`.

**Comment by evidolob** [comment]
But `NativeKeyboardLayoutProvider` still in `node` folder.

**Comment by evidolob** [comment]
@akosyakov When I run fresh Theia I got error:
```
node src-gen/backend/main.js /projects --hostname=0.0.0.0
/home/theia/node_modules/@theia/core/lib/node/main.js:56
    throw reason;
    ^

Error: Cannot find module 'native-keymap'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/theia/node_modules/@theia/core/lib/node/keyboard/native-keyboard-layout-provider.js:24:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by akosyakov** [comment]
@evidolob it's a bug it should go to electron-browser, i will open a PR
and assign you for a review

**Comment by evidolob** [comment]
@akosyakov OK, thank you!

**Pull request closed without merging**
