### PR TITLE
GH-147: Enabled Windows CI

### PR DESCRIPTION
**Pull request by kittaakos**
Task: #147 
Closes: #147

### CODE REVIEW

**Comment by kittaakos** [comment]
Once the PR is accepted and merged, I add the badge to the main Github page, plus I enable the hook for Gitter.

**Comment by kittaakos** [comment]
I do not like this PR. There are too many commits. I close this, and create a new one.

**Comment by akosyakov** [comment]
Changes are looking very good to me. But the history has a lot of commits which did not make to the final. I can see that 5 things were done: fixed electron-rebuild, wdio config, package generation, lerna calling and added the script for windows.

**Comment by kittaakos** [comment]
New PR is here: #381.

**Comment by hexa00** [comment]
Just curious is there a reason you created a new one rather than doing a force push?

**Pull request closed without merging**
