### PR TITLE
fix #2710: add startup-timeout option

### LINKED ISSUE #2710: Backend fails to start possibly because of a timeout
The server worker startup fails for me from time to time with the following output:
```
time yarn start --hostname=0.0.0.0
yarn run v1.9.4
$ theia start --hostname=0.0.0.0
Starting server worker...
Server worker has been started. [ID: 1 | PID: 1558]
Server worker failed to start.
Server worker is ready to accept messages. [ID: 1 | PID: 1558]
Server worker has been disconnected. [ID: 1 | PID: 1558]
^CCommand terminated by signal 2
real 0m 16.72s
user 0m 3.26s
sys 0m 0.21s
```

I terminated the command immediately after the "...has been disconnected" message. The host machine is a Raspberry Pi. A timeout seems a probable cause.

### PR DESCRIPTION
**Pull request by akosyakov**
To review in Gitpod: https://gitpod.io#https://github.com/theia-ide/theia/pull/2811

You can play around with `yarn start --startup-timeout x` in the browser example to verify it.

### CODE REVIEW

**Comment by akosyakov** [comment]
@mathansen Can you try and review it?

**Comment by marechal-p** [comment]
```
yarn start --startup-timeout 30
yarn run v1.9.4
$ theia start --startup-timeout 30
Starting server worker...
Server worker has been started. [ID: 1 | PID: 23811]
Server worker is ready to accept messages. [ID: 1 | PID: 23811]
Server worker has been disconnected. [ID: 1 | PID: 23811]
Server worker failed to start within 30 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
Done in 1.10s.
```
Hmmm, something seems off with the way the timeout is processed. Command ran in 1.10s yet the 30 second timeout failed?

**Comment by marechal-p** [comment]
Thinking out loud: Do you think it would be nicer to be able to input the timeout value as `5s` or `2m` ?

I got confused by the milliseconds, I may not be the last to do it I think.

**Comment by akosyakov** [comment]
@marechal-p I don't oppose an idea but want to have a fix, please file an issue to improve the input format

**Comment by mathansen** [comment]
Thanks for the fix! I wasn't able to verify it yet as I was out of the office. If you don't hear from me then everything is fine.

**Pull request merged**
