### PR TITLE
GH-4209: From now on, Theia is not shipped with Git.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes: #4209.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by kittaakos** [comment]
Note, we [neither notify the user](https://github.com/theia-ide/theia/issues/3874), nor disable the Git UI if the executable is not on the PATH.

**Comment by marcdumais-work** [comment]
@kittaakos Thanks for this PR. This is a sad lost of functionality and convenience, so I suggest we wait for Sharon's response to Simon's arguments before merging. 

I wonder if any distribution of anything GPL, even if not "linked-with" by anything, is to be completely avoided? Extreme example: what if a GPL-licensed poem was included in a production npm package we use/need? 

---

To test the PR I momentarily renamed my system's git executable so that it would not be found and restarted the backend and frontend. I am not sure if this is valid, or if dugite might be confused by the presence of other git-related things still present. 

In any case, it seems that dugite is trying to spawn a git (system's? removed previously bundled?, Every few seconds I see this exception in the BE logs: 

```
root ERROR Error occurred while synchronizing the status of the repository. file:///home/marc/dev/theia Error: Git could not be found at the expected path: '/home/marc/dev/theia/node_modules/dugite-no-gpl/git/bin/git'. This might be a problem with how the application is packaged, so confirm this folder hasn't been removed when packaging.
    at /home/marc/dev/theia/node_modules/dugite-no-gpl/build/lib/git-process.js:87:39
    at exithandler (child_process.js:283:5)
    at ChildProcess.errorhandler (child_process.js:295:5)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:196:12)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```

**Comment by AlexTugarev** [comment]
Just tried that change and made sure git is not available.

@kittaakos, you are right about the gap in notification part. what we could do is, to add error handling e.g. at the [`git.repositories`](https://github.com/theia-ide/theia/blob/01667babcb9fb7f94f63a37b5229e2b684dc6534/packages/git/src/browser/git-repository-provider.ts#L148) call and let it flow through the `GitErrorHandler`. WDYT? 

also, it looks like the scripts to download the git package are still available. which means, in theory, we could provide an action to call that afterwards. this again would be much easier if the notification is send from the backend.

**Comment by marcdumais-work** [comment]
@kittaakos based on the post below, even if the GPL content is not used (or "linked-to"), the distribution aspect requires board approval, estimated to take several weeks. I lean towards not going-down that road, but I am open to contrary opinions. Permitting or even facilitating the end-user triggering the `dugite-bundled` git download script is a good idea and AFAIK perfectly legal (IINAL). 

https://spectrum.chat/theia/dev/potentially-huge-issue-gpl-code-downloaded-by-dugite~289c696e-b241-4c7e-84aa-8859fcc89e4d?m=MTU0OTE0NTc0MTQwMg==

**Comment by svenefftinge** [comment]
I really think we should remove the auto-downloaded git. It is fair to assume that developers are able to install git on their machines. That said it would be nice to have a message telling the user so.

**Comment by kittaakos** [comment]
> It is fair to assume that developers are able to install git on their machines.

We might have electron users on Windows who are not developers.

**Comment by sunix** [comment]
Maybe out of scope of this issue: what replacing dugite with vscode git extension ?

**Comment by marcdumais-work** [comment]
@kittaakos 
> It is expected. The code is the same, we use a `dugite` fork without the executables.

Ok. I am good with merging this ASAP so we can submit an updated CQ and unblock.  Further polishing can be undertaken in a new PR. 

P.S. Ironically, we should technically seek CQ approval before merging this, since version of prereq dependencies have changed. Let's not.

**Comment by marcdumais-work** [comment]
@svenefftinge @akosyakov Are you ok with merging this PR as it is now?

**Comment by marcdumais-work** [comment]
ping

**Comment by kittaakos** [comment]
I can push the merge button if we are good with this state.
 - The custom `dugite` fork does not download the executable, hence no GPL code.
 - Theia will use Git from the `PATH`.
 - No user notification if Git is not on the `PATH`.
 - The UI will be always enabled, even if Git is not on the `PATH`. In such cases, [it won't work](https://github.com/theia-ide/theia/pull/4210#issuecomment-459528944).

**Comment by AlexTugarev** [comment]
> No user notification if Git is not on the `PATH`.

@kittaakos, I discussed that with @akosyakov, and already started trying something that to solve the MessageService issue. We need to bind some parts in connection scope. I'll try to wrap it up today/tomorrow.

**Comment by kittaakos** [comment]
This is ready for the review. Current state:
 - We do not ship the Git executable with the application.
 - If Git is not on the `PATH`, we notify the clients. Thank you, @AlexTugarev!

**Comment by phaumer** [comment]
Is this PR planned for 0.3.20?

**Comment by marcdumais-work** [comment]
@kittaakos is there anything blocking merging this PR?

**Comment by kittaakos** [comment]
@marcdumais-work, there are test failures on Travis. It is a generic problem. I am looking into it.

**Comment by marcdumais-work** [comment]
Looks like we proceed and merge this PR?

**Comment by marcdumais-work** [comment]
Thanks - I have updated our blocked CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18717#c21

**Pull request merged**
