### PR TITLE
[debug] Add "debug" progress indicator

### LINKED ISSUE #5988: Show progress in Debug view
As a follow-up of https://github.com/theia-ide/theia/pull/5830.

It would be nice to see a progress indicator for debug actions similar to git/scm.

### PR DESCRIPTION
**Pull request by AlexTugarev**
#### What it does
Adds a progress bar to the debug view.

Fixes #5988

#### How to test
- start a debugging session and see a progress indicator

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@AlexTugarev is it ready for a review?

**Comment by westbury** [comment]
Can we make this progress support progress percentage?  We have debug adaptors that report the percent in the OutputEvent:
```
new OutputEvent('progress', 'telemetry', {
            percent,
            message
        }
```
We know the progress percent because we get this from the process when downloading the image.

Currently this ends up at logOutput in DebugConsoleSession.  It would be nice if this percent could be shown in this progress monitor.

**Comment by akosyakov** [comment]
@westbury Could you please accept an invitation to the organization? That i can assign you for a review.

**Comment by AlexTugarev** [comment]
@westbury can you elaborate on the intent of this information? it looks like you're talking about telemetry data. well, that would not be the idea of this PR to bring progress indication as it's done in vscode; shame on me I didn't mentioned that before!

**Comment by thegecko** [comment]
@AlexTugarev 

> that would not be the idea of this PR to bring progress indication

Perhaps the PR should be rename `activity indication` 😄 
I think the point here is that it's possible to have sources of richer progress data and this PR doesn't currently allow exposing in this richer data.

It's just a suggestion, the addition as it stands is an improvement.

**Comment by AlexTugarev** [comment]
@thegecko, the term "progress indicator"  is used for indeterminate indicators e.g. in vscode and [material design](https://material.io/components/progress-indicators/). I'd like to stick with that. 

> I think the point here is that it's possible to have sources of richer progress data and this PR doesn't currently allow exposing this richer data in the UI. 

The progress bars integrated into scm/git, search, and debug as proposed in this PR, are linked to a "progress location" with the id `debug` which allows different tasks to indicate progress, cf. currently the single call site https://github.com/theia-ide/theia/blob/bb37bd1c15ffd5165ceaafa6937c38e499d1853c/packages/debug/src/browser/debug-session-manager.ts#L146
Other components may report progress to this location as well. I think it fits quite well to render an  indeterminate indicator, especially when a user might not understand where the length of a process comes from.

Generally the `ProgressService` does support reporting of progress updates as it is done already for the `window` (aka status bar) location, cf. https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/progress-status-bar-item.ts#L58. So, it depends on what you would like to render in the first place. The progress bar can aggregate multiple tasks to show an indeterminate progress indicator. I'm fully open to the idea of falling back to the current behavior, but showing a determinate progress there if there is only one progress source and it's reporting updates.

**Comment by akosyakov** [comment]
@AlexTugarev Are you going to merge it?

**Comment by AlexTugarev** [comment]
@westbury and @thegecko I like the idea to enhance it as suggested and created https://github.com/theia-ide/theia/issues/6043 as a followup.

**Pull request merged**
