### PR TITLE
Minor change to properly find plugins by path for VS Code plugins on …

### PR DESCRIPTION
**Pull request by paigeibm**
…the Windows platform.

Signed-off-by: Paige J. Sullivan <psullivan@ibm.com>

### CODE REVIEW

**Comment by benoitf** [comment]
@paigeibm it's about a trailing / ?

**Comment by paigeibm** [comment]
Yep.  That's literally all the problem was.

**Comment by benoitf** [comment]
should wecheck the last char before removing it ? If there is no trailing /

**Comment by paigeibm** [comment]
> should wecheck the last char before removing it ? If there is no trailing /

It won't really matter, as it'll still match because it uses the .beginsWith method.

**Comment by vince-fugnitto** [comment]
@paigeibm do you mind squashing your commits into a singular commit containing the necessary fix?
I see that the commit e15f60f91ec45f7b206809f202a004a023f0af6e simply fixed the first commit (whitespace).

**Comment by paigeibm** [comment]
Fixed in commit 6893c4cf

**Pull request closed without merging**
