### PR TITLE
Typo in description of Range class

### PR DESCRIPTION
**Pull request by yotamshapira**

### CODE REVIEW

**Comment by benoitf** [comment]
@yotamshapira thank you for the fix. Could you please add a Signed-off to your commit message so the "DCO" check will be green (and then we can accept your contribution) thanks.

**Comment by benoitf** [comment]
https://github.com/theia-ide/theia/pull/3763/checks?check_run_id=38304677

**Comment by marcdumais-work** [comment]
Hi @yotamshapira ,

In order for us to merge your contribution, you will also need to sign the Eclipse Foundation ECA: https://www.eclipse.org/legal/ECA.php

Thanks!

**Comment by kittaakos** [comment]
@yotamshapira, you have to sign the ECA with your `yotam.shapira@sap.com` address. Otherwise, we cannot accept your contribution.

**Comment by yotamshapira** [comment]
> @yotamshapira hello, when checking with your email address used in Signed-Off it's telling me that ECA is not found for this user

Should be OK now, my bad

**Comment by yotamshapira** [comment]
@marcdumais-work can you please review this change?

**Comment by marechal-p** [comment]
ECA not found for `yotam.shapira@sap.com`

**Comment by yotamshapira** [comment]
@marechal-p - I signed the ECA under a different mail address - I have now fixed that, can you please check again?

**Comment by vince-fugnitto** [comment]
@yotamshapira sorry for taking a while, I just noticed this PR myself.
I see you now have a valid `eca` agreement for the following email ` yotam.shapira@sap.com` so I'll merge :)

<div align='center'>

screenshot from 2019-03-05 07-55-12

</div>

**Pull request merged**
