### PR TITLE
WIP Close widgets on resource disposal

### PR DESCRIPTION
**Pull request by akosyakov**
- This PR fixes https://github.com/theia-ide/theia/issues/560 by disposing a file resource on a file deletion.
- Widgets depending on resources get closed if underlying resources get disposed regardless whether they are dirty, e.g. editors for file resources. Copied this behaviour from VS code and IntelliJ.
- https://github.com/theia-ide/theia/issues/717 should be fixed with it as well, reacting to other files changes was covered by the save-cycle implementation.
- This PR allows exclusive file watching with the callback. As discussed in https://github.com/theia-ide/theia/issues/942#issuecomment-349909873, it is a temporary minimal change since API is confusing. It will be better to have 2 APIs: one low level for exclusive watching and the second on the top for watching workspace changes.
- This PR also fixes bugs in the user storage service.

### CODE REVIEW

**Comment by kittaakos** [comment]
@akosyakov, could you please take care of the timeouts on Appveyor by taking care of #860?

**Comment by kittaakos** [comment]
> could you please take care of the timeouts on Appveyor by taking care of #860?

Just in case you agree that the current Windows timeout issue is related to the ticket I have referenced above.

**Comment by akosyakov** [comment]
@kittaakos tests were broken for real

**Comment by hexa00** [comment]
>Widgets depending on resources get closed if underlying resources get disposed regardless whether they are dirty, e.g. editors for file resources. Copied this behaviour from VS code and IntelliJ.

I don't think that's true ? VS code will show the (delete from disk) and keep the editor if it's dirty. Which I think is the right thing to do. 

We should never lose unsaved information without user interaction.

**Comment by akosyakov** [comment]
@hexa00 true, somehow overlooked it

**Comment by akosyakov** [comment]
I will redo it, an idea to dispose a resource on a file deletion turned out to be bogus, a user should be able to preserve an editor with dirty changes and save a deleted resource.

**Comment by hexa00** [comment]
@akosyakov Just a ping is this still something planned ?

I ask because we would like to change the file watcher api a bit to allow "transactions" so that we don't get many events during a save for example and the decoupling discussed in #942 would be helpful.

**Comment by akosyakov** [comment]
@hexa00 I don't have time to look at it. Go ahead with your changes.

**Comment by akosyakov** [comment]
@hexa00 What do you mean about `transactions`. I think events should be filtered out in `NsfwFileSystemWatcherServer.pushFileChange`, where they get buffered.

**Comment by hexa00** [comment]
@akosyakov the idea would be to buffer the events based on an operation, like buffering all events that occur during a save, and send 1 merged notification about all events during that operation.

**Comment by hexa00** [comment]
This would remove the timeout heuristic use currently.

**Comment by akosyakov** [comment]
I thought we wanted to improve `FileStat` that it is not important how many events are there, we won't read if `FileStat` is not outdated. I think it is easier and less invasive than transactions approach.

**Comment by hexa00** [comment]
@akosyakov the thing is to know it's not updated you'll have to check by doing a hash... on each event.. otherwise you can't know.

Also this will be helpful I think for git as it could receive only 1 event with all the changes after an operation instead of generating a lot of updates.

**Comment by hexa00** [comment]
Started #1269 about this so we can discuss it there.

**Pull request closed without merging**
