### PR TITLE
RipgrepSearchInWorkspaceServer: reset style with --colors=X:none

### PR DESCRIPTION
**Pull request by eepp**

### CODE REVIEW

**Comment by eepp** [comment]
Looks like this is failing. My guess is that I did not modify the expected "match start" escape sequence, and this one contains a bold sequence (`\x1b\\[1m`), whereas ripgrep should not write bold sequences anymore with this patch.

**Comment by marcdumais-work** [comment]
@eepp Nice to see you in our neck of the woods. Thanks for the patch. Good work on the description in your commit massage.

**Comment by eepp** [comment]
> Could you update the PR?

@simark Do you prefer that I rebase this branch or that I push a fixup commit?

**Comment by simark** [comment]
You can amend the commit and force push.

**Pull request merged**
