### PR TITLE
support file searches with globs

### PR DESCRIPTION
**Pull request by elaihau**
- vscode.workspace.findFiles() requires the search service to support finding files with globs, while the theia service only supports string match at the moment. Since the Theia goal is making the plugin system compatible with vscode extensions, the glob support should be added to theia file search service.

Signed-off-by: elaihau <liang.huang@ericsson.com>

### CODE REVIEW

**Comment by elaihau** [comment]
This is the `vscode.workspace` api:
```ts
findFiles(include: GlobPattern, exclude?: GlobPattern | null, maxResults?: number, token?: CancellationToken): Thenable<Uri[]>
```
where an example of `GlobPattern` is something like "**/*work*": https://code.visualstudio.com/api/references/vscode-api#workspace

With the current theia code, if "**/*work*" is passed to `file-search-service`, an empty array will most likely be returned, as our service only support exact string match at the moment.

**Comment by kittaakos** [comment]
Nice addition, but I am a bit puzzled. Perhaps I misunderstood it. Can you please explain the following search results? Why do I see them?

Here, I have expected to see all the `package.json`s from the `packages` folder:
screen shot 2019-02-25 at 09 17 07

I do not know why I see anything any results here from `.git/logs/refs/remotes/origin` folder:
screen shot 2019-02-25 at 09 16 38

Is it possible to highlight the matches somehow:
screen shot 2019-02-25 at 09 26 56

**Comment by elaihau** [comment]
@kittaakos Thank you for the review !

>Here, I have expected to see all the `package.json`s from the `packages` folder:

I tested on both gitpod and my local env, and looks like it worked properly when i key-in `**/packages/**/package.json`:
peek 2019-02-25 06-59

**Comment by kittaakos** [comment]
> tested on both gitpod

Crazy. Thanks for checking! Something is odd either in my Chrome or with GItpod. I had an odd behavior when I was reviewing #4392 too. Can someone else verify this PR?

**Comment by elaihau** [comment]
> I do not know why I see anything from the `.git/logs/refs/remotes/origin` folder:

This one is interesting. I got what you saw when tried to search two stars: `**`. But with `**/examples` i don't get the result showed in your screenshot:

peek 2019-02-25 07-32

**Comment by elaihau** [comment]
>Is it possible to highlight the matches somehow

it would be a nice feature to add, but I am not sure how to implement it. can i create a github issue so that i can resolve it separately, after this one gets merged ?

**Comment by kittaakos** [comment]
> can i create a github issue so that i can resolve it separately,

Sure.

**Comment by elaihau** [comment]
@lmcbout I made the change that you and Marc suggested. Now the users don't have to key-in the trailing star (*).

**Comment by elaihau** [comment]
> the `*` character seems to be ignored in the file-quick-open widget.

You are right. vscode api supports globs, while the frontend ignores the stars (*).

> Back to Theia, IIUC this change was originally to fix the API for plugins, but why does it have an impact on the file search from the quick open menu?

theia front end sends whatever the user enters to the backend, and therefore you can use the frontend to test functional changes i made to the backend.

regarding the impact on the file search experience, we had a small group discussion in the office with Jacques, Marc, & Jean. here is what I personally think:

the user can still do whatever they used to do to search the files. The string match and fuzzy match are still performed. what this change offers the user is using globs, which helps the more advanced users to more precisely locate the files they need.

entering stars (*) into the vscode file search is equivalent to using spaces, e.g., `j*son` is treated as searching with `j` and `son`. while theia-this-patch handles this use case, theia-master-branch does not support it. From this perspective, this patch is an enhancement and brings theia a little closer to vscode.

the case that vscode support and theia-this-patch does not, is searching with spaces, e.g., searching with `j   son` in vscode returns json files, while in theia the user gets nothing.
@marechal-p

**Comment by elaihau** [comment]
related to https://github.com/theia-ide/theia/issues/4216

**Pull request merged**
