### PR TITLE
Disable format-on-save in VSCode

### PR DESCRIPTION
**Pull request by HighCommander4**
As discussed on Spectrum:

https://spectrum.chat/theia/dev/formatter-workflow~a168b15c-5258-416f-944b-53504d740ec6?m=MTU2NTkzNjczMTE3OQ==

Signed-off-by: Nathan Ridge <zeratul976@hotmail.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@vince-fugnitto I'm not sure that @svenefftinge meant. Format on save on is good to enforce our formatting.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I'm not sure that @svenefftinge meant. Format on save on is good to enforce our formatting. If some files are misformatted a PR should update this file, if some formatting settings bogus then a PR should fix such settings. But disable enforcing does not look good to me.

I see, I'll wait for a response from @svenefftinge. I understood it as well as it should be removed the config. Also, would it be worthwhile to provide `eslint` as a recommended extension so that when users open Theia from VSCode they will get the notification to install?

This is an example from their [docs](https://code.visualstudio.com/docs/editor/extension-gallery#_workspace-recommended-extensions):
```json
{
    "recommendations": [
        "ms-vscode.vscode-typescript-tslint-plugin",
        "dbaeumer.vscode-eslint",
        "msjsdiag.debugger-for-chrome"
    ]
}
```

**Comment by svenefftinge** [comment]
I personally do not use VS Code, but I meant to adjust/fix the formatting (i.e. whitespace)

**Comment by HighCommander4** [comment]
Closing in favour of #6137.

**Pull request closed without merging**
