### PR TITLE
Make Debug Session Views Act like Panels

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### Reference issue
https://github.com/theia-ide/theia/issues/2846

Makes every debug session widget behaves like independent panel. This allows to use several debuggers simultaneously. 

panels

### CODE REVIEW

**Comment by tolusha** [comment]
> I'm  confused why do we need so many panels.

Not a rare case when user needs to handle several debuggers simultaneously and different users get used to different layouts.

**Comment by akosyakov** [comment]
> Not a rare case when user needs to handle several debuggers simultaneously

It's true but it does not require a panel for each session. I've posted in https://github.com/theia-ide/theia/pull/2891#issuecomment-422269919 how other tools displays several sessions within the same panel. Why do we need to invent our own way?

> and different users get used to different layouts.

That one can relayout the debug panel horizontally and vertically looks cool.

**Comment by marcdumais-work** [comment]
Hi,

Could it be that we are talking about two slightly different things? Having multiple different debuggers (as in debugging different languages) being used simultaneously vs having multiple simultaneous sessions of the same debugger/language? 

For the former, it's right to say that typically all sessions would be shown in the same view, controlled by selection. 

For the later, it might not be possible. e.g. in the Eclipse C/C++ example screenshot above, if one launched a Java debug session, I think a new Debug View would be created for it, or?

**Comment by akosyakov** [comment]
@marcdumais-work I will need to try, I thought that the debug view in VS Code and Eclipse is not specific to debuggers/langauges, but show a tree of running configurations with the following hierarchy:
- launch configurations
- processes
- threads
- call stack

In the case of a single running configuration with a single thread, VS Code simplifies the view and just show a call stack.

**Comment by svenefftinge** [comment]
I think we should do it similar to existing mainstream debuggers (vscode, chrome devtools).
I.e. having one panel, where I can switch between all running debug configurations.

@marcdumais I am pretty sure you don't have multiple debug views in Eclipse.

**Comment by svenefftinge** [comment]
@tolusha Cool btw. to see you are doing the horizontal vs vertical layout. I love it :)

**Comment by svenefftinge** [comment]
> We at Red Hat see debugging multiple things in parallel as crucial in a microservices world.

👍 

Ok, let's try your approach. I think we have to use it to know, if it's helpful.

**Comment by svenefftinge** [comment]
I don't think it's a big issue, but usually, the breakpoints are part of the view (I think they should).
But they are not for a particular session/language. So that would be duplicated.

**Comment by akosyakov** [comment]
@tsmaeder thanks, it gets clear

> Also, there really is no disadvantage to it, except that it's not "standard".

It eats up the screen space and leaves a lot of space unused in the debug view.

> there is an competitive advantage to having a set of panels per debug target: you can debug them in parallel, keeping selection, etc. while stepping in a different in session, for example. 

It is solvable the single panel as well, i.e. like in Chrome keep threads and call stack separate, so one can debug each thread independent and preserve selection in the call stack for each thread.

**Pull request merged**
