### PR TITLE
[plug-in] check that the hosted instance URI is ready.

### PR DESCRIPTION
**Pull request by benoitf**
Helpful when routes are taking time to be available. It avoids to redirect user to a "N/A" page

Change-Id: Iac107c7226682f05f4518d7efa50a247b62d0fb8
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

### CODE REVIEW

**Comment by mmorhun** [comment]
My concern here that we ping hosted instance from backend but user will use it from frontend. They might be on different hosts and routes might be different as well.

**Comment by benoitf** [comment]
first, it's impossible to ping from frontend (due to CORS)
second, the route is the exposed one, not the internal URL. We only check that route is `ready/responding`

**Comment by mmorhun** [comment]
@benoitf yes, agree CORS is problem for that implementation...
As about exposed url it still might have different route...

**Comment by mmorhun** [comment]
Old issue for this PR: https://github.com/eclipse/che/issues/9894

**Comment by benoitf** [comment]
thanks @mmorhun I've searched on theia repository but wasn't able to find one !

**Pull request merged**
