### PR TITLE
Fix for VSCode plugin loading

### PR DESCRIPTION
**Pull request by paigeibm**
Some VSCode plugins send a string as the first parameter of their registerCommand() call, while Theia expects an object and uses the 'id' property of that object to register the plugin.  This will detect if a string is sent and convert it to an object if necessary so the plugin properly registers and executes.

Signed-off-by: Paige J. Sullivan <psullivan@ibm.com>

### CODE REVIEW

**Comment by benoitf** [comment]
hello, it's not already handled by https://github.com/theia-ide/theia/blob/master/packages/plugin-ext-vscode/src/node/plugin-vscode-init.ts#L39-L45 ?

**Comment by paigeibm** [comment]
Doesn't appear so.  I ran a lot of traces and that's where it seemed to go all wrong.

**Comment by benoitf** [comment]
@paigeibm ok it's strange because as registerCommand is overrided for VS Code extensions it should be handled there.

Do you have a VS Code extension sample to reproduce the issue ?

**Comment by paigeibm** [comment]
Zowe extension for VScode, any of the VS Code sample extensions/plugins


   Florent BENOIT --- [EXTERNAL] Re: [theia-ide/theia] Fix for VSCode plugin loading (#5198) --- 
    From:"Florent BENOIT" <notifications@github.com>To:"theia-ide/theia" <theia@noreply.github.com>Cc:"Paige J Sullivan" <psullivan@ibm.com>, "Mention" <mention@noreply.github.com>Date:Mon, May 20, 2019 10:26 AMSubject:[EXTERNAL] Re: [theia-ide/theia] Fix for VSCode plugin loading (#5198)
  
  @paigeibm ok it's strange because as registerCommand is overrided for VS Code extensions it should be handled there. 
 Do you have a VS Code extension sample to reproduce the issue ?

**Comment by benoitf** [comment]
@paigeibm 
Hello, I checked and having `@theia/plugin-ext-vscode` extension enabled

when running Zowe Extension it's going into the VS Code register command.
image

**Comment by paigeibm** [comment]
@benoitf True, it does call the vscode registerCommand method, but that in turn calls registerCommand in the command-registry.ts/.js file and passes it a string, rather than an object, at runtime.  Because of that, the command never actually gets registered because the second registerCommand expects an object with an .id property to add it to the Theia command registry.  So, the extension never fully loads and runs.  The GUI is loaded, but it's essentially non-functional.  If you were to compare the extension in VS Code and Theia (without my fix), you'll see that.

FWIW, I don't expect this to be the only fix to make VS Code extensions to be fully functional in Theia, as even with my fix, the extension still is not functioning as designed.  I'm currently investigating why.

**Comment by benoitf** [comment]
@paigeibm registerCommand is correctly handled on my side

zowe-debug

It's intercepted by the vscode init hooks and never goes to another registerCommand

**Comment by paigeibm** [comment]
I just pulled both theia and the vscode-extension-for-zowe from master branches and compiled.  I can't reproduce your results.  I stuck a console.log in theia\packages\plugin-ext\src\plugin\command-registry.ts just after registerCommand() is called and it hits it twice.  Is there another branch I should be pulling from?

**Comment by benoitf** [comment]
@paigeibm 

so you're:

- compiling vsix file and doing vsce package command to generate the vsix file,  copy the `vscode-extension-for-zowe-0.16.1.vsix` file to `<THEIA_CLONED_DIR>/plugins` and then you're doing `yarn run start` command in `<THEIA_CLONED_DIR>/examples/browser` ?

**Comment by paigeibm** [comment]
@benoitf To your last comment - yes.  That is one way I'm trying.  The other way is to just drop the entire source of the plugin into the plugins/ dir under Theia.  On my side, in either instance, it's hitting the registerCommand() method in command-registry.ts.  I still can't reproduce your results.  I am pulling from the latest master code.  I'm just as perplexed as you and offer my full resources to fix anything that's required to make it work.

**Comment by benoitf** [comment]
@paigeibm on which OS are you ? I've tested on macOS and linux.

Also, on your debug session, is that `plugin-vscode-init.ts` is invoked at some time ?

Is there a chance to try on a different OS (like Linux if you're on Windows) or using the theia full container ?

**Comment by paigeibm** [comment]
@benoitf I'm on Windows, but going to try in a Fedora VM.  I've also got a co-worker looking at it on a Mac.  

No, `plugin-vscode-init.ts` is ***never*** invoked at the current time.  If I see something different on the different platforms, I'll let you know.

**Comment by benoitf** [comment]
ok thanks @paigeibm and you're using the vsix file ? not a copy of the folder into plugins/ folder, correct ?

My guess is that it's deployed as a theia plugin and not a vscode extension

**Comment by paigeibm** [comment]
@benoitf I'm actually running it both ways - as a vsix file and dropping the built code into the plugins/ folder.  There seems to be no difference in how it executes.  When it loads, I can see in the logs that it detects it as a VSCode extension, but it doesn't seem to take the VSCode path during execution - treats it as a Theia extension.  I'll keep investigating - this has high priority for me.

**Comment by paigeibm** [comment]
Appears to be a Windows-only issue.  Still debugging.

**Comment by benoitf** [comment]
@paigeibm ok thanks for the feedback, please open a windows issue then as vsix should be still deployed correctly on Windows

**Comment by paigeibm** [comment]
@benoitf I tentatively have a fix, but need to clean up the source first.  Look for a PR in a few hours.

**Pull request closed without merging**
