### PR TITLE
get rid of ts-node in examples

### PR DESCRIPTION
**Pull request by akosyakov**
In order to remove ts-node and its dependency eventually.

### CODE REVIEW

**Comment by akosyakov** [comment]
It's ready for the review. Example tests are running fine on travis without ts-node.

After this PR + https://github.com/theia-ide/theia/pull/4135 + https://github.com/theia-ide/theia/pull/4138 are merge we can remove ts-node from our dependency graph.

**Comment by marcdumais-work** [comment]
Hi Anton, can you give us a few minutes to test something related to watch mode? Just to confirm. Otherwise PR looks good. We'll get back after.

**Comment by vince-fugnitto** [comment]
@akosyakov I've been having trouble watching for changes after this pr, I tried to watch for changes and it wasn't picking them up anymore.

steps:
1. in a terminal, run `yarn start`
2. in a second terminal, run `yarn watch` from the `examples/browser`
3. in a third terminal, run `yarn watch` on any package
4. make an change in a file under the same package

I used to use this development process at times to make changes and watch for them, but it no longer seems to work.

**Comment by marcdumais-work** [comment]
@vince-fugnitto I will try to reproduce

**Pull request merged**
