### PR TITLE
Add exists/createFile API to user storage

### PR DESCRIPTION
**Pull request by epatpol**
i.e if I want to open user_storage:settings.json but it does not exist
yet, this adds the possibility to create the file.

Signed-off-by: Patrick-Jeffrey Pollo Guilbert <patrick.pollo.guilbert@ericsson.com>

### CODE REVIEW

**Comment by epatpol** [comment]
I was testing the latest keybinding PR on top of this one, and I happened to notice that if you open user_storage:keymaps.json and it does not exist, it throws an error. I feel like we should maybe create a default keymaps.json when the File-> Open Keyboard Shortcuts is clicked and fill it with the instructions on how to rebind keys for instance. wdyt?

**Comment by epatpol** [comment]
Also when creating/reading user storage files, should we also pass the encoding as an option like the fs does? I omitted it as I don't know if all future implementations might need it...

**Comment by svenefftinge** [comment]
Please keep in mind that file-system is just on way of storing use information. We should think  of it as a map (key: string to content: string). We could say that the FileSystem automatically creates a file once there is information and deletes it if the content is empty.

**Comment by epatpol** [comment]
@svenefftinge So maybe not add those specific fs APIS but instead if `readContents` or `saveContents` fail because the file does not exist, it should instead create one? i.e without having to specifically tell the client to create/check it exists etc.

**Comment by epatpol** [comment]
Use case would be this https://github.com/epatpol/theia-1/blob/c18036b8e5863b3850b98dd0fca3d0754e8c4286/packages/keymaps/src/browser/keymaps-frontend-contribution.ts#L51

What should we do if the file does not exist etc.

**Comment by svenefftinge** [comment]
We could return an empty string and once the client saves something non-empty we create a file.

**Comment by epatpol** [comment]
Yea this is much simpler @svenefftinge, wdyt?

**Pull request merged**
