### PR TITLE
fix#2715 Fix preferences widget

### PR DESCRIPTION
**Pull request by vinokurig**
fix for #2715, Check values for `undefined` in case the value is `boolean`

### CODE REVIEW

**Comment by vinokurig** [comment]
@elaihau Could you please check this fix?

**Comment by vinokurig** [comment]
@elaihau Thank you for testing it. The idea wast to show stored preferences in the preferences files with the help of **bold** style, but since this commit: https://github.com/theia-ide/theia/commit/8aa64f4cffbd5ea2a716abe7c15db13378754e04 all preferences are stored in the Preference Service, so all of them are bold now. @akosyakov WDYT?

**Comment by akosyakov** [comment]
@vinokurig sorry, I did not pay attention that it was styled differently. `PreferenceService` has to provide default values even if something is not stored, it was a bug before.

Maybe you can style something with **bold**  if its value is not default or just remove this styling. For me the most important that the proper current value is displayed. 

// cc @svenefftinge

**Comment by vinokurig** [comment]
Removed The **bold** styling

**Comment by akosyakov** [comment]
@elaihau can you finish a review please

**Comment by elaihau** [comment]
I will merge this change on behalf of Igor, as it has stayed here almost a day after the approval.

**Pull request merged**
