### PR TITLE
Revert "[keybindings] Aligned keybindings with VSCode"

### PR DESCRIPTION
**Pull request by kittaakos**
Reverts theia-ide/theia#5326

#5326 is causing a regression on Windows. See https://github.com/theia-ide/theia/issues/5749.

### CODE REVIEW

**Comment by kittaakos** [comment]
CC @JPinkney

**Comment by akosyakov** [comment]
@kittaakos ECA is missing

@tsmaeder we have to revert it for now unfortunately, since it breaks keybindings. I hope you find someone later to look into these issues. We would be glad to review a new PR.

**Comment by kittaakos** [comment]
> @kittaakos ECA is missing

I cannot do much with it.

**Comment by akosyakov** [comment]
I see, you've already signed off a commit. Are you sure that your ECA is not expired? @marcdumais-work can we merge it like that?

**Comment by kittaakos** [comment]
> Are you sure that your ECA is not expired?

Yes, I am positive.

**Comment by marcdumais-work** [comment]
> My private email address is not exposed via GH. Hence, GH substitutes my address with something else. In general, whenever I create a PR via the web UI, it happens all the time.

Looks like the ECA checker is not smart enough to map this GH-generated email addr to your "real" one. I think you can fix this by fetching the branch on your computer, amending in the following way and force-pushing back here:

```git commit --amend --author="Akos Kitta <kittaakos@typefox.io>"```

**Pull request merged**
