### PR TITLE
add dependencies to fs-extra from dev-packages

### PR DESCRIPTION
**Pull request by amiramw**
as dev-packages do not depend on @theia/code.
otherwise fs-extra is missing when running browser app as a package in
monorepo.

Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

#### What it does
Fixes an error we get when starting browser app in monorepo:
```
user@46f46f2c37e9:/theia$ /usr/local/bin/node browser-app/src-gen/backend/main.js  --hostname=0.0.0.0 --startup-timeout 30000
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/theia/node_modules/@theia/application-package/lib/extension-package.js:63:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

#### How to test

Put the browser app as a package in monorepo together with other theia extension that depend on theia core. Use lerna 3.16.4.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov do we merge the PR for the release?
I don't believe @amiramw is a committer yet.

**Comment by akosyakov** [comment]
@vince-fugnitto as you want, it is not harmful, but the issue was there always

**Comment by amiramw** [comment]
actually it was introduced in 0.10: https://github.com/theia-ide/theia/pull/5834

**Comment by vince-fugnitto** [comment]
I'll merge it for the release, thank you @amiramw

**Pull request merged**
