### PR TITLE
Enable semantic highlighting support for the C++ language client

### PR DESCRIPTION
**Pull request by HighCommander4**
Signed-off-by: Nathan Ridge <zeratul976@hotmail.com>

The C++ language server, clangd, now has basic semantic highlighting support. This patch allows Theia to make use of it by enabling the semantic highlighting feature in the C++ language client.

cc @jvikstrom

### CODE REVIEW

**Comment by jvikstrom** [comment]
Hello,

Just thought I'd chime in a bit as I've been developing/testing this feature primarily using theia. These are the same changes I did to theia locally to enable semantic highlighting and it seems to work well. So the changes look good to me.

There is one issue though, but I think it is related to the underlying client implementation in Theia. I haven't looked into the Theia codebase to see what is causing it. But from what I can tell, clangd sends the correct source ranges for the test cases.

[This is the issue](https://github.com/theia-ide/theia/issues/5854) that I created for it.

(Thanks for tagging me by the way)

**Comment by hokein** [comment]
@HighCommander4 thanks for doing it.

just a note from clangd, this feature is still under development and may have bugs. In the coming-release clangd-9, it is considered experimental (clangd only emits highlightings for basic symbols).

The PR here will enable the semantic highlighting in clangd by default (not sure whether theia needs an `experimental` flag for it).

**Comment by simark** [comment]
Can you give an example of what constructs are currently highlighted by clangd?  Bonus points if they are thing not correctly handled by our textmate grammars.

**Comment by jvikstrom** [comment]
> Can you give an example of what constructs are currently highlighted by clangd? Bonus points if they are thing not correctly handled by our textmate grammars.

Currently clangd is highlighting these kinds of symbols:

- variables (all the different kinds (globals, parameters, etc..) as the same textmate type, except for members)
- functions
- methods 
- member variables
- class "names"
- enums
- enum constants
- namespaces
- template parameters

(things that are typedefed will also be highlighted as their underlying type)

So for example in this case:
```
// Somewhere in a header
namespace aaa {
  struct A {
    static int a;
  }
}
// The current source file
#include ...
void f() {
  aaa::A::a = 123;
}
```
Clangd will highlight `aaa` as a namespace, `A` as a class and `a` as a variable (as is, the default theia theme will give `aaa` and `A` the same color though).

I guess another thing that might be incorrectly handled by TM grammars are enums/scoped enums and things like that.

**Comment by HighCommander4** [comment]
Template parameters would be another case that clangd highlights but the TM grammar does not.

**Comment by HighCommander4** [comment]
@simark do you think we can proceed with this?

**Comment by marechal-p** [comment]
@HighCommander4 I would like to try your patch, can you tell me what to look for exactly?

I am afraid I would not see what is being highlighted by clangd and what is from the TM grammars :)

**Comment by HighCommander4** [comment]
(Updated to resolve conflicts)

**Comment by HighCommander4** [comment]
> Tried to compare with master, this is much better indeed!

It wil get even better after I upstream some clangd patches, and figure out how to make corresponding customizations in Theia :)

**Comment by simark** [comment]
> @simark do you think we can proceed with this?

I haven't had the time to try it, but looking at Paul's screenshot, it seems very nice.  No objection from me to merge this.

**Comment by MarkZ3** [comment]
It looks nice! Thanks a lot for working on this.

**Comment by HighCommander4** [comment]
The credit goes to @kittaakos for the LSP proposal and Theia client implementation, and @jvikstrom for the C++ server implementation. I'm just enabling it, and polishing things here and there :)

**Pull request merged**
