### PR TITLE
Electron 3 node 10

### PR DESCRIPTION
**Pull request by debovema**
Rebased and updated Node version to 10 in Appveyor & Travis CI config files.

### CODE REVIEW

**Comment by benoitf** [comment]
hello @debovema you should rebase your PR, it includes commits from master there

**Comment by debovema** [comment]
Thanks @benoitf. I did a proper rebase from master since @thegecko did rebase from master but new commits came along.
If I am not mistaken conflicting files between ```debovema:electron-3-node-10``` and ```theia-ide:electron-3``` will resolve conflicts between ```theia-ide:electron-3``` and ```theia-ide:master```.

**Comment by benoitf** [comment]
you still have commits that should not be displayed
```
$ git fetch
$ git pull --rebase origin master
```

**Comment by benoitf** [comment]
@debovema hmm ok didn't see you were providing a PR for a custom branch

**Comment by debovema** [comment]
Nevermind I see that @thegecko has updated the Node version in #4750.
Rebase from master can be performed on this branch directly as master is moving fast right now.

**Pull request closed without merging**
