### PR TITLE
Wait until plugin metadata processed

### PR DESCRIPTION
**Pull request by evidolob**
This pull try to fix https://github.com/eclipse/che-theia/issues/101, that bug may be caused because we start server before `PluginDeployer` able to read and process plugins metadata, and if client connects in that time, he (client) will receive empty list of plugins. So this pull force Theia server to wait until all plugins are processed.

Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@evidolob btw there is already PR for decorators https://github.com/theia-ide/theia/pull/4827 could you have a look at it?

**Comment by akosyakov** [comment]
> Try to fix eclipse/che-theia#101, that bug may be caused because we start server before PluginDeployer able to read and process plugins metadata, and if client connects in that time, he (client) will receive empty list of plugins. So this pull force Theia server to wait until all plugins are processed.

Do you know how to reproduce it with some timeouts in the code?

**Comment by evidolob** [comment]
I think yes, give me an our to create branch with timeouts

**Comment by akosyakov** [comment]
@evidolob i would try to reproduce as well had something like that npm, grunt and gulp extensions installed together

**Comment by evidolob** [comment]
@akosyakov I add `sleep` on `doStart` method, in this branch https://github.com/theia-ide/theia/tree/plugin-init-test

**Comment by akosyakov** [comment]
@evidolob trying, could you have a look at https://github.com/theia-ide/theia/pull/4824?

**Comment by akosyakov** [comment]
@evidolob If i set up 30 sec I can reproduce an issue, but the PR does no fix it.

`onStart` is called after the server is already started

**Comment by akosyakov** [comment]
@evidolob I think we need a new lifecycle callback for the backend app, something like `onWillStart`.

**Comment by evidolob** [comment]
@akosyakov Yes, this fix is not resolving the issue, I'm going to close it, and create new one.
I think I will do more async code, so browser request for plugins metadata will check that all plugins are  processed or will wait until plugin metadata will be present

**Comment by akosyakov** [comment]
@evidolob ok

**Pull request closed without merging**
