### PR TITLE
[plugin/tree] don't pass tree item data over json-rpc

### LINKED ISSUE #4975: TreeView fails if TreeItem object contains circular references
### Description
 
Theia's TreeView API fails to display an extension's tree if an object to be converted to a TreeItem contains circular references. 
Running [my VS Code extension](https://github.com/microclimate-dev2ops/microclimate-vscode-tools) in Theia fails to show the TreeView in all but the simplest case. In the Theia logs, I see this message interspersed with the output from my tree-building code:
```
root ERROR [hosted-plugin: 40579] [ERRO: 13:12:22.031 extension.js.on():32]: Unhandled promise rejection: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Function.MessageFactory.replyOK (/Users/tim/programs/clones/theia/packages/plugin-ext/lib/api/rpc-protocol.js:274:103)
    at /Users/tim/programs/clones/theia/packages/plugin-ext/lib/api/rpc-protocol.js:152:51
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
The error is generated by that file trying to `JSON.stringify` my complex tree objects, which do contain circular references.

### Reproduction Steps

You need [Microclimate installed](https://microclimate-dev2ops.github.io/mdt-vsc-getting-started#doc) to use the extension, so hopefully the description above is enough.
1. Clone https://github.com/microclimate-dev2ops/microclimate-vscode-tools
2. Checkout the `theia` branch
3. Run `cd dev && vsce package` to build the vsix.
4. Copy the vsix into `$theia_clone/plugins`
5. Run the browser example. You will see that error message in the console output when the TreeView is rendered.

**OS and Theia version:**
macOS
Latest theia (built from master)

To fix this, we should use [`flatted.stringify`](https://www.npmjs.com/package/flatted) instead, which will flatten circular references. I have this working, and I'm putting together a PR with the fix. 
However, this means all JSON-to-string conversions on both the client and server ends will have to be done with `flatted` (you can't JSON.parse something that was stringified with `flatted`, or vice-versa), so this might not be so straightforward.

### LINKED ISSUE #4978: Commands invoked from TreeView context menu do not pass the object to the command handler
### Description
 
In VS Code, if a command is run from right-clicking an item in a TreeView, the object that provided that TreeItem is passed to the command handler. [vs code doc](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)
[My extension](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/) uses this feature in almost every command, such as [this command](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/blob/theia/dev/src/command/OpenInBrowserCmd.ts#L25).
The handlers are registered [in this file](https://github.com/microclimate-dev2ops/microclimate-vscode-tools/blob/theia/dev/src/command/CommandUtil.ts#L42).
From the `OpenInBrowserCmd` (first link), you see that I expect the resource passed to be `Project | Connection`, as these are the two types of objects that are displayed in my TreeView. This works great in VS Code.

But in Theia, the resource passed is instead a string roughly outlining the item's position and indices in the tree. This will cause extensions' commands like mine to fail to work in Theia because they rely on that context. 

I plan to refactor my extension to use the TreeView selection events to infer the currently selected project/connection. But I expect mine is not the only extension to use this behaviour from VS Code, so Theia should implement this feature to allow more extensions to work with minimal friction.

### Reproduction Steps

You need [Microclimate installed](https://microclimate-dev2ops.github.io/mdt-vsc-getting-started#doc) to use the extension, so hopefully the description above is enough.
1. Clone https://github.com/microclimate-dev2ops/microclimate-vscode-tools
2. `cd microclimate-vscode-tools/dev && vsce package`
3. Copy the vsix into $theia_clone/plugins
4. Run the browser example
5. Open the Microclimate tree and right-click run Open in Browser
6. Observe that the command doesn't work, and the output prints the unexpected object.

**OS and Theia version:**
macOS 
Latest theia (built from master)

### PR DESCRIPTION
**Pull request by akosyakov**
- fix #4975 fix #4978
- closes #5121 (superseded)
- closes #5196 (superseded)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tetchel could you please try whether #4975 is resolved

**Comment by akosyakov** [comment]
@vinokurig Could you verify as well when you have a chance?

**Comment by akosyakov** [comment]
@marcdumais-work if it will be approved please merge before a release, i won't be around today

**Comment by tetchel** [comment]
It works great - Thanks so much for the fix, guys!

**Comment by marcdumais-work** [comment]
Unfortunately this PR was not approved in time to be merged for `0.7.0`. How important is it in general? Enough to warrant a `0.7.1` bugfix release?

**Comment by akosyakov** [comment]
@marcdumais-work it is fine, can be landed in 0.8.0

**Pull request merged**
