### PR TITLE
test: [filesystem] Update nsfw to support Node 10.15.1

### PR DESCRIPTION
**Pull request by marechal-p**
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by marechal-p** [comment]
I forgot to update the CI to use Node 10 too, but on my workstation it worked without any issue.

**Comment by marechal-p** [comment]
Update CI configs to run Node 10.

**Comment by kittaakos** [comment]
I thought we do the Node.js 10.x support with electron 3.x.

**Comment by marechal-p** [comment]
@kittaakos I don't know, just wanted to try and see what was failing, turns out it was pretty minimal.

But it seems to make sense to do the Electron upgrade at the same time, this way both target will be in sync. If anything this change can be base for the actual migration from 8 to 10, unless this was already figured out, really no idea.

In the mean time I am curious to see how the CI behaves on this patch.

**Comment by marechal-p** [comment]
Turns out Travis failed...

**Comment by marechal-p** [comment]
Ok turns out that @thegecko had everything setup this way too, just a matter of rebasing his branch now maybe, and should be good to go :)

https://github.com/theia-ide/theia/commit/e29673b24b7abd2b0856bbd0bffb53fe21b8b9b9

**Comment by marechal-p** [comment]
CI was building correctly.

**Comment by thegecko** [comment]
👍 Keep an eye on https://github.com/theia-ide/theia/issues/3729

**Pull request closed without merging**
