### PR TITLE
Open file dialog

### PR DESCRIPTION
**Pull request by akosyakov**
It is not ready yet, please don't merge.

### CODE REVIEW

**Comment by akosyakov** [comment]
Please review.

At the current moment, there is `Open...` file menu entry which opens the file dialog to navigate the file system and select the file.

This PR as well:
- add `onInitialize` callback to the application contribution providing a single point to contribute commands, keybindings and menus, see as an example: https://github.com/theia-ide/theia/pull/166/files#diff-b5d7dec9a06bcdca0c69528ea13c921aR22
- fix various URI, FileSystem, dialogs and file command bugs

Since this PR gets quite big already, I would like it to be reviewed and merged. I will add more UI features to the file dialog, as search, improve styling and change the server side with separate PRs.

**Comment by akosyakov** [comment]
It is done and contains a lot of fixes and changes to different parts, like the file-system extension, the application extension, URI, JSON-RPC, the logger extension, ldm.

Please review.

**Comment by akosyakov** [comment]
@hexa00 I've removed additional scripts for debugging and taught ldm to install original sources for local dependencies. theia-core has proper source maps for publishing and examples have source maps pointing to the original sources. Debugging of frontend should be possible from Chrome as well as from VS code.

**Comment by hexa00** [comment]
@akosyakov Sounds very cool! thanks, however I don't see how it will be different from chrome debugging since the sourcemaps are the equivalent of what we had with sourceMaps: src no ?

I'll try this out tomorrow and do what I can to review this monster patchset :)

**Comment by akosyakov** [comment]
yes, they are equivalent, but relative not absolute compare with `sourceMaps: src`, because of it the webpack loader able to find them and install for debugging in Chrome

**Comment by hexa00** [comment]
Strange thing trying this out today I try File-> Open..  And I get the /boot directory open like this:

file-open-screenshot

What's the rule for the directory to display ?  I expected the workspace root or the cwd

**Comment by hexa00** [comment]
Doing File->Open.. in the electron example I get these errors in the console
```
GET file:///home/eantotr/ownCloud/work/theia/examples/electron/lib/frontend/af7ae505a9eed503f8b8e6982036873e.woff2 net::ERR_FILE_NOT_FOUND
scrollIntoViewIfNeeded @ element.js:102
TreeWidget.onUpdateRequest @ tree-widget.ts:85
Widget.processMessage @ widget.js:477
invokeHandler @ index.js:398
sendMessage @ index.js:169
runMessageLoop @ index.js:448
fee66e712a8a08eef5805a46892932ad.woff:1 GET file:///home/eantotr/ownCloud/work/theia/examples/electron/lib/frontend/fee66e712a8a08eef5805a46892932ad.woff net::ERR_FILE_NOT_FOUND
b06871f281fee6b241d60582ae9369b9.ttf:1 GET file:///home/eantotr/ownCloud/work/theia/examples/electron/lib/frontend/b06871f281fee6b241d60582ae9369b9.ttf net::ERR_FILE_NOT_FOUND
```

It's ok in the browser example.

**Comment by hexa00** [comment]
I can confirm that debugging now works in Chrome and in vscode!! and there's no more ugly warnings! Thanks!

BTW could you update the doc in Developping.md so that this is reflected ?

Also I've tried to debug the backend & frontend at the same time in vscode but that is still broken... (most likely a vscode issue)

**Comment by akosyakov** [comment]
@hexa00 I am trying to open the first drive, but I think for now opening the current workspace root will be good. Drives can be handled separately.

I will try to reproduce the electron issue.

Thank you for trying out!

**Comment by akosyakov** [comment]
@hexa00 I've switched to use `cwd` for now as the fs-root for now as the easiest solution.

**Comment by hexa00** [comment]
@akosyakov great thanks for that and the updated doc.

I've read through the series and it LGTM for what it's worth.

I liked the improvements to the logger with JsonRpcConnectionHandler, I'll refactor my doc after this series is in.

Only detail is UI wise it seems to me that in the dialog the "Open" header takes too much vertical space...
There's enough empty space there to cut the height from the top of the dialog the the folder selection bar in half I think...

**Comment by akosyakov** [comment]
@hexa00 thx for looking at it again!

I've filled a bug about the dialogs styling: https://github.com/theia-ide/theia/issues/228

**Pull request merged**
