### PR TITLE
[theia-core] Add missing fs-extra dependency

### PR DESCRIPTION
**Pull request by shahar-h**
Signed-off-by: Shahar Harari <shahar.harari@sap.com>

fs-extra is used in several places inside theia-core, but is missing in package.json:
https://github.com/theia-ide/theia/blob/98bf44fbc831b2c64714315ebc1fbe5e6fdeb0a4/packages/core/src/node/backend-application.ts#L21
https://github.com/theia-ide/theia/blob/98bf44fbc831b2c64714315ebc1fbe5e6fdeb0a4/packages/core/src/node/logger-cli-contribution.ts#L21

Currently it is working because fs-extra is hoisted to root node_modules.

### CODE REVIEW

**Comment by akosyakov** [comment]
> fs-extra is used in several places inside theia-core, but is missing in package.json.

please provide list of places

**Comment by vince-fugnitto** [comment]
@shahar-h thank you for your contribution 👍Please be sure to [sign-off](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#sign-your-work) and sign the [Eclipse ECA](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#sign-your-work) (it's the reason for the failed pull request checks)

**Comment by vince-fugnitto** [comment]
`fs-extra` is used in the following extensions:
- `application-manager`
- `application-package`
- `extension-manager`
- `filesystem`
- `git`
- `mini-browser`
- `preferences`
- `workspace`

I believe we can declare it in `core` and also add it to the whitelist of `no-implicit-dependencies`.

**Comment by akosyakov** [comment]
@vince-fugnitto not sure why we did not catch it with `no-implicit-dependencies` rule

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto not sure why we did not catch it with `no-implicit-dependencies` rule

We did not catch it since it was added to the whitelist for the rule but it looks like it was forgotten in the actual `package.json` of `core`:
https://github.com/theia-ide/theia/blob/98bf44fbc831b2c64714315ebc1fbe5e6fdeb0a4/configs/errors.tslint.json#L58-L60

**Comment by akosyakov** [comment]
I think whitelisting `fs-extra` is fine, if we added it to core. We use it often instead of `fs`, since it provides more convenient APIs. But then we should remove `fs-extra` declarations from other packages.json except core. It could be done with another PR. @vince-fugnitto could you do it?

**Comment by vince-fugnitto** [comment]
> I think whitelisting `fs-extra` is fine, if we added it to core. We use it often instead of `fs`, since it provides more convenient APIs. But then we should remove `fs-extra` declarations from other packages.json except core. It could be done with another PR. @vince-fugnitto could you do it?

Sure, I'll handle it.

**Pull request merged**
