### PR TITLE
THEIA-2091: Update vscode-ripgrep lib to use cached ripgrep search lib.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Update vscode-ripgrep lib to use cached ripgrep search lib.

Related issue: https://github.com/theia-ide/theia/issues/2091

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Please change here too: https://github.com/theia-ide/theia/blob/2d2f1100238203d2a203521d7ea10e9531dae6ae/packages/search-in-workspace/package.json#L8

**Comment by kittaakos** [comment]
Otherwise, it looks good. @AndrienkoAleksandr, please ping me here once more after the update and I approve this PR. Thanks!

**Comment by AndrienkoAleksandr** [comment]
@kittaakos, thanks. Done.

**Comment by akosyakov** [comment]
@AndrienkoAleksandr just fyi: please use GH references in comments - https://help.github.com/articles/autolinked-references-and-urls/#issues-and-pull-requests

**Comment by AndrienkoAleksandr** [comment]
@akosyakov Do You mean use GH-2091 instead of THEIA-2091 in the commit message?

**Pull request merged**
