### PR TITLE
Auto Dependency Updates ...

### PR DESCRIPTION
**Pull request by lguzzon**

### CODE REVIEW

**Comment by kittaakos** [comment]
@lguzzon, you need to sign your commit as described in the [contributing](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#sign-your-work) guide.

**Comment by akosyakov** [comment]
it is not enough, generator-theia should be adapted and theia.package.json files.

**Comment by akosyakov** [comment]
all commits should be signed of, please use `git rebase -i` to squash to one signed off commit

**Comment by akosyakov** [comment]
Thank you, but not it is too far away from the master state.

**Pull request closed without merging**
