### PR TITLE
GH-484: Quick fix (Code action) does not seem to work

### PR DESCRIPTION
**Pull request by MarkZ3**
Add handler for Clangd "fixits" command.
There is also a bug in Clangd for this to work, see
https://bugs.llvm.org/show_bug.cgi?id=34559

Signed-off-by: Marc-Andre Laperle <marc-andre.laperle@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
I wonder whether you can do it completely in clangd:
- register the server-side command by providing `ServerCapabilities.executeCommandProvider`
- implement the command via [workspace/executeCommand request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#execute-a-command)
- trigger [workspace/applyEdit request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#applies-a-workspaceedit) from the command implementation

**Comment by MarkZ3** [comment]
> implement the command via workspace/executeCommand request
So server-side, in the workspace/executeCommand handler, it would check for "clangd.applyfixit" command string, if so then send workspace/applyEdit back to the client?

Just to summarize what I understood:
Theia ---- textDocument/codeAction ---> Clangd
Theia <--- Commands --- Clangd
** User triggers the quick fix **
Theia ---  workspace/executeCommand (clangd.applyFix) ---> Clangd
Theia <--- workspace/applyEdit --- Clangd

**Comment by akosyakov** [comment]
@MarkZ3 also at the handshake:
Theia --> `initialize` --> Clangd
Theia <-- ServerCapabilities.executeCommandProvider <-- Clangd

**Comment by MarkZ3** [comment]
Haven't tried yet but am a bit concerned about breaking existing clients. I will inquire with other Clangd contributors.

**Comment by svenefftinge** [comment]
The good thing about this, is that you don't need to configure any commands on the clients anymore.

**Comment by svenefftinge** [comment]
@MarkZ3 what is the state with this and the related issue?

**Comment by MarkZ3** [comment]
I haven't looked into it yet on the Clangd side. I probably won't have time to look at it for another week.

**Comment by MarkZ3** [comment]
I don't see the  workspace/executeCommand (command=="clangd.applyFix") being sent from Theia to Clangd when the user selects the code action. Is this supposed to be forwarded to the Server automatically when no command is registered with that string on the client? I set executeCommandProvider: ["clangd.applyFix"] in ServerCapabilities.
I also tried with VS Code with no luck. I'll try to debug further tomorrow.

**Comment by MarkZ3** [comment]
Gahh, I forgot the "commands" part, it should have been
"executeCommandProvider": {"commands": ["clangd.applyFix"]}
Now it's working. Sorry for the noise.

**Comment by MarkZ3** [comment]
Clangd was changed to handle the command server-side, see https://reviews.llvm.org/D39276
Thanks for the suggestions!

**Pull request closed without merging**
