### PR TITLE
[workspace] Allow easier overriding of DefaultWorkspaceServer

### PR DESCRIPTION
**Pull request by thegecko**
Signed-off-by: Rob Moran <rob.moran@arm.com>

This is a simple PR which slightly reworks the base `Workspace Server` to make it easier to override.

Specific changes:

- Some useful methods have been marked as `protected` so they can be used in sub-classes
- Functionality in the `init` method has been separated into a new protected method to allow easier overriding, e.g.:

```typescript
/* Overridden class */
protected async getRoot(): Promise<string | undefined> {
    let root = super.getRoot();
    if (!root) {
        // Do something else
    }
    return root;
}
```

### CODE REVIEW

**Comment by marechal-p** [comment]
I'm not against it, but usually things marked as `private` are things that can be deleted/renamed without worrying too much about breaking clients.

Now, marking them as protected kind of make them some kind of API, one that at least you are going to use. LGTM otherwise.

**Comment by thegecko** [comment]
> marking them as protected kind of make them some kind of API

I understand. It's a delicate balance between usability and supporting a new interface.

`init()` uses the private `readRecentWorkspacePathsFromUserHome()` which in turn uses the private `readJsonFromFile()`, etc.

So in order to override the class to decide which workspace to load, there's a need to duplicate a lot of the private functions.

Happy to reduce the protected methods back to just `readRecentWorkspacePathsFromUserHome()` and `readJsonFromFile()` or accept other suggestions.

**Comment by marechal-p** [comment]
Oops, build error: https://travis-ci.org/theia-ide/theia/jobs/493338180#L901

**Comment by marechal-p** [comment]
Commit should be signed-off too :)

**Pull request merged**
