### PR TITLE
[terminal] Allow configuration of used terminal through Theia specific envs. (fixes #849)

### LINKED ISSUE #849: Support Theia-specific envs for terminal process
When running Theia in e.g. a Kubernetes context, the terminal maybe should connect to a shell in another container than the IDE one. 
We should allow configuring that through env variables.

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

**Comment by akosyakov** [comment]
copyrights are missing

**Comment by hexa00** [comment]
Is this meant so that we use a ssh command ?

Did you test string-argv with such a command ?

**Comment by hexa00** [comment]
If you could provide an example it would be nice to test...

**Comment by svenefftinge** [comment]
> Is this meant so that we use a ssh command ?

Yes, that is my use case. But #664 can be done, too.

> Did you test string-argv with such a command ?

Yes, I tested it with a complex arg list including whitespaces in strings and such. The library itself has unit tests.

> If you could provide an example it would be nice to test...

For instance:
```
export THEIA_SHELL="ssh"
export THEIA_SHELL_ARGS="localhost"
```

**Comment by svenefftinge** [comment]
The appveyor fail is unrelated #860

**Pull request merged**
