### PR TITLE
[cpp-debug] Add C/C++ Debug Support

### PR DESCRIPTION
**Pull request by marechal-p**
This extension relies on `code-debug`, which expect you to have GDB installed on your system.

https://github.com/WebFreak001/code-debug
https://www.gnu.org/software/gdb/

Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@MarkZ3 We forgot to bring this new PR to your attention, sorry

**Comment by svenefftinge** [comment]
We could add this extension already here https://github.com/eclipse/theia-cpp-extension

**Comment by marechal-p** [comment]
Ok, made a separate extension here: https://github.com/marechal-p/theia-cpp-extension

But because https://github.com/eclipse/theia-cpp-extension is not initialised, I couldn't fork it, and it turned out that we also cannot make any pull request.

What's the procedure in this case? :)

**Comment by svenefftinge** [comment]
I added an empty README.md so a PR should work now.

**Comment by marechal-p** [comment]
Thanks!

**Comment by marechal-p** [comment]
https://github.com/eclipse/theia-cpp-extension/pull/1

**Pull request closed without merging**
