### PR TITLE
[electron] Add a menu to open Chrome DevTools

### LINKED ISSUE #3739: [electron] There is no way to open the Dev Tools if the electron application is in a broken state
I am not sure if this is related or not, but with [this](https://github.com/theia-ide/theia/commit/316c760b68231257da77b55ba217f43b14c9bc51#diff-e6697ec7c0f7ddbbfd9e8365baacf132R153) change, we set the application menu only when the [electron menu contribution has loaded](https://github.com/theia-ide/theia/blob/14078b4e3c1e783ea938c641fb5694ca6c60ec11/packages/core/src/electron-browser/menu/electron-menu-contribution.ts#L83).

The problem with this approach, there is no way to open the `Dev Tools` and access the console for the error stack trace.

See the attached image:

bildschirmfoto 2018-12-05 um 13 54 34

@marechal-p, do you have any idea how can we tackle this problem. I like the changes you had made regarding the application menu, but clearly, we need a way to access the console.

### PR DESCRIPTION
**Pull request by marechal-p**
Signed-off-by: Paul Maréchal <paul.marechal@ericsson.com>

Fix #3739

### CODE REVIEW

**Comment by kittaakos** [comment]
I am doing the review...

**Comment by kittaakos** [comment]
It works great! Can we use the `Help` > `Toggle Developer Tools` menu item for this?

When the app has crashed during the startup:
screen shot 2018-12-06 at 08 15 05


When the app has started without an issue:
screen shot 2018-12-06 at 08 14 45

**Comment by marechal-p** [comment]
@kittaakos I added back the default button for toggling the devtools, under `Help`

**Comment by marechal-p** [comment]
@kittaakos ping :)

**Pull request merged**
