### PR TITLE
Misc fixes related to @theia/java

### PR DESCRIPTION
**Pull request by AlexTugarev**
This PR resolves following issues

1. JDT LS tries to register `java.edit.organizeImports` command, which is already done in [java-commands.ts](https://github.com/theia-ide/theia/blob/574236ee83e8bb1a6c31011ac7fc73876cc81a0c/packages/java/src/browser/java-commands.ts#L60)
1. on reload with opened java editor, many rejected promise errors from `monaco-outline-contribution.ts` were logged.
* it happened due to frequent calls of [updateOutline](https://github.com/theia-ide/theia/blob/947a7e79ddbdbf69d87d0e24f7acfaa290d223db/packages/monaco/src/browser/monaco-outline-contribution.ts#L69)
* call of [`provideDocumentSymbols`](https://github.com/theia-ide/theia/blob/947a7e79ddbdbf69d87d0e24f7acfaa290d223db/packages/monaco/src/browser/monaco-outline-contribution.ts#L105-L116) throws with rejected promise errors on cancellation

### CODE REVIEW

**Comment by AlexTugarev** [comment]
@gorkem, WDYT about 1.)?  Should we remove the command registration from [`java-commands.ts`](https://github.com/theia-ide/theia/blob/574236ee83e8bb1a6c31011ac7fc73876cc81a0c/packages/java/src/browser/java-commands.ts#L60)?

**Comment by gorkem** [comment]
We can not really remove the command because we are registering menu and keybinding to that command. That command is also registered by the server via registerCapability which fires a similar error. I thin the solution is in the lines of to adopting a more tolerant policy for consequent command registrations.

**Comment by AlexTugarev** [comment]
Thanks @gorkem, I've updated the PR to log only warnings if commands are registered multiple times.

**Comment by AlexTugarev** [comment]
@akosyakov could you have a look at the commands whenever possible?

also, if you see more to consider with that change to commands, I'll splitt that PR. the changes to outline are actually a different story.

**Pull request merged**
