### PR TITLE
Support source breakpoints

### PR DESCRIPTION
**Pull request by tolusha**
### Reference issue
https://github.com/eclipse/che/issues/10077

breakpoints

### CODE REVIEW

**Comment by tolusha** [comment]
@akosyakov 
Here is a new PR

**Comment by akosyakov** [comment]
> For me breakpoints are irrelevant to markers.

A marker is a data associated with some position in a file. It can be displayed in the editor and has a widget to show and manage them. A breakpoint seems to be exactly that.

I am asking because of 2 reasons:
- a user should have similar UX across the app, reusing existing widgets with build-in UX would be good, for example there is the marker widget which can be extended and has built in keyboard navigation, multi selection support and so on.
- the similar problem should be solved only once otherwise it introduces unnecessary deviataion and repetive bugs. There is already the marker manager which can be extended to support specific markers.

It could be that you don't need to use markers indeed, but if it is not true in the long run the debug support won't benefit from improvements in markers and the same basic funcntionality will need to reimplemented for it.

**Comment by tolusha** [comment]
I see your point. I will redo breakpoints using markers.

**Comment by akosyakov** [comment]
@tolusha Should not it be a part of a marker data and a URI should always point to a file? 
```ts
export interface BreakpointMarker extends Marker<ExtDebugProtocol.AggregatedBreakpoint> {
   kind: 'breakpoint'
}

export class BreakpointManager extends MarkerManager<ExtDebugProtocol.AggregatedBreakpoint>> {
    ...
}
```

**Comment by tolusha** [comment]
```
 /**
     * The aggregated breakpoint.
     */
    export interface AggregatedBreakpoint {
        /**

...
 origin: DebugProtocol.SourceBreakpoint | DebugProtocol.FunctionBreakpoint | ExtDebugProtocol.ExceptionBreakpoint;
}
```

Either source breakpoints which points to the file or another type without relation to file.

**Comment by akosyakov** [comment]
I see, yes, it sounds good.

**Pull request merged**
