### PR TITLE
Fix 'Open Recent Workspace' command and menu item

### LINKED ISSUE #3421: 'Open Recent Workspace' menu item no longer displays
As of 9b08af17c5dde9464e17af68ee6b71bcf8552c44, the menu item for `Open Recent Workspace` no longer displays.

### LINKED ISSUE #3428: [windows][electron] Unknown command with ID: workspace.openRecent
```
root ERROR Could not start contribution Error: Unknown command with ID: workspace:openRecent.
```

Windows 10 running Electron example application. This makes the native menu creation fail.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #3421
Fixes #3428

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@akosyakov are you fine with this solution?

**Comment by kittaakos** [comment]
I will try the changes locally, and if it works, I'll merge the PR...

**Comment by kittaakos** [comment]
@vince-fugnitto, please clean up the branch if you do not need it. I did not want to delete it after the merge.

**Comment by vince-fugnitto** [comment]
thanks @kittaakos !

**Pull request merged**
