### PR TITLE
[plug-in][languages] Add ability to provide language and syntax highlight by plugin

### PR DESCRIPTION
**Pull request by evidolob**
This pull request also provide a way for plugin to get all registered languages, and provide some configuration to the editor.
[Demo](https://www.youtube.com/watch?v=7xQ7nxDCDVo)

Issue: #2348
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### CODE REVIEW

**Comment by evidolob** [comment]
@benoitf Does Thea has documented rules on which single quote or double quotes should be used for import?

**Comment by evidolob** [comment]
I know [Coding-Guidelines](https://github.com/theia-ide/theia/wiki/Coding-Guidelines), maybe we should add strict rules for import strings?

**Comment by benoitf** [comment]
@evidolob maybe https://github.com/theia-ide/theia/wiki/Coding-Guidelines#strings (so here strings should use single quotes but it's not so clear)

**Comment by evidolob** [comment]
@benoitf OK, thx

**Pull request merged**
