### PR TITLE
GH-1311: Implemented the navigator filter.

### LINKED ISSUE #1311: [Navigator] Add Filters
A preference shall allow providing glob patterns for filtering elements in the navigator tree.
By default `.git` shall be filtered.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #1311

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by svenefftinge** [comment]
Looks good, but could we make the preference similar to VS Code? 
It would be:
```
  "navigator.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true
  },
```
I think it is more flexible to disable individual patterns and will also make it easier to read and translate settings from vscode.

**Comment by kittaakos** [comment]
> make the preference similar to VS Code

You mean just the preference values? So instead of having an array of exclude patterns, you would like to see a pair of exclude patterns plus the boolean value whether it is enabled or not? Is that you meant?

**Comment by svenefftinge** [comment]
Yes, plus the preference name.

**Comment by kittaakos** [comment]
OK, that should be a minor adjustment.

**Comment by kittaakos** [comment]
I have made the required changes; from now on we have the same navigator exclusion format as VSCode does.

**Pull request merged**
