### PR TITLE
GH-934: Aligned the version of the third-party dependencies

### PR DESCRIPTION
**Pull request by kittaakos**
It is a must for the bundled electron application.
Otherwise, these two dependencies won't be hoisted into
the root `node_modules` folder.
Instead, they will stay in `node_modules/@theia/core/node_modules`,
and will not make into the bundled electron application.

Closes: #934.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@marechal-p do you have time to review/test this? It would be nice if we could merge in time for today's release.

**Comment by kittaakos** [comment]
> LGTM, could not reproduce issue #934

Did you bundle a Theia electron application?

**Comment by marechal-p** [comment]
Does that means from npm solely and not the sources? From your question I assume that I should have done it from npm, let me retry...

**Comment by marechal-p** [comment]
```
root ERROR [nsfw-watcher: 24733] /meh/projects/electron-bundle/node_modules/electron/dist/electron: symbol lookup error: /meh/projects/electron-bundle/node_modules/vscode-nsfw/build/Release/nsfw.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE
root ERROR Request watchFileChanges failed with error: Connection is closed. Error: Connection is closed.
    at new ConnectionError (/meh/projects/electron-bundle/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/meh/projects/electron-bundle/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendRequest (/meh/projects/electron-bundle/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at /meh/projects/electron-bundle/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:309:72
    at Promise (<anonymous>)
    at /meh/projects/electron-bundle/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:302:24
    at <anonymous>
```

Not sure if I didn't rather mess up the bundling?

Used this `package.json` from `theia-apps`:

```json
{
    "private": true,
    "theia": {
        "target": "electron"
    },
    "dependencies": {
        "typescript": "latest",
        "@theia/tslint": "next",
        "@theia/typescript": "next",
        "@theia/navigator": "next",
        "@theia/terminal": "next",
        "@theia/outline-view": "next",
        "@theia/preferences": "next",
        "@theia/messages": "next",
        "@theia/git": "next",
        "@theia/file-search": "next",
        "@theia/markers": "next",
        "@theia/preview": "next",
        "@theia/callhierarchy": "next",
        "@theia/merge-conflicts": "next",
        "@theia/search-in-workspace": "next",
        "@theia/json": "next",
        "@theia/textmate-grammars": "next",
        "@theia/mini-browser": "next"
    },
    "devDependencies": {
        "@theia/cli": "next"
    }
}
```

**Comment by kittaakos** [comment]
> Not sure if I didn't rather mess up the bundling?

You need the `electron-builder` as a dev dependency if you want to bundle an application.
Did you check this https://github.com/theia-ide/yangster-electron?

**Comment by marechal-p** [comment]
Ok, so I cloned `yangster-electron`, removed the `yarn.lock` and built/packaged the electron app.
From there, I had the lastest Theia packages, without your patch, and I didn't have any issue...
(I started `dist/linux-unpacked/yangster-electron`).

Sorry if I couldn't test this in time. Do you have a list of steps for me to reproduce the issue you had?

**Comment by kittaakos** [comment]
I put this on hold. It fixes the issue in `@theia/core`, but other extensions might have the same problem.

As a full solution, I would like to implement a Travis hook, that traverses the extensions, checks the content of the `node_modules` folder for each extension, and fails when it contains anything than binaries.

**Comment by akosyakov** [comment]
I wonder how other electron apps handle it, having multiple node_modules folders with duplicate dependencies is very typical in Node.js world. Even if we manage to check everything in the Theia repo (which is hard), we cannot check external extensions.

**Comment by kittaakos** [comment]
> Having multiple node_modules folders with duplicate dependencies is very typical in Node.js world.

Assumption: the problem occurs because we do not declare explicit dependencies to the third-party libraries from the extensions. (Correct me if I am wrong.)

Running `yarn why yargs` in Theia shows the following:
```
yarn why v1.9.4
[1/4] 🤔  Why do we have the module "yargs"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "yargs@11.1.0"
info Has been hoisted to "yargs"
info Reasons this module exists
   - "workspace-aggregator-47136766-a005-47ac-8fef-08550217db9f" depends on it
   - Hoisted from "_project_#nyc#yargs"
   - Hoisted from "_project_#@theia#application-manager#webpack-cli#yargs"
info Disk size without dependencies: "444KB"
info Disk size with unique dependencies: "816KB"
info Disk size with transitive dependencies: "1.66MB"
info Number of shared dependencies: 35
=> Found "lerna#yargs@8.0.2"
info This module exists because "_project_#lerna" depends on it.
=> Found "@theia/core#yargs@9.0.1"
info This module exists because "_project_#@theia#core" depends on it.
info Disk size without dependencies: "288KB"
info Disk size with unique dependencies: "760KB"
info Disk size with transitive dependencies: "2.18MB"
info Number of shared dependencies: 48
=> Found "showdown#yargs@10.1.2"
info This module exists because "_project_#@theia#extension-manager#showdown" depends on it.
info Disk size without dependencies: "300KB"
info Disk size with unique dependencies: "672KB"
info Disk size with transitive dependencies: "1.52MB"
info Number of shared dependencies: 35
=> Found "electron-rebuild#yargs@7.1.0"
info This module exists because "_project_#@theia#application-manager#electron-rebuild" depends on it.
info Disk size without dependencies: "340KB"
info Disk size with unique dependencies: "812KB"
info Disk size with transitive dependencies: "2.23MB"
info Number of shared dependencies: 48
=> Found "handlebars#yargs@3.10.0"
info Reasons this module exists
   - "_project_#istanbul#handlebars#uglify-js" depends on it
   - Hoisted from "_project_#istanbul#handlebars#uglify-js#yargs"
=> Found "glob-all#yargs@1.2.6"
info This module exists because "_project_#@theia#application-manager#webpack-cli#glob-all" depends on it.
info Disk size without dependencies: "248KB"
info Disk size with unique dependencies: "344KB"
info Disk size with transitive dependencies: "344KB"
info Number of shared dependencies: 1
✨  Done in 1.90s.
```

We have `yargs` as a dependency from 
 - `application-manager`,
 - `extension-manager`, and 
 - `core`.

In the electron application, I did not include the
 - `extension-manager` and the 
 - `application-manager`.

Only `core` is included which has the direct dependency to `yargs`. But in the electron application, I added `filesystem` and `workspace`. After a quick search in the source, I can see both `workspace` and `filesystem` use `yargs` at runtime although they do not declare it as a dependency.

screen shot 2018-09-29 at 16 25 36

The electron builder ignores `devDependencies`, only the `core` depends on `yargs`, so `yargs` won't be hoisted to the root `node_modules` folder; `workspace` and `filesystem` fails at runtime.

Thoughts?

**Comment by kittaakos** [comment]
> Thoughts?

@akosyakov

**Comment by akosyakov** [comment]
> only the core depends on yargs, so yargs won't be hoisted to the root node_modules folder; workspace and filesystem fails at runtime.

I thought that yarn always hoist at least one version, maybe my assumptions are wrong.

**Comment by kittaakos** [comment]
> I thought that yarn always hoists at least one version, maybe my assumptions are wrong.

👍 Exactly. I had the same assumption. This is something I have to try out and experiment before we can decide how to proceed.

**Comment by kittaakos** [comment]
With the latest changes on this branch:
```
$ cross-env THEIA_CHECK_HOISTING_NO_BAIL=true node scripts/check-hoisting
🔍  Analyzing hoisted dependencies in the Theia extensions:
 - Checking @theia/bunyan...
 - Checking @theia/callhierarchy...
 - Checking @theia/console...
 - Checking @theia/core...
 - Checking @theia/cpp...
 - Checking @theia/debug...
 - Checking @theia/debug-nodejs...
 - Checking @theia/editor...
 - Checking @theia/editorconfig...
 - Checking @theia/extension-manager...
 - Checking @theia/file-search...
 - Checking @theia/filesystem...
 - Checking @theia/git...
 - Checking @theia/java...
 - Checking @theia/json...
 - Checking @theia/keymaps...
 - Checking @theia/languages...
 - Checking @theia/markers...
 - Checking @theia/merge-conflicts...
 - Checking @theia/messages...
 - Checking @theia/metrics...
 - Checking @theia/mini-browser...
 - Checking @theia/monaco...
 - Checking @theia/navigator...
 - Checking @theia/outline-view...
 - Checking @theia/output...
 - Checking @theia/plugin...
 - Checking @theia/plugin-ext...
 - Checking @theia/plugin-ext-vscode...
 - Checking @theia/preferences...
 - Checking @theia/preview...
 - Checking @theia/process...
 - Checking @theia/python...
 - Checking @theia/search-in-workspace...
 - Checking @theia/task...
 - Checking @theia/terminal...
 - Checking @theia/textmate-grammars...
 - Checking @theia/tslint...
 - Checking @theia/typehierarchy...
 - Checking @theia/typescript...
 - Checking @theia/userstorage...
 - Checking @theia/variable-resolver...
 - Checking @theia/workspace...
📖  Issue summary:
🎉  No dependency issues were detected.
✨  Done in 0.29s.
```

**Comment by kittaakos** [comment]
Ready for review. I had to apply one dirty hack, I pinned the version of `ajv` to `6.5.3`. I wanted to use `^6.5.4` instead, but multiple modules depend on this particular version :(

**Comment by kittaakos** [comment]
I have overlooked a test case, will fix it soon. It was due to an API change in the `jsonc-parser`. For more details, see here: https://github.com/Microsoft/node-jsonc-parser/issues/13.

**Pull request merged**
