### PR TITLE
Update incorrect git commit font

### LINKED ISSUE #3435: [css][electron][windows] Incorrect font type in the Git widget
screen shot 2018-11-08 at 09 33 15

On Windows in electron.

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #3435

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@kittaakos I decided to update the `textarea` property from `core` instead of simply updating the font-family for `.theia-git-commit-message-container textarea`. My reasoning was so that all current and future textarea in Theia would all share the same font-family styling to ensure consistency. If I simply update `.theia-git-commit-message-container textarea` then there is no guarantee in the future that the issue will not occur in a different case.

If however you'd like me to only update the font-family for `.theia-git-commit-message-container textarea` I can do so :)

**Comment by kittaakos** [comment]
Thanks for the patch, @vince-fugnitto. Any ideas why it works on OS X but not on Windows?

**Comment by vince-fugnitto** [comment]
> Thanks for the patch, @vince-fugnitto. Any ideas why it works on OS X but not on Windows?

I'm not certain but perhaps since the `textarea` was not using the `--theia-ui-font-family` it was simply defaulting to a system font which can be quite different between operating systems? OSX would probaly use the nice `Helvetica Neue` while Windows something different entirely?

**Comment by kittaakos** [comment]
> OSX would probaly use the nice `Helvetica Neue` while Windows something different entirely?

👍 Makes sense. Thanks for the clarification.

**Comment by vince-fugnitto** [comment]
> > OSX would probaly use the nice `Helvetica Neue` while Windows something different entirely?
> 
>  Makes sense. Thanks for the clarification.

is it fine to approve and merge @kittaakos ?

**Comment by kittaakos** [comment]
Sure, I will take care of it today.

**Comment by vince-fugnitto** [comment]
thanks @kittaakos ! :)

**Pull request merged**
