### PR TITLE
Fix plugin initialization when browser is refreshed

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does PR do:
Stops remote plugins before initialization

### Reference issue
https://github.com/theia-ide/theia/issues/3970

### CODE REVIEW

**Comment by benoitf** [comment]
hello, it doesn't try to stop plug-in before it's started as well ?

**Comment by tolusha** [comment]
It does stop plugin before start in case of `backend`
https://github.com/theia-ide/theia/blob/f20cd2e0afc08d6560faf416f6fae2c08f61fdcd/packages/plugin-ext/src/hosted/browser/hosted-plugin.ts#L133

`stopPlugin` causes plugin deactivation:
```text

PLUGIN_HOST(1): PluginManagerExtImpl/init()
--
  | PLUGIN_HOST(1): initializing(/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
  | Debugger contribution has been registered: cppdbg
  | Debugger contribution has been registered: cppvsdbg
  | PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/plugins/ms-vscode.cpptools.0.20.1/extension/out/src/main)
  | Debug configuration provider has been registered: cppdbg
  | activating extension
```

Page is refreshed:

```text
  | deactivating extension
  | TypeError: Cannot read property 'dispose' of undefined
  | at Object.deactivate (/plugins/ms-vscode.cpptools.0.20.1/extension/out/src/LanguageServer/extension.js:557:8)
  | at ActivatedPlugin.deactivate [as stopFn] (/plugins/ms-vscode.cpptools.0.20.1/extension/out/src/main.js:50:27)
  | at /home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:72:28
  | at Map.forEach (<anonymous>)
  | at PluginManagerExtImpl.$stopPlugin (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:69:31)
  | at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:173:23)
  | at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:158:41)
  | at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:122:45)
  | at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:108:22)
  | at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:51:89
  | PLUGIN_HOST(1): PluginManagerExtImpl/init()
  | PLUGIN_HOST(1): initializing(/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
  | Debugger contribution has been registered: cppdbg
  | Debugger contribution has been registered: cppvsdbg
  | PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/plugins/ms-vscode.cpptools.0.20.1/extension/out/src/main)
  | Debug configuration provider has been registered: cppdbg
  | activating extension
```

**Comment by benoitf** [comment]
@tolusha what I mean is that stop should not be called when we load plug-ins. Lifecycle is : init, start, stop, not init, stop, start

**Comment by tolusha** [comment]
Closed in favor of https://github.com/theia-ide/theia/pull/4583

**Pull request closed without merging**
