### PR TITLE
fix #5927: plugin ext file path error

### LINKED ISSUE #5927: [vscode] vscode ext can't get file
### Description
```
GET https://theia.miaowoo.cc/hostedPlugin/ms_kubernetes_tools_vscode_kubernetes_tools/images%2Flogo.svg 404
images%2Fdark%2Frefresh.svg:1 
GET https://theia.miaowoo.cc/hostedPlugin/ms_kubernetes_tools_vscode_kubernetes_tools/images%2Fdark%2Frefresh.svg 404
```

### Reproduction Steps

- Press F1
- Deploy Plugin By Id
- input `ext install ms-kubernetes-tools.vscode-kubernetes-tools`
- until install finish
- refresh theia

**OS and Theia version:**
latest next version

**Diagnostics:**

### PR DESCRIPTION
**Pull request by 502647092**
#### What it does
fix: #5927

image

#### How to test
- Press F1
- Deploy Plugin By Id
- input ext install ms-kubernetes-tools.vscode-kubernetes-tools
- until install finish
- refresh theia
- the ext logo show correct

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@azatsarynnyy Could you check please that icons for kubernetes VS Code extension work well as before?

**Comment by azatsarynnyy** [comment]
@akosyakov sure, I'll test it today

**Comment by azatsarynnyy** [comment]
I've tested the PR and can confirm that it fixes the issue with icons
image

**Comment by akosyakov** [comment]
Let me check that it works with relative paths as well.

**Pull request merged**
