### PR TITLE
migrate to latest Monaco to support hierarchical symbols

### LINKED ISSUE #2304: a new editor should be opened in the active tag group
For example, a cross reference navigation should open an editor next to existing, not in first tab group.

### LINKED ISSUE #2717: Error when opening inline editor via code lens
Originally from here: https://github.com/theia-ide/yangster/issues/64

Then I have verified with Java too, same error. Click on a code lens (of references)

errors.ts:81 Uncaught Error: Cannot read property 'lineNumber' of null

```
TypeError: Cannot read property 'lineNumber' of null
    at monaco-editor.js:120
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onMouseDown (codeEditorWidget.ts:438)
    at ViewOutgoingEvents.emitMouseDown (viewOutgoingEvents.ts:99)
    at ViewController.emitMouseDown (viewController.ts:311)
    at TouchHandler.MouseHandler._onMouseDown (mouseHandler.ts:259)
    at mouseHandler.ts:110
    at HTMLDivElement.<anonymous> (editorDom.ts:127)
    at monaco-editor.js:120
    at Emitter.fire (event.ts:140)
    at ViewOutgoingEvents.viewEventBus.onMouseDown (codeEditorWidget.ts:438)
    at ViewOutgoingEvents.emitMouseDown (viewOutgoingEvents.ts:99)
    at ViewController.emitMouseDown (viewController.ts:311)
    at TouchHandler.MouseHandler._onMouseDown (mouseHandler.ts:259)
    at mouseHandler.ts:110
    at HTMLDivElement.<anonymous> (editorDom.ts:127)
    at errors.ts:81
```

### PR DESCRIPTION
**Pull request by akosyakov**
What is broken:
- [x] syntax coloring
- [x] cross editor navigation, fixes #2304
- [x] fixes #2717

Please test and add what is broken.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
compilation error:

```
lerna ERR! [lint] theiaext lint exited with code 0
lerna ERR! [compile] src/browser/monaco-command-service.ts(28,14): error TS2420: Class 'MonacoCommandService' incorrectly implements interface 'ICommandService'.
lerna ERR! [compile]   Property '_onWillExecuteCommand' is missing in type 'MonacoCommandService'.
lerna ERR! [compile] src/browser/monaco-editor-provider.ts(72,53): error TS2345: Argument of type '{ editorService: MonacoEditorService; textModelService: MonacoTextModelService; contextMenuServic...' is not assignable to parameter of type 'IEditorOverrideServices'.
lerna ERR! [compile]   Types of property 'commandService' are incompatible.
lerna ERR! [compile]     Type 'MonacoCommandService' is not assignable to type 'ICommandService | undefined'.
lerna ERR! [compile]       Type 'MonacoCommandService' is not assignable to type 'ICommandService'.
lerna ERR! [compile]         Property '_onWillExecuteCommand' is missing in type 'MonacoCommandService'.
lerna ERR! [compile] src/browser/monaco-editor-provider.ts(76,36): error TS2345: Argument of type 'StandaloneCommandService' is not assignable to parameter of type 'ICommandService | undefined'.
lerna ERR! [compile]   Type 'StandaloneCommandService' is not assignable to type 'ICommandService'.
lerna ERR! [compile]     Property '_onWillExecuteCommand' is missing in type 'StandaloneCommandService'.
```

**Comment by akosyakov** [comment]
@AlexTugarev pushed again

**Comment by akosyakov** [comment]
I've pushed again to fix broken coloring.

**Comment by akosyakov** [comment]
@evidolob Hi, did you access any internal apis from Monaco from the plugin extension, except those which are defined in monaco extension? If yes please check it could break plugin. Ideally, we should avoid using internal apis except for Monaco extension, to keep it manageable.

**Comment by AlexTugarev** [comment]
screen shot 2018-09-03 at 17 57 16

code lenses for Java seems to work. 'will test with more examples.

**Comment by AlexTugarev** [comment]
it's cool that navigation within the editor considers tab groups. 

OT: it would be awesome to support same for opening files from navigator.

**Comment by akosyakov** [comment]
@AlexTugarev Do you think we can merge it?

**Comment by svenefftinge** [comment]
Rename in TS doesn'T work for me:

```
simpleServices.ts:452 Uncaught (in promise) Error: bad edit - model not found
    at SimpleBulkEditService.apply (simpleServices.ts:452)
    at rename.ts:185
```

**Comment by AlexTugarev** [comment]
@akosyakov, @svenefftinge, I can confirm now, it's broken if the file which contains a reference to the symbol being renamed is closed.

**Comment by AlexTugarev** [comment]
testing right now...

**Comment by AlexTugarev** [comment]
Verified with Java, rename works again.

**Pull request merged**
