### PR TITLE
Changed `Modifier` to `KeyModifier` and each enum member to its key

### PR DESCRIPTION
**Pull request by marechal-p**
This is my attempt at fixing #458

Re-opened a new pull-request pointing to a specific branch, so that I can work on a per-feature basis (seems easier to create a PR on a specific branch rather than playing around in master alone...)

As I could not change the branch used for the PR I recreated this one, it felt cleaner.
(also now that I better know how it works I won't mess up too much the PR logs, sorry)

_(also seems like I could have used the `user/branch` notation, still learning)_

### CODE REVIEW

**Comment by akosyakov** [comment]
LGTM, any objections?

**Comment by epatpol** [comment]
Maybe not have the "This is my attempt at fixing #458" inside the commit message is the first thing that comes to mind. I think a simple "Fixes #458" would be perfect.

**Comment by WKnight02** [comment]
Indeed. Fixed.

**Comment by akosyakov** [comment]
@marechal-p thank you! merged

**Pull request merged**
