### PR TITLE
use VS Code icons in a tabbar toolbar

### PR DESCRIPTION
**Pull request by akosyakov**
TODO:
- [x] CQ for new icons: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19390

Screen Shot 2019-03-20 at 13 14 46

### CODE REVIEW

**Comment by kittaakos** [comment]
Checking it now...

----

I have restarted the Windows CI:
```
Output:
46Failed to download Java LS: Error: getaddrinfo ENOTFOUND download.eclipse.org download.eclipse.org:80
47info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
48
```

**Comment by kittaakos** [comment]
I have seen a lot of these in the logs:
```
oot ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root ERROR TypeError: Cannot read property 'getElementsByClassName' of undefined
    at ToolbarAwareTabBar.get [as contentNode] (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89282:41)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/tabbar.js.TabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:21714:54)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ScrollableTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89176:42)
    at ToolbarAwareTabBar.../../packages/core/lib/browser/shell/tab-bars.js.ToolbarAwareTabBar.onUpdateRequest (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:89323:42)
    at ToolbarAwareTabBar.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-b0af2e3e-7e62-45ca-a84c-9499de374992.ws-eu0.gitpod.io/bundle.js:7635:17)
root INFO There is no document formatter for 'markdown'-files installed.
```

I am sure we have (or used to have) a GH issue with a very similar if not the same error. I could not find it.

**Comment by akosyakov** [comment]
@kittaakos https://github.com/theia-ide/theia/issues/3674 I will have a look at it separately

**Comment by kittaakos** [comment]
> I will have a look at it separately

Sure sure, I have no intention of holding you back.

**Pull request merged**
