### PR TITLE
Fixed #5419: supported key chords display & search in the Keybinding widget

### LINKED ISSUE #5419: [keybindings] key chords are displayed incorrectly
In the Keybinding widget, the key chords are not displayed correctly.

Screenshot from 2019-06-11 12-37-50

### PR DESCRIPTION
**Pull request by fangnx**
Fixed #5419.

- Fixed the display issue with key chords in the Keybinding widget. 
- Updated the keybinding search function to support fuzzy search with key chords.

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
It works really well! 
@lmcbout @elaihau do you mind taking a look as well ? :)

**Comment by elaihau** [comment]
is the keybinding widget supposed to auto-update after the keybindings are changed? I tested in gitpod and looks like it does not get refreshed.

**Comment by vince-fugnitto** [comment]
> is the keybinding widget supposed to auto-update after the keybindings are changed? I tested in gitpod and looks like it does not get refreshed.

Do you mean the `keymaps.json` is updated, and it is not reflected in the widget?

**Comment by elaihau** [comment]
> > is the keybinding widget supposed to auto-update after the keybindings are changed? I tested in gitpod and looks like it does not get refreshed.
> 
> Do you mean the `keymaps.json` is updated, and it is not reflected in the widget?

yes. i needed to refresh browser to have the most updated keybindings shown in the widget

**Comment by fangnx** [comment]
> > > is the keybinding widget supposed to auto-update after the keybindings are changed? I tested in gitpod and looks like it does not get refreshed.
> > 
> > 
> > Do you mean the `keymaps.json` is updated, and it is not reflected in the widget?
> 
> yes. i needed to refresh browser to have the most updated keybindings shown in the widget

I just tested it and got the same issue. Seems like it can be another issue/PR ;)

**Pull request merged**
