### PR TITLE
fix issue with `timeout=0`

### PR DESCRIPTION
**Pull request by AlexTugarev**
This contains suggested fixes for issues found during tests of PR #1491.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
@lmcbout I reset the branch again. I was not mergeable. If you like it, please merge it into `issue_1081` and squash it there as you wish to continue.

**Comment by lmcbout** [comment]
@AlexTugarev I squashed the commit, rebased and pushed it into your branch.

**Comment by AlexTugarev** [comment]
@lmcbout it won't work this way, as I've created a PR for your branch, not for master. please, merge into `issue_1081` and continue there.

**Comment by lmcbout** [comment]
OK, I rebase onto 1081

**Pull request closed without merging**
