### PR TITLE
[terminal] permit showing widget for already running terminal

### PR DESCRIPTION
**Pull request by marcdumais-work**
This contains the infrastructure, but no UI yet.

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>

### CODE REVIEW

**Comment by hexa00** [comment]
This looks nice but it would be nice to have a user of the attach to be able to test it in the same PR ?

**Comment by marcdumais-work** [comment]
@hexa00 The task stuff I am working-on will use it. The only case I can see ATM is permitting to connect a second (, third,...) xterm widget to an existing shell process. That doesn't seem very useful. Other ideas?

**Comment by hexa00** [comment]
We could wait for the stuff you're working on now?

**Comment by marcdumais-work** [comment]
ok

**Comment by marcdumais-work** [comment]
Will re-submit with the Task PR

**Pull request closed without merging**
