### PR TITLE
[WIP] [textmate] Removed csharp grammar and def

### PR DESCRIPTION
**Pull request by svenefftinge**
Fixes theia-ide/theia#2555

### CODE REVIEW

**Comment by marechal-p** [comment]
Seems like we were using the `csharp` grammar for the `handlebars` grammar?
https://github.com/theia-ide/theia/blob/GH-2555/packages/textmate-grammars/src/browser/handlebars.ts#L57

This is also why the build is not passing.

**Comment by svenefftinge** [comment]
Argh! I put [WIP] in front to indicate it should not be merged

**Comment by svenefftinge** [comment]
The csharp extension doesn't work yet, please revert.

**Comment by jbicker** [comment]
Shit, sorry!

**Pull request merged**
