### PR TITLE
Generate bépo keyboard layout

### PR DESCRIPTION
**Pull request by Beetix**
I've run the keyboard layout generation for bépo. I am now able to use keyboard shortcuts. Unfortunately not all shortcuts work. For example, this is the case for undo (Ctrl + z). I don't know why. Also the info field generated on my machine (running Arch Linux) and also on Gitpod does not match the format of the other layouts.

### CODE REVIEW

**Comment by AlexTugarev** [comment]
@Beetix thanks for creating this PR!

You need to sign an [ECA](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git) and sign off your commit.

**Comment by spoenemann** [comment]
I generated all other PC layouts on Windows. I know the creators of the [native-keymap](https://www.npmjs.com/package/native-keymap) package have had some struggle with the Linux integration, e.g. it doesn't support keyboard layout change detection. More importantly, the layout generated on Linux misses the `vkey` information that is necessary to correctly derive keybindings on Windows.

@Beetix do you have access to a machine with Windows installation (or maybe a VM) to generate the layout?

**Comment by Beetix** [comment]
I see. Thank you for the explanation.

Yes I can run it on Windows.

Do you have any idea regarding the issue with the Ctrl+z? My current thought is that the z key bépo mapping corresponds to 'à' which is not ASCII.

**Comment by spoenemann** [comment]
> Do you have any idea regarding the issue with the Ctrl+z? My current thought is that the z key bépo mapping corresponds to 'à' which is not ASCII.

What is your expectation? Should `ctrl+à` be mapped to _undo_? The current key mapping logic would keep the keybinding as `ctrl+z`.

**Comment by Beetix** [comment]
Yes I would like `ctrl+z` to be bound to undo. Unfortunately it doesn't work. I was trying to find an explanation. I realize that looking at `KeyZ` is wrong because that matches a physical position on the keyboard. The "physical key" that actually gives the value `z` is `BracketLeft` according to the generated layout.

**Comment by spoenemann** [comment]
The best way to find out what's going on would be to set a breakpoint here:

https://github.com/theia-ide/theia/blob/9395eda975d3c76557a1c36c385ef3e22c3e62e8/packages/core/src/browser/keyboard/keyboard-layout-service.ts#L141-L197

The code should get to an entry where `code` is `BracketLeft` and `keyMapping.value` is `z`.

But maybe it's better to generate the layout on Windows before debugging?

**Comment by Beetix** [comment]
I ran the keyboard layout generation on Windows 10. I also did a quick test with Theia browser example. `ctrl+z` was working on Windows! Tried it back on Linux but it still didn't work... I guess debugging is necessary.

**Comment by spoenemann** [comment]
The mentioned entry is present in the json file:
```json
"BracketLeft": {
    "vkey": "VK_Z",
    "value": "z",
    "withShift": "Z",
    "withAltGr": "ə",
    "withShiftAltGr": "Ə"
}
```
This should lead to an entry in the `key2KeyCode` map. Then it should be picked up by the following code when the KeyCode for the "Undo" keybinding is resolved:

https://github.com/theia-ide/theia/blob/9395eda975d3c76557a1c36c385ef3e22c3e62e8/packages/core/src/browser/keyboard/keyboard-layout-service.ts#L77-L92

**Comment by Beetix** [comment]
I've been debugging using Chromium. I have placed a breakpoint on `resolveKeyCode` but I don't get any hit... I can't figure what I am doing wrong.

Looking at the console's logs I get several keybinding warnings, here is the one mentioning `ctrl+z`: 
`logger-protocol.ts:112 root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+[","context":"terminalActive"}  collided with  {"command":"passthrough","keybinding":"ctrl+z","context":"terminalActive"}
`

**Comment by Beetix** [comment]
I ran the browser example back on Windows to compare. There are fewer keybinding collisions. I also tried other layouts on Linux. Here are the logs I got:
* bépo on Windows
```
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
```
* bépo on Linux
```
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.foldAllBlockComments","keybinding":"ctrl+k ctrl+/","context":"strictEditorTextFocus"}  collided with  {"command":"monaco.editor.action.formatSelection","keybinding":"ctrl+k ctrl+f","context":"strictEditorTextFocus"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"monaco.editor.foldAllBlockComments","keybinding":"ctrl+k ctrl+/","context":"strictEditorTextFocus"}
Error: "ctrl+k ctrl+/" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+[","context":"terminalActive"}  collided with  {"command":"passthrough","keybinding":"ctrl+z","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+[","context":"terminalActive"}
Error: "ctrl+[" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+]","context":"terminalActive"}  collided with  {"command":"passthrough","keybinding":"ctrl+w","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+]","context":"terminalActive"}
Error: "ctrl+]" is in collision with something else [scope:0] logger-protocol.ts:112:15
```
* qwerty on Linux:
```
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
```
* azerty on Linux:
```
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.quickFix","keybinding":"ctrl+.","context":"strictEditorTextFocus"}  collided with  {"command":"monaco.editor.action.inPlaceReplace.down","keybinding":"shift+ctrl+.","context":"strictEditorTextFocus"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.quickFix","keybinding":"ctrl+.","context":"strictEditorTextFocus"}
Error: "ctrl+." is in collision with something else [scope:0] logger-protocol.ts:112:15
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"} logger-protocol.ts:112:15
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
```

**Comment by spoenemann** [comment]
The "Undo" keybinding is shadowed by the "Outdent Line" keybinding. That's a bug in the transformation logic, I'll open a separate issue for that.

**Comment by Beetix** [comment]
Ok! Thank you for your help.

**Pull request merged**
