### PR TITLE
[ldm] use gulp4 to incrementally copy changes and watch local dependencies

### PR DESCRIPTION
**Pull request by akosyakov**
@hexa00 could you verify with this PR whether you still have issues with missing files during watching?

### CODE REVIEW

**Comment by hexa00** [comment]
OK, I'm trying this out today

**Comment by hexa00** [comment]
This brings a lot of improvements, it no longer complains about half written files!!

I did found an issue however when removing files:

To test I add and remove my logging patch which brings in new files or removes them as I apply/unapply

I run my watch as such:
```"watch": "concurrently --names watch-deps,watch-backend,watch-frontend --prefix \"[{name}]\" \"npm run watch:localdeps" \"npm run watch:backend\"  \"npm run watch:frontend\"",```

And when I unapply I get:
````
[watch-deps] theia-core: 9:30:30 AM - File change detected. Starting incremental compilation...
[watch-deps] 
[watch-backend] 9:30:30 AM - File change detected. Starting incremental compilation...
[watch-backend] 
[watch-backend] 
[watch-backend] 9:30:31 AM - Compilation complete. Watching for file changes.
[watch-backend] 
[watch-backend] 
[watch-frontend] Hash: af26225920552b990b45
[watch-frontend] Version: webpack 2.6.1
[watch-frontend] Time: 2468ms
[watch-frontend]                                    Asset      Size  Chunks                    Chunk Names
[watch-frontend]                                bundle.js   2.02 MB       0  [emitted]  [big]  main
[watch-frontend]     0.61833de20cc870b8fffc.hot-update.js   2.41 kB       0  [emitted]         main
[watch-frontend]     61833de20cc870b8fffc.hot-update.json  43 bytes          [emitted]         
[watch-frontend]                            bundle.js.map   2.76 MB       0  [emitted]         main
[watch-frontend] 0.61833de20cc870b8fffc.hot-update.js.map   3.98 kB       0  [emitted]         main
[watch-frontend]  [155] ./src/frontend/main.ts 2.69 kB {0} [built]
[watch-frontend]  [329] ./~/xterm/lib/addons ^\.\/.*$ 488 bytes {0} [built]
[watch-frontend]     + 337 hidden modules
[watch-deps] theia-core: src/application/browser/logger-frontend-module.ts(10,48): error TS2307: Cannot find module '../common/logger'.
[watch-deps] src/application/node/logger-backend-module.ts(8,48): error TS2307: Cannot find module '../common/logger'.
[watch-deps] src/application/node/logger-backend-module.ts(9,36): error TS2307: Cannot find module './logger-server'.
[watch-deps] src/application/node/logger-server-module.ts(11,31): error TS2307: Cannot find module '../../application/common/logger'.
[watch-deps] src/application/node/logger-server.ts(8,41): error TS2307: Cannot find module '../../application/common/logger'.
[watch-deps] 9:30:32 AM - Compilation complete. Watching for file changes.
[watch-deps] Had errors, not spawning
[watch-deps] 
[watch-backend] 9:30:33 AM - File change detected. Starting incremental compilation...
[watch-backend] 
[watch-backend] 
[watch-backend] 9:30:34 AM - Compilation complete. Watching for file changes.
[watch-backend] 
[watch-backend] 
[watch-frontend] Hash: 03d4d39e8f81ea362a7d
[watch-frontend] Version: webpack 2.6.1
[watch-frontend] Time: 1810ms
[watch-frontend]                                    Asset      Size  Chunks                    Chunk Names
[watch-frontend]                                bundle.js   2.02 MB       0  [emitted]  [big]  main
[watch-frontend]     0.af26225920552b990b45.hot-update.js   3.89 kB       0  [emitted]         main
[watch-frontend]     af26225920552b990b45.hot-update.json  43 bytes          [emitted]         
[watch-frontend]                            bundle.js.map   2.76 MB       0  [emitted]         main
[watch-frontend] 0.af26225920552b990b45.hot-update.js.map    6.4 kB       0  [emitted]         main
[watch-frontend]  [155] ./src/frontend/main.ts 2.69 kB {0} [built]
[watch-frontend]  [322] ./src/frontend/index.ts 1.43 kB {0} [built]
[watch-frontend]  [329] ./~/xterm/lib/addons ^\.\/.*$ 488 bytes {0} [built]
[watch-frontend]     + 336 hidden modules
````

So the files watch-deps is complaining about do not exist anymore it's like it saw 1 file move, and started compiling before all the files were deleted by git...

This issue is minor compared to what we had before however so this is a major improvement IMO.

Applying the patch back works,  normal workflow works fine, editing code and saving etc...

Thanks!

**Comment by akosyakov** [comment]
@hexa00 Thanks for verifying! It also should be faster, synchronization always happens incrementally.

**Comment by hexa00** [comment]
Thanks! Note I made this PR  #176 to fix the watch commands, which were broken for the examples...

**Pull request merged**
