### PR TITLE
Fix debug theme coloring for menu and breakpoints

### LINKED ISSUE #3032: breakpoints are not visible
Currently, breakpoints are not visible in the light theme. Ideally, styles should be aligned with VS Code.

breakpoints

### LINKED ISSUE #3036: Debug menu not rendered properly
Icons for debug menu clash on white theme

selection_034

Related to #3032

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes #3036

selection_055

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@vince-fugnitto breakpoints should be styled as in VS Code, it does not properly really fix https://github.com/theia-ide/theia/issues/3032, could you remove `Fixes` tag for it

**Comment by vince-fugnitto** [comment]
@akosyakov sure no problem, I only followed having the greyed out circle outline for inactive breakpoints and a red breakpoint for active. I can play around trying to see with css selectors if my parent is disabled, I'll grey out my icon with an alpha value.

**Comment by vince-fugnitto** [comment]
@akosyakov is this the styling you were thinking of according to vscode?

selection_046

selection_045

**Comment by vince-fugnitto** [comment]
closing in order to produced PRs with reduced scope

**Pull request closed without merging**
