### PR TITLE
Disallow users to commit without a commit message

### LINKED ISSUE #1532: No notification if one commits without commit message. Last message will be used.
If I reload the theia page and commit something without a commit message, I get a notification.
But if I already committed something before, the last typed message will be committed again next time.
nocommitmsg

### PR DESCRIPTION
**Pull request by elaihau**
- Fixes #1532

Signed-off-by: elaihau <liang.huang@ericsson.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
I am doing the review now. Meanwhile, I have restarted the Windows build on AppVeyor.

**Comment by AlexTugarev** [comment]
@kittaakos and @elaihau that would be awesome 👍 

the thing is, having two input fields might be less intuitive, but, as I've learned recently, the first line of a commit message is treated specially, even by git itself.

**Comment by kittaakos** [comment]
I agree, @AlexTugarev. I am not holding back this PR for sure, but that is just a temporary solution. @elaihau, if you would have time working on the new UI concept, that would be great.

**Comment by kittaakos** [comment]
BTW, here is the corresponding ticket that covers the validation: https://github.com/theia-ide/theia/issues/590

**Comment by elaihau** [comment]
@kittaakos @AlexTugarev I just tried what VS code does to the longer commit messages. it looks really good. 

#590 will be the next thing i would do after finishing up my current task. Thank you !

**Pull request merged**
