### PR TITLE
Reorganize the tslint.json files

### PR DESCRIPTION
**Pull request by simark**
The end goal of this is to have a tslint.json at the root of the
project.  By putting it there, tslint will automatically pick it up, no
need to explicitly point to it with -c/--config.

This will help when we'll have tslint integrated into Theia as a
language server.  It will will automatically find the rules without any
extra configuration.  Eventually, we'll want to offer the user a
preference to point to a specific tslint.json, but that will come later.
And anyway, it's better if it works out of the box, without having to
set a preference.

I am a bit confused by the current naming (strict.tsconfig.json and
tsconfig.json).  One contains rules we want as warnings, and the other
the rules we want as errors, so I renamed them warnings.tslint.json and
errors.tslint.json.  The tslint.json at the root just imports both
files.

### CODE REVIEW

**Comment by simark** [comment]
Anybody knows why the tslint rules are organized as they are currently?

**Comment by simark** [comment]
According to @MarkZ3, `all.tslint.json` might be used for Sonar.  I re-added it, now it imports the tslint.json at the root, and adds some more rules.

**Comment by marcdumais-work** [comment]
@simark as far as I am concerned you could remove all.tslint.json: we did use it at one point for (internal) Sonar, but no longer. It makes more sense to use strict.tslint.json (or the equivalent one, in the root folder, after this PR goes in).

**Comment by simark** [comment]
> @simark as far as I am concerned you could remove all.tslint.json: we did use it at one point for (internal) Sonar, but no longer. It makes more sense to use strict.tslint.json (or the equivalent one, in the root folder, after this PR goes in).

Ok, I updated the patch to remove it.  Leaving some unused rule files would just contribute to confusion in the future.

**Comment by simark** [comment]
Thanks.

**Comment by akosyakov** [comment]
> The end goal of this is to have a tslint.json at the root of the
project. By putting it there, tslint will automatically pick it up, no
need to explicitly point to it with -c/--config.

The idea was to keep the repo repo uncluttered as much as possible by moving the configuration to the separate folder.

> This will help when we'll have tslint integrated into Theia as a
language server. It will will automatically find the rules without any
extra configuration. Eventually, we'll want to offer the user a
preference to point to a specific tslint.json, but that will come later.
And anyway, it's better if it works out of the box, without having to
set a preference.

Why do you need a preference? It is a matter of one line to configure a path  for `tslint-language-service` in tsconfig.json.

> I am a bit confused by the current naming (strict.tsconfig.json and
tsconfig.json). One contains rules we want as warnings, and the other
the rules we want as errors, so I renamed them warnings.tslint.json and
errors.tslint.json. The tslint.json at the root just imports both
files.

Why warning and errors are better, to me is quite random choice? Configs are organized by usages:
- tslint.json is used by the build and editor contains rules which we follow already
- strict.tslint.json is used only by the tool and introduce more strict rules which we want to follow and eventually move to tslint.json

**Comment by akosyakov** [comment]
I would like to revert it. You can add "configFile": "../tslint.json" in https://github.com/theia-ide/theia/pull/1662/files#diff-e5e546dd2eb0351f813d63d1b39dbc48R91. It should do what you want.

**Comment by simark** [comment]
> Why warning and errors are better, to me is quite random choice? Configs are organized by usages:
> 
>     tslint.json is used by the build and editor, it contains rules which we follow already
>     strict.tslint.json is used only by the tool and introduce more strict rules which we want to follow and eventually move to tslint.json

Then `tslint.json` is exactly `errors.tslint.json` and `strict.tslint.json` is exactly `warnings.tslint.json`.  When you want to recommend a practice, put it in `warnings`, when you want to enforce it, move it to errors.  To me "strict" wasn't clear...

Putting tslint.json in the root offers the advantage that any static analysis tool can find it.  Adding `"configFile": "configs/strict.tslint.json"` to `tsconfig.json` only affects `tslint-language-service`, which means all tools require such extra configuration.  It's much better IMO to put the file at its well-known location where tools expect to find it.

**Comment by simark** [comment]
> The idea was to keep the repo root uncluttered as much as possible by moving the configuration to the separate folder.

That's why the extra files are still in the config directory.  I think having a tslint.json in the root of a typescript project is a reasonnable amount of clutter.

**Comment by akosyakov** [comment]
> At least with error and warning, it tells exactly what these rules are used for.

How from `errors` one can derive that it is executed by npm scripts and the tool?  How from `warnings` one can derive that rules are executed only by the tool? Why should we assume that rules executed by npm scripts cannot be warnings or by the tool cannot be errors?

> To me "strict" wasn't clear. Instinctively, I thought that "strict" meant the rules that we are strict about, that would cause errors. But it wasn't the case.

We could reverse naming.

Looking at the code closer i am not sure how it works now. npm scripts does not reference proper tslint config anymore, i assume now all rules executed by npm scripts which is bogus.

**Comment by akosyakov** [comment]
It is the case: https://travis-ci.org/theia-ide/theia/jobs/363082951#L836 npm scripts executes everything now instead of only rules from tslint as before.

**Comment by akosyakov** [comment]
Let's discuss it tomorrow at the dev meeting, if it does not bother anybody, we can simplify to one tsling.json file with some rules as warnings or maybe fix remaining. When we introduced tslint whether were about 5K warnings only for the core. It was quite bothering to recognise real errors among everything. Now looking at the build output there are 222 in total. We did quite a good job fixing them.

**Pull request merged**
