### PR TITLE
Add 'title' for widgets in the sidebar

### PR DESCRIPTION
**Pull request by vince-fugnitto**
#### What it does

- added `title` to widgets present in the sidebar by using the widget's caption.
- adjusted the `explorer` to display the workpace uri path when hovering over
the widget's title.

_Examples: (when hovering the title)_

Screen Shot 2019-08-14 at 12 27 48 PM

Screen Shot 2019-08-14 at 12 29 50 PM

#### How to test

- test with as many widgets as possible.
- hover over the title for widgets present in the sidebar (a html title should now be displayed)
- hovering over the `explorer` title should display the workspace uri path when in a single-root

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
We need to test it with plugin system adding views to the explorer and then toggle between single and multi view modes to check that captions look good in all cases.

**Comment by vince-fugnitto** [comment]
> We need to test it with plugin system adding views to the explorer and then toggle between single and multi view modes to check that captions look good in all cases.

How can I test that case? The same way described in your PR #5665 ?

**Comment by akosyakov** [comment]
yes, you can adjust the sample extension to contribute to the explorer

**Comment by vince-fugnitto** [comment]
I tested using the [`tree-view-sample`](https://github.com/microsoft/vscode-extension-samples/tree/master/tree-view-sample) with both the single and multi views. The code handles the case where no caption is present by simply displaying the widget's title instead.

**Multi-View (Explorer + JSON Outline)**

a

**Single-View (Explorer Only)**

b

**Comment by akosyakov** [comment]
@vince-fugnitto What do you see when you hover over `TREE-VIEW-SAMPLE` in the multi view mode?

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto What do you see when you hover over `TREE-VIEW-SAMPLE` in the multi view mode?

The panels don't display an individual title, should we add them for those items as well?

c

**Comment by akosyakov** [comment]
> The panels don't display an individual title, should we add them for those items as well?

I thought it was the issue that @lmcbout wanted to see the path whenever he hovers over the project root as it was before?

**Comment by vince-fugnitto** [comment]
> I thought it was the issue that @lmcbout wanted to see the path whenever he hovers over the project root as it was before?

Yes that's true, apparently I only handle the case of displaying the path when there is a single-view, but I should also do something similar for when it's in a multi-view.

**Comment by akosyakov** [comment]
Basically `caption` should be set (and updated) here: https://github.com/theia-ide/theia/blob/e8a29ca5690548b1a7fa0a646274be2c3e9b0426/packages/navigator/src/browser/navigator-frontend-module.ts#L55-L59

and then everything should work

**Comment by vince-fugnitto** [comment]
> Basically `caption` should be set (and updated) here:
> 
> https://github.com/theia-ide/theia/blob/e8a29ca5690548b1a7fa0a646274be2c3e9b0426/packages/navigator/src/browser/navigator-frontend-module.ts#L55-L59
> 
> and then everything should work

What will be fixed or work if we set the caption at this point?
I still see that individual views part of the explorer do not have captions for their parent items (ex: `TREE-VIEW-SAMPLE` or `JSON Outline`)

**Comment by akosyakov** [comment]
@vince-fugnitto you are right, we should set `caption` on the navigator widget: https://github.com/theia-ide/theia/blob/a878bbfe0085393bac144995788cac8f25a6e64a/packages/core/src/browser/view-container.ts#L211

There is be a bug in the view part that we only display title label ignoring the caption: https://github.com/theia-ide/theia/blob/a878bbfe0085393bac144995788cac8f25a6e64a/packages/core/src/browser/view-container.ts#L846-L850

I think if we should use the caption here as well as a caption for the view part header.

**Comment by vince-fugnitto** [comment]
I've updated the code to also support captions for view-containers.
Testing with the `explorer` and `debug` widgets I can see the following:

d
e

**Comment by vince-fugnitto** [comment]
@akosyakov should I let it sit for a day? :)

**Comment by akosyakov** [comment]
@vince-fugnitto we have not agreed on such things and did not document it anywhere, so no for now :) and with current review activity, doubt that someone else will have a look

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto we have not agreed on such things and did not document it anywhere, so no for now :) and with current review activity, doubt that someone else will have a look

Okay sounds good, thank you for the help and review I appreciate it! :)

**Pull request merged**
