### PR TITLE
always show debug icon on first start

### PR DESCRIPTION
**Pull request by amiramw**
Align with vscode behavior.
See discussion: https://spectrum.chat/theia/dev/debug-icon-appearance~a321c3d1-11f4-45ec-a5ed-2d5e1ba2b714

Signed-off-by: Amiram Wingarten <amiram.wingarten@sap.com>

### CODE REVIEW

**Comment by amiramw** [comment]
I'm getting this error in the build:
```
Error: Cannot find the log file for the Electron codecs test.
    at main (/Users/travis/build/theia-ide/theia/scripts/post-install.js:30:15)
    at Object.<anonymous> (/Users/travis/build/theia-ide/theia/scripts/post-install.js:34:1)
```
Anyone has any clue?

**Comment by kittaakos** [comment]
> Anyone has any clue?

CC: @marechal-p

**Comment by vince-fugnitto** [comment]
@amiramw can you rebase your PR on master, hopefully it's fixed by #5587

**Comment by amiramw** [comment]
now appveyor fail with unrelated error...

**Comment by vince-fugnitto** [comment]
@amiramw I'm just curious, initially we had your change, but then it was updated to the following https://github.com/theia-ide/theia/pull/3384/commits/c52e20f946f6145b8483ef5265122b54b7f1f00b. It looks like the PR intended to only show the `debug` view if there were currently supported debug configurations. Perhaps we should check thoroughly why the change was needed before we revert to the original design.

**Comment by amiramw** [comment]
@akosyakov could you  advise maybe why was this check added and whether it is ok not to have it? In vscode the debug icon is visible even though there are not configurations.

**Comment by akosyakov** [comment]
We don't want to confuse a user that debugging is supported if there is no debug adapter available for his project, i.e. debug extension is installed, but no concrete debuggers. I'm not sure how to go about it. Maybe it would be better never show it by default, but concrete IDEs can enable it. cc @svenefftinge

**Comment by akosyakov** [comment]
@svenefftinge Could we just enable it always?

**Comment by svenefftinge** [comment]
Yes, I think we can align it now, given that our vs code extension support has been improved a lot lately.

**Pull request merged**
