### PR TITLE
upgrade to latest Monaco

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by akosyakov** [comment]
Please review. @AlexTugarev `shift+R` seems to work without workaround now. I've tested with TS.

**Comment by AlexTugarev** [comment]
@akosyakov in that case, could you please add a reverse commit of https://github.com/theia-ide/theia/pull/1879/commits/d031e69f582b87df86a2b0691de1a8c14c92984f.

**Comment by akosyakov** [comment]
@AlexTugarev ok, reverted via git

**Comment by simark** [comment]
One thing we are missing in the monaco we use right now is markdown/html support in hovers.  Do you know if this update will bring that?

**Comment by akosyakov** [comment]
@simark I'm not sure, on the first glance it looks like we convert all kind of hovers sent by LSP to Monaco: https://github.com/TypeFox/monaco-languageclient/blob/e2b66a4ba5a0c1a993b18437d8103d7f5d58d3db/src/monaco-converter.ts#L571-L584

Could you try, please?

**Comment by simark** [comment]
I will try eventually, it is on my low-prio todo list :)

**Comment by akosyakov** [comment]
@simark it was a good call, turned out that a lot of conversions are outdated, including one for `MarkdownContent` was bogus: https://github.com/TypeFox/monaco-languageclient/pull/100/files#diff-2f3134371c3b4a7583daa0adab8fb0f2

**Comment by akosyakov** [comment]
I would like to merge it if nobody objects? Could someone review and approve?

**Comment by svenefftinge** [comment]
Reviewing it now

**Pull request merged**
