### PR TITLE
Detect type of archive based on header

### PR DESCRIPTION
**Pull request by stereobooster**
Detect type of downloaded VSCode extensions based on HTTP header. Fix for issue mentioned in https://github.com/theia-ide/theia-apps/pull/177#issuecomment-490984126

### CODE REVIEW

**Comment by akosyakov** [comment]
@stereobooster You should not use urls like ´https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publishers/alanz/vsextensions/vscode-hie-server/0.0.27/vspackage` but use a direct url like: 
`https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

**Comment by stereobooster** [comment]
Yes sure. Can you instruct me how to get direct url? I tried to find it in and had no luck

**Comment by akosyakov** [comment]
replace `${publisher}`, `${name}` and `${version}` with values for your extension in `https://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage`

**Comment by stereobooster** [comment]
👌

**Pull request closed without merging**
