### PR TITLE
GH-568: Bumped up Yarn version from 1.0.2 to 1.2.1.

### LINKED ISSUE #568: Yarn 1.1 and tslint update causing linting errors
I tracked this down to the whilespace   "check-separator", rule.

I'm not sure yet about the relationship between tslint and yarn.

tslint was also updated recently by 3b4276a626cae078cd2a3d35103573ba88946843

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #568.

Signed-off-by: Akos Kitta <kittaakos@gmail.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
@akosyakov, @hexa00, please review ASAP, otherwise we cannot proceed with other PRs due to the broken Windows build. Thank you!

**Comment by hexa00** [comment]
Could you add maybe in the doc a comment about: https://github.com/yarnpkg/yarn/issues/4695

The user will see errors while building with 1.2.1, maybe point to the issue and say we can ignore those errors?

otherwise LGTM. thx

**Comment by kittaakos** [comment]
> Could you add maybe in the doc a comment about: yarnpkg/yarn#4695

Please link the desired location, I'll add it. Thanks!

**Comment by hexa00** [comment]
I did provide the link already ? :) https://github.com/yarnpkg/yarn/issues/4695

**Comment by kittaakos** [comment]
> I did provide the link already ? :) yarnpkg/yarn#4695

:) OK, but where should I put this in our documentation. Did I misunderstand you?

**Comment by hexa00** [comment]
In Troubleshooting I think would be ok with like:

With yarn 1.2.1 you will see these errors...

Don't worry about it.

**Comment by kittaakos** [comment]
Cheers!

**Pull request merged**
