### PR TITLE
Remove unused wdio config in electron

### PR DESCRIPTION
**Pull request by epatpol**
Signed-off-by: Patrick-Jeffrey Pollo Guilbert <patrick.pollo.guilbert@ericsson.com>

### CODE REVIEW

**Comment by epatpol** [comment]
@kittaakos Is there a reason why the examples/electron folder have a wdio config? Calling `yarn run test` in turn calls `yarn test:electron` which calls `yarn run test \"@theia/example-electron\", and this only runs the electron-mocha test to make sure that the electron app actually runs. Looking at the commit history it seems this might have been a mistake copying those files from the examples/browser folder. Or correct me if I'm wrong! Anyway, if indeed those files aren't used I suggest removing them from the examples.

**Comment by hexa00** [comment]
It's quite possible that they are not used and can be removed.

**Comment by akosyakov** [comment]
@epatpol are you going to merge it?

**Comment by epatpol** [comment]
My bad, thanks for merging it!

**Pull request merged**
