### PR TITLE
Shrinkwrap theia-core and the examples

### PR DESCRIPTION
**Pull request by hexa00**
Signed-off-by: Antoine Tremblay <antoine.tremblay@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
It does not look like what we want:
- theia-core can still be broken
- examples use the published version of theia-core

**Comment by kittaakos** [comment]
Also, we still have the types for `express-serve-static-core`. That should not be there when the versions are fixed and it works correctly.

**Comment by hexa00** [comment]
How can theia-core can still be broken ?

They used the published version because of depencencies "theia-core: latest" ? 

Usually this gets overwritten by localDependencies?

**Comment by akosyakov** [comment]
sorry, the second assumption is wrong, examples are built againg locally packaged version of theia-core, will see how the build goes

**Comment by hexa00** [comment]
And for the 1st problem ? how can theia-core break?

**Comment by hexa00** [comment]
@kittaakos yeah the thing is I need to install to be able to shrinkwrap it ... so it needs to be something that works now...

**Comment by akosyakov** [comment]
@hexa00  you are right, i have not noticed the last file

**Comment by hexa00** [comment]
OK :)

**Comment by kittaakos** [comment]
> yeah the thing is I need to install to be able to shrinkwrap it ... so it needs to be something that works now...

That is true. Please create a ticket, associate your PR with that task. And then reference #231 too. Once the real problem (described in #231) is solved, we can get rid of the dependency.

In general, I would not create a PR without a task/issue otherwise no one can keep track of them.

**Comment by hexa00** [comment]
This PR is covered by #173  I'll update that issue to reference #231 too

**Comment by hexa00** [comment]
Actually I think it should just be part of #231 to update the shrinkwrap, it will be now part of the workflow the moment you touch package.json to update that

**Pull request merged**
