### PR TITLE
Changed `Modifier` to `KeyModifier` and each enum member to its key

### PR DESCRIPTION
**Pull request by WKnight02**
This is my attempt at "fixing" #458

### CODE REVIEW

**Comment by WKnight02** [comment]
Hm.

Learning how to pull-request the hard way I guess, my bad.

Basically tried to get a bit familiar with the project by looking into issue #458.

**Comment by akosyakov** [comment]
Hi @WKnight02, thanks for the PR, you should squash all commits in one and sign it, look at the interactive rebase.

**Comment by WKnight02** [comment]
Should I do everything in a separate branch in my fork too ?

I feel like every commit that I will do on master will now end up in this PR...

Should I close this PR and re-make a proper one ?

**Comment by akosyakov** [comment]
This PR is fine. A PR is a diff between 2 branches, to add new changes you just push to your branch.

**Comment by akosyakov** [comment]
To sign the last commit `git commit --amend -s`. To remove commits you should use git interactive rebase or git hard reset.

**Comment by WKnight02** [comment]
Thank you, I will look into it now.

**Pull request closed without merging**
