### PR TITLE
Fix preference server watching the same file multiple times

### LINKED ISSUE #748: Settings files are watched several more times on startup (3 times more than they should)
i.e when you start the example:

```
Starting watching: [ '/home/epatpol/Projects/Github/theia/examples/browser/package.json' ]

Starting watching: [ '/home/epatpol/.theia/settings.json' ]

Starting watching: [ '/.theia/settings.json' ]
The express server worker 1 is ready to accept messages.

Started watching: [ '/home/epatpol/Projects/Github/theia/examples/browser/package.json' ]

Started watching: [ '/home/epatpol/.theia/settings.json' ]

Started watching: [ '/.theia/settings.json' ]

[2017-10-26T16:02:59.330Z]  INFO: Theia/23422 on elxag2w8q32: Theia app listening on http://localhost:3000. []

Starting watching: [ '/home/epatpol/.theia/settings.json' ]

Starting watching: [ '/.theia/settings.json' ]

Started watching: [ '/home/epatpol/.theia/settings.json' ]

Started watching: [ '/.theia/settings.json' ]

Starting watching: [ '/home/epatpol/.theia/settings.json' ]

Starting watching: [ '/.theia/settings.json' ]

 Started watching: [ '/home/epatpol/.theia/settings.json' ]

Started watching: [ '/.theia/settings.json' ]
```

### PR DESCRIPTION
**Pull request by epatpol**
Closes #748

Signed-off-by: Patrick-Jeffrey Pollo Guilbert <patrick.pollo.guilbert@ericsson.com>

### CODE REVIEW

**Comment by epatpol** [comment]
This doesn't address #749.

**Comment by akosyakov** [comment]
How should it work with 2 workspaces?

**Comment by akosyakov** [comment]
I think it should be handled after https://github.com/theia-ide/theia/issues/772.

**Comment by epatpol** [comment]
I'm fine with this!

**Pull request closed without merging**
