### PR TITLE
[textmate] fix #2354: remove html grammar overriding by java

### LINKED ISSUE #2354: Missing HTML Syntax Highlighting
prior to #2306 - HTML seems to have missing Syntax Highlighting.

image

JSON Manifest for my app 
```json

{
    "private": true,
    "dependencies": {
       "@theia/core": "next",
       "@theia/filesystem": "next",
       "@theia/workspace": "next",
       "@theia/preferences": "next",
       "@theia/navigator": "next",
       "@theia/process": "next",
       "@theia/terminal": "next",
       "@theia/file-search": "next",
       "@theia/messages": "next",
       "@theia/git": "next",
       "@theia/editor": "next",
       "@theia/languages": "next",
       "@theia/markers": "next",
       "@theia/monaco": "next",
       "@theia/typescript": "next",
       "@theia/json": "next",
       "@theia/textmate-grammars": "next",
       "@theia/java" : "next",
       "@theia/cpp": "next"
    },
    "devDependencies": {
        "@theia/cli": "next"
    },
    "theia": {
        "target": "browser"
    }
}
```

### PR DESCRIPTION
**Pull request by akosyakov**
See https://github.com/theia-ide/theia/issues/2354#issuecomment-405046272 for explanation.

### CODE REVIEW

**Comment by akosyakov** [comment]
It is still broken :(
to reproduce in Theia repo with browser example:
```
{
  "private": true,
  "name": "@theia/example-browser",
  "version": "0.3.12",
  "dependencies": {
    "@theia/callhierarchy": "^0.3.12",
    "@theia/core": "^0.3.12",
    "@theia/editor": "^0.3.12",
    "@theia/editorconfig": "^0.3.12",
    "@theia/extension-manager": "^0.3.12",
    "@theia/file-search": "^0.3.12",
    "@theia/filesystem": "^0.3.12",
    "@theia/git": "^0.3.12",
    "@theia/keymaps": "^0.3.12",
    "@theia/languages": "^0.3.12",
    "@theia/markers": "^0.3.12",
    "@theia/merge-conflicts": "^0.3.12",
    "@theia/messages": "^0.3.12",
    "@theia/metrics": "^0.3.12",
    "@theia/mini-browser": "^0.3.12",
    "@theia/monaco": "^0.3.12",
    "@theia/navigator": "^0.3.12",
    "@theia/outline-view": "^0.3.12",
    "@theia/output": "^0.3.12",
    "@theia/plugin-ext": "^0.3.12",
    "@theia/plugin-ext-vscode": "^0.3.12",
    "@theia/preferences": "^0.3.12",
    "@theia/preview": "^0.3.12",
    "@theia/process": "^0.3.12",
    "@theia/search-in-workspace": "^0.3.12",
    "@theia/task": "^0.3.12",
    "@theia/terminal": "^0.3.12",
    "@theia/typescript": "^0.3.12",
    "@theia/textmate-grammars": "^0.3.12",
    "@theia/java": "^0.3.12",
    "@theia/cpp": "^0.3.12",
    "@theia/userstorage": "^0.3.12",
    "@theia/variable-resolver": "^0.3.12",
    "@theia/workspace": "^0.3.12"
  },
  "scripts": {
    "prepare": "yarn run clean && yarn build",
    "clean": "theia clean && rimraf errorShots",
    "build": "theia build --mode development",
    "watch": "yarn build --watch",
    "start": "theia start",
    "start:debug": "yarn start --log-level=debug",
    "test": "wdio",
    "coverage:compile": "yarn build --config coverage-webpack.config.js",
    "coverage:remap": "remap-istanbul -i coverage/coverage.json -o coverage/coverage-final.json --exclude 'frontend/index.js' && rimraf coverage/coverage.json",
    "coverage:report:html": "istanbul report --root coverage --format html",
    "coverage:report:lcov": "istanbul report --root coverage --format lcov",
    "coverage": "yarn coverage:compile && yarn test && yarn coverage:remap && yarn coverage:report:lcov && yarn coverage:report:html"
  },
  "devDependencies": {
    "@theia/cli": "^0.3.12"
  }
}
```

I will continue looking into it.

**Comment by akosyakov** [comment]
Please review again, turned out that java extension were overriding grammars for html scope.

**Comment by AlexTugarev** [comment]
@akosyakov, what was the broken use case? open java file first, then html?

I'm retesting...

**Comment by akosyakov** [comment]
@AlexTugarev you have to change the order of extension, java after textmate-grammars, then java will override html grammar

**Pull request merged**
