### PR TITLE
Decouple language and grammar contributions for typescript 

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

To use VS Code typescript extension [1] & [2] I have to cut off typescript extension from Theia IDE and this leads to turning of syntax highlighting as well. That's why it is needed to move ts/js grammar contribution to another package.

### What does this PR do
PR decouple typescript language and grammar contribution. 

[1] https://github.com/eclipse/che-plugin-registry/blob/master/plugins/ms-vscode.typescript/1.30.2/meta.yaml
[2] https://github.com/che-incubator/ms-code.typescript

### CODE REVIEW

**Comment by marechal-p** [comment]
I was having troubles understanding why the Typescript VS Code extension was not adding grammars, but IIUC the syntax highlighting comes from the VS Code builtin extension, and not from `ms-vscode.typescript` ?

**Comment by tolusha** [comment]
There is no typescript extension on the marketplace [1]. To have it I need to make it manually [2]. It is based on `typescript-language-features` package [3]. The final bundle that I provide [4] doesn't contain syntax highlighting which locates in `typescript-basics` package [5].

[1] https://marketplace.visualstudio.com/VSCode
[2] https://github.com/che-incubator/ms-code.typescript
[3] https://github.com/Microsoft/vscode/tree/master/extensions/typescript-language-features
[4] https://github.com/che-incubator/ms-code.typescript/releases/download/v1.30.2/che-typescript-language.vsix
[5] https://github.com/Microsoft/vscode/tree/master/extensions/typescript-basics

**Comment by marechal-p** [comment]
Ok thank you for the explanation, so if I still understand correctly: you only provide a Theia plugin based on VS Code's `typescript-language-feature` extension, but not `typescript-basics` yet? Although down the road we would be using the latter as well, right?

**Comment by marechal-p** [comment]
Otherwise LGTM, will wait if anyone else want to have a look :)

**Comment by tolusha** [comment]
> Theia plugin based on VS Code's `typescript-language-feature` extension, but not `typescript-basics` yet? 

yes, correct.

> Although down the road we would be using the latter as well, right?

`typescript-basics` package basically contains everything that I've decoupled and moved to `textmate-grammars`. So, I don't know if it is necessary to have a dedicated plugin for this.

**Comment by tolusha** [comment]
@benoitf 
We are not waiting for any CQ here. I've just moved some files from one package to another one.

**Pull request merged**
