### PR TITLE
fix #5827 node debug breakpoints moving

### LINKED ISSUE #5827: Sometimes breakpoint moves into another line after some time
### Reproduction Steps

This bug could be reproduced quite often, but not all the time.
A scenario how to reproduce:

1. Generate a simple backend plugin using `Yeoman wizard` command.
2. Set a breakpoint into default command handler
3. Run the plugin in debug mode (using hosted instance for example)
4. Wait until debugger connects and invoke command to hit the breakpoint
5. Go back to Che Theia
5. The breakpoint moves for a few lines on its own.

Note, debugger stops exactly in the place where breakpoint was set, but the breakpoint marker moves, which can bring confusion especially when a user has many breakpoints.

debugger-breakpoint-jump

**OS and Theia version:**
Theia 0.8.0 (2c7485f)

### PR DESCRIPTION
**Pull request by tom-shan**
Signed-off-by: tom-shan <swt0008411@163.com>

#### What it does

fix https://github.com/theia-ide/theia/issues/5827

#### How to test

1 clone theia plugin samples project and build hello-world-backend-plugin/
```
git clone https://github.com/eclipse/che-theia-samples.git
cd che-theia-samples/samples/hello-world-backend-plugin
yarn
cd ..
```
2 build theia's latest master 
```
git clone https://github.com/theia-ide/theia.git && cd theia
yarn
```
3 start theia browser example
```
cd examples/browser/ && yarn start
```
4 try to build `che-theia-samples/samples/hello-world-backend-plugin`, 
then add breakpoint at line **13** 
of `che-theia-samples/samples/hello-world-backend-plugin/src/hello-world-backend-plugin.ts` 
and start hosted debug mode. 
but the red dot will move to line **12**

image

5 modify packages/debug-nodejs/package.json like this PR
```
cd ../../
sed -i 's/node-debug\/1.29.2/node-debug\/1.35.3/g' packages/debug-nodejs/package.json
sed -i 's/node-debug2\/1.29.2/node-debug2\/1.33.0/g' packages/debug-nodejs/package.json
```
6 clean previous downloaded package and build again
```
cd packages/debug-nodejs/ 
rm -r download && yarn 
cd ../../examples/browser/ && yarn
```
7 try to add breakpoint and start hosted debug mode again,
at this time the red dot stay still on line **13**

image

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
@tom-shan please update the PR description:
- please reference relevant issues explaining why switch to a new version helps
- please explain a reviewer how to test changes

**Comment by kittaakos** [comment]
I am verifying this.

**Comment by kittaakos** [comment]
> clone theia plugin samples project and build hello-world-backend-plugin/
> 
> ```
> git clone https://github.com/eclipse/che-theia-samples.git
> cd che-theia-samples/samples/hello-world-backend-plugin
> ```

I could not verify it. I could not build the provided sample on Windows:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 /c/che-theia-samples (master)
$ git clean -ffxqd && git reset --hard && git rev-parse --short HEAD && cd samples/hello-world-backend-plugin/ && yarn
HEAD is now at 9d8160a add activation event to samples
9d8160a
yarn install v1.16.0
[1/5] Validating package.json...
warning @eclipse-che/hello-world-backend-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning "@theia/plugin-packager > glob-promise@3.4.0" has unmet peer dependency "glob@*".
[5/5] Building fresh packages...

$ yarn run clean && yarn run build
yarn run v1.16.0
warning @eclipse-che/hello-world-backend-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
$ rimraf lib
Done in 0.27s.
yarn run v1.16.0
warning @eclipse-che/hello-world-backend-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
$ yarn run format-code && yarn run compile && theia:plugin pack
warning @eclipse-che/hello-world-backend-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
$ tsfmt -r
replaced C:/che-theia-samples/samples/hello-world-backend-plugin/src/hello-world-backend-plugin.ts
warning @eclipse-che/hello-world-backend-plugin@0.0.1: The engine "theiaPlugin" appears to be invalid.
$ tsc
The filename, directory name, or volume label syntax is incorrect.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

kittaakos@DESKTOP-VJRAMKC MINGW64 /c/che-theia-samples/samples/hello-world-backend-plugin (master)
```

I thought the build issue is related to the long file paths on Windows, but it does not work from the `C:\` either:
```
warning: Could not stat path 'samples/code-lens-provider-plugin/node_modules/.cache/uglifyjs-webpack-plugin/content-v2/sha512/d8/ed/6d820e81d0f34471071855c5b4dd414747ceeaac31e05a30daa8f3fb07f5782737d1e7c9aa9c025a17ba19976ac273c371b84b0fe15b843d650b8e7f48f6': Filename too long
warning: Could not stat path 'samples/color-provider-plugin/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/47/2e/e5f1824c77ee5002ea1d7a78891f8e27059aab39f95d6c8bf870d272ecd477e88f3793913c91a8cd3da739cb535ea70e2a1f8f2dd9b40524a3c994b06ea9': Filename too long
```

**Comment by akosyakov** [comment]
@tolusha Have you managed to build and verity it? Please provide a comment what the approve means.

**Comment by tom-shan** [comment]
> I could not verify it. I could not build the provided sample on Windows:
How about use `yo @theia/plugin`(https://www.theia-ide.org/doc/authoring_plugins) to generate a new plugin on Windows?

**Comment by akosyakov** [comment]
I'm not sure that generator was tested before on Windows. Maybe @evidolob @benoitf can clarify it. If it is not used to work, then let's test this PR on linux and mac os, and open a new issue on the generator project to make it work on Windows.

**Comment by tolusha** [comment]
1. Run Theia from https://github.com/tom-shan/theia/tree/break-point-move
2. Cloned and built https://github.com/eclipse/che-theia-samples/tree/master/samples/hello-world-backend-plugin
3. Set breakpoint on line 13
4. Breakpoint doesn't move to line 12

**Comment by tom-shan** [comment]
> I don't think errors with che samples running on windows from sources are related. It would be good though to file an issue on the corresponding repo. @tom-shan Could you do it?

I'm pleased to file an issue.

**Comment by kittaakos** [comment]
> I'm pleased to file an issue.

Thanks for taking care of this, @tom-shan. I wanted to file an issue in the https://github.com/eclipse/che-theia-samples repository, but ...

Screen Shot 2019-08-07 at 11 32 18
Screen Shot 2019-08-07 at 11 32 25

Let me know if you cannot reproduce the build issue on Windows and I will update the ticket you have created. Thanks!

**Comment by tom-shan** [comment]
@kittaakos I made a reference to your [comment](https://github.com/theia-ide/theia/pull/5849#issuecomment-518151795) in issue (https://github.com/eclipse/che/issues/14145)

**Comment by akosyakov** [comment]
@kittaakos please merge if you are fine

**Comment by kittaakos** [comment]
> @kittaakos please merge if you are fine

I could not try it on Windows: https://github.com/theia-ide/theia/pull/5849#issuecomment-518151795

**Comment by akosyakov** [comment]
@kittaakos would it be fine to tackle windows issue for che sample repo separately? I saw similar issues on linux on completely unrelated repos. It would be good to fix it.

**Comment by kittaakos** [comment]
> would it be fine to tackle windows issue for che sample repo separately?

Sure.

> @kittaakos please merge if you are fine

But I cannot say it is fine, it did not work for me.

**Comment by tom-shan** [comment]
@kittaakos I created a new [theia plugin sample repo](https://github.com/tom-shan/theia-plugin-hello-world) which I have tested on ubuntu, please use this repo and have another try on windows.

**Comment by akosyakov** [comment]
@kittaakos Could you try with @tom-shan extension when you have a chance, please?

**Comment by akosyakov** [comment]
@westbury I know that you have access to Windows machine, may I ask you to review this PR as  @tom-shan suggested in https://github.com/theia-ide/theia/pull/5849#issuecomment-519548446?

**Comment by westbury** [comment]
I've tried this on Windows but I can't reproduce the problem without the change.  Can you share the launch configuration you are using?

**Comment by akosyakov** [comment]
@westbury it should be explained in `How to test` section of this PR or in https://github.com/theia-ide/theia/issues/5827 desc. If not @tom-shan could you help

**Comment by tom-shan** [comment]
> I've tried this on Windows but I can't reproduce the problem without the change. Can you share the launch configuration you are using?

There is no `launch.json` in `.theia` and only have a `settings.json` which is very simple and is pasted below.
```
{
   "typescript.tsdk": "node_modules/typescript/lib"
}
````
BTW, this issue still exist in ubuntu with the latest master branch.

**Comment by tom-shan** [comment]
@westbury You can press F1 then choose `Hosted mode: start instance` to debug the repo of https://github.com/tom-shan/theia-plugin-hello-world and no need to use the `launch.json`.

**Comment by westbury** [comment]
@tom-shan Thanks for confirming how you are starting the hosting mode.  Sorry, it was probably obvious to everyone else but I have not looked at plugins before.

When I try this on Windows, on master, immediately after a reboot, with your theia plugin sample repo, I get this when I select 'Hosted Plugin: Debug Instance':

image

followed finally with:
image

When I do exactly the same steps on Ubuntu it performs as you described, with the breakpoint moving from line 13 to line 12 but with execution stopping on line 13.

**Comment by tom-shan** [comment]
@westbury Thanks for your reply. 
I have a similar error in my win10 machine and I think this error may be related to the weired file path of `/d%3A/theia/theia-plugin-hello-world\package.json` which can not be parsed successfully by https://github.com/theia-ide/theia/blob/master/packages/plugin-dev/src/node/hosted-plugins-manager.ts#L123-L133 .

my console error logs:
```
root ERROR Request runWatchCompilation failed with error: Watch script doesn't exist in /d%3A/theia/theia-plugin-hello-world\package.json Error: Watch script doesn't exist in /d%3A/theia/theia-plugin-hello-world\package.json
    at HostedPluginsManagerImpl.runWatchCompilation (D:\theia\theia-breakpoint\packages\plugin-dev\lib\node\hosted-plugins-manager.js:48:19)
    at HostedPluginServerImpl.runWatchCompilation (D:\theia\theia-breakpoint\packages\plugin-dev\lib\node\hosted-plugin-service.js:125:42)
    at JsonRpcProxyFactory.<anonymous> (D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:217:73)
    at step (D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:47:23)
    at Object.next (D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:28:53)
    at D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:18:12)
    at JsonRpcProxyFactory.onRequest (D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:211:16)
    at D:\theia\theia-breakpoint\packages\core\lib\common\messaging\proxy-factory.js:174:48
```

**Comment by westbury** [comment]
> this error may be related to the weired file path

Thanks for the info.  There is a weird file path on Windows which can cause problems and confusion, though usually it is "\c:\...".  I will see if I can hack around the problem so I can validate this PR on Windows.

**Comment by westbury** [comment]
I don't think this plugin hosting code has ever worked on Windows.  The getFsPath function has multiple problems.  I have pushed a couple of commits to https://github.com/westbury/theia/tree/windows-fixes .  The first removes the getFsPath function (FileUri.fsPath does the same except it also works on Windows).  The second commit is required to get the spawn to work on Windows, but this is a workaround (hence why I did not sign it).

With these changes the plugin hosting works.  However I saw different behavior.  Instead of the breakpoint moving, it showed as unbound and it did not stop on the breakpoint.  As soon as I select another breakpoint, the first breakpoint shows as bound.  So not what we are seeing on Linux.  Also this behavior is the same with and without the version changes made in this PR.

As this PR does not make things worse on Windows I see no reason why it should not be merged (as far as Windows testing is concerned).  The break-point behavior I saw could require significant time to investigate.  I can put in a separate PR for my Windows fixes.

**Comment by akosyakov** [comment]
I'm just for merging it. I don't think it breaks and it fixes issues on Ubuntu. If someone wants to make the plugin hoisting to work on Windows, then let's to file an issues and address it separately.

**Pull request merged**
