### PR TITLE
Resize debug widget on debug panel

### PR DESCRIPTION
**Pull request by tolusha**
### What does PR do
* Every debug widget has its own scroll bar
* Debug widgets are resizeable

https://github.com/theia-ide/theia/issues/3377

screenshot from 2018-12-18 16-18-22

### CODE REVIEW

**Comment by svenefftinge** [comment]
Thank you! 
Do we have a ticket for collapsing `ViewContainer`s like in VS Code? 
Would be nice to have an easy way to minimize them.

The `.theia-header` style has a too high margin on the top. It should be only 5px.
Before:
screenshot 2018-12-19 at 08 52 09

After:
screenshot 2018-12-19 at 08 54 42

**Comment by tolusha** [comment]
@svenefftinge 
1. fixed margin
screenshot from 2018-12-19 10-46-08

2. ViewContainer can be minimized but a height of the widget in controlled by split panel. That's why it doesn't have any affect in this particular case.

**Comment by svenefftinge** [comment]
> ViewContainer can be minimized but a height of the widget in controlled by split panel. That's why it doesn't have any affect in this particular case.

I think it should be supported eventually. Do we have a ticket to at least track this for now?

**Comment by tolusha** [comment]
Here is https://github.com/theia-ide/theia/issues/3860

**Pull request merged**
