### PR TITLE
Added tabindex to git widget

### PR DESCRIPTION
**Pull request by jbicker**
Fixes theia-ide/theia#2626

Signed-off-by: Jan Bicker <jan.bicker@typefox.io>

### CODE REVIEW

**Comment by AlexTugarev** [comment]
'testing right now.

**Comment by AlexTugarev** [comment]
it's fixed for clicking into the empty area, but not for changed items.

**Comment by jbicker** [comment]
Yes. Because the diff widget gets the focus. As far as I remember it's on purpose. I've once filed an issue for having another behaviour here. https://github.com/theia-ide/theia/issues/1791

**Comment by AlexTugarev** [comment]
Well, in that case I'll better commend the other issue, as it's inconsistent with SiW selection.

**Pull request merged**
