### PR TITLE
[plug-in] Fix webview resize

### PR DESCRIPTION
**Pull request by evidolob**
This pull fixed webview resize issue, when user try to resize webview widget with split panel.
Pull reuse approach and `MiniBrowserMouseClickTracker` class to provide fix.

Original issue: https://github.com/eclipse/che-theia/issues/151

### CODE REVIEW

**Comment by akosyakov** [comment]
It would be good to move it to core and rename to something like `ApplicationShellMouseTracker`.

**Comment by akosyakov** [comment]
@olexii4 What your approve? Did you test how good it works when mini-browser and webview are present together? Since we hijack mini browser functionality we need to test it as well.

**Comment by akosyakov** [comment]
It also seems to fix https://github.com/theia-ide/theia/issues/4823. Could someone double check? @olexii4

**Comment by evidolob** [comment]
@akosyakov OK, I can do refactoring and rename/move `MiniBrowserMouseClickTracker` as `ApplicationShellMouseTracker ` to core, in this pull.

**Comment by evidolob** [comment]
@akosyakov `application-shell.ts` is quite big, are you ok to  have `ApplicationShellMouseTracker` in separate file: `application-shell-mouse-tracker.ts` or `shell-mouse-tracker.ts`?

**Comment by akosyakov** [comment]
@evidolob yes, having a separate file for classes is good, application-shell-mouse-tracker.ts sounds good

**Pull request merged**
