### PR TITLE
Long names in tree node don’t get wrapped anymore

### LINKED ISSUE #870: open dialog: long names are formatted strangely
I find it strange that when a directory name is cut because it's too long, the remaining part is shown centered instead of left-justified.

image

The long filenames in question:
``` bash
drwx------  3 root root     4096 Nov 22 05:16 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-colord.service-fTR5ev/
drwx------  3 root root     4096 Nov 22 05:16 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-rtkit-daemon.service-ofQcVk/
drwx------  3 root root     4096 Nov 22 05:14 systemd-private-136bdce8f99b4741aad6e2c7b2f7249e-systemd-timesyncd.service-RWr33S/
```

### PR DESCRIPTION
**Pull request by jbicker**
Fixes #870 .

### CODE REVIEW

**Comment by kittaakos** [comment]
@jbicker, once you have fixed the CIs, I verify your changes.

**Comment by svenefftinge** [comment]
It was not because if this change, but because the CI ran while I was publishing new releases to npm. The extension tests don't seem to like that.

**Comment by kittaakos** [comment]
I am verifying it now on Windows...

**Comment by kittaakos** [comment]
Before:
screen shot 2017-12-04 at 10 54 42

After:
screen shot 2017-12-04 at 11 04 13

**Pull request merged**
