### PR TITLE
Add MS Debug Adapter as a jdt.ls extension

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>
Add a script to download Microsoft debug adapter and contribute it into jdt.ls.

Related issue: https://github.com/theia-ide/theia/issues/3058

### CODE REVIEW

**Comment by akosyakov** [comment]
Should not there be a separate debug extension?

//cc @svenefftinge

**Comment by tsmaeder** [comment]
> Should not there be a separate debug extension?


We have thought about this and haven't come up with a good reason.

**Comment by tsmaeder** [comment]
We currently have the module debug-nodejs for nodejs debugging, if this is the way to go, we'll have python-debug, as well. I'm fine to go this way, but is there a reason we're not contributing java debug support in the /java module?

**Comment by akosyakov** [comment]
@tsmaeder that existing clients (products) don't get affected and does not pull debug extensions through it

**Comment by svenefftinge** [comment]
One could argue that the debug support is not for Java but for the JVM. So other JVM languages would benefit from the jvm debug support, too. OTOH there are other platforms for Java that might need different debug support (e.g. GraalVM).

**Comment by tsmaeder** [comment]
@svenefftinge @akosyakov fair enough.

**Comment by svor** [comment]
@akosyakov @svenefftinge @tsmaeder made it as a separate extension, please have a look at it

**Comment by svenefftinge** [comment]
I tried opening with https://github.com/Microsoft/java-debug, but it doesn't recognize the debug type.
Also this extension doesn't contribute any snippets, so how can I test it?

**Comment by svor** [comment]
@akosyakov yes, it was. This PR is as a first step to create an extension based on https://github.com/Microsoft/vscode-java-debug. It just adds some custom commands to jdt.ls wich are used in vscode-java-debug.
@svenefftinge I don't think that we can totally reuse vscode-java-debug. Java-debug VS Code extension is using Redhat java vscode extension

**Comment by akosyakov** [comment]
@svor ok, we will do the same as with nodejs debugger, reuse as much as possible and rewrite `JavaDebugConfigurationProvider`

**Comment by akosyakov** [comment]
Here is a PR: https://github.com/theia-ide/theia/pull/3613 

It already reuses launch configurations, will reimplement `JavaDebugConfigurationProvider` next week.

**Comment by svor** [comment]
It has already done in https://github.com/theia-ide/theia/pull/3613

**Pull request closed without merging**
