### PR TITLE
Enable semicolon tslint rule

### PR DESCRIPTION
**Pull request by simark**
We currently have inconsistent use of semicolon, fix it and enable the
linter rule.  Also, I don't see why we shouldn't enforce the use of
semicolons in interfaces, since it will just lead to more inconsistency,
so I removed that part of the rule.

### CODE REVIEW

**Comment by akosyakov** [comment]
Ideally we won’t use semi colons, only missing semicolons in expressions can cause problems, in interfaces they are meaningless

**Comment by simark** [comment]
Is it possible to say that there should never be semicolons in interfaces (to make it an error if there are)?  I just don't want to end up with different styles and wonder what I should use.

**Comment by akosyakov** [comment]
Why is it important? It does not prevent any programming errors and introduce linting noise.

**Comment by simark** [comment]
For interfaces, indeed.

For code, vscode already shows a warning when the semicolon is missing, so I wanted to remove them and make sure they don't reappear.

**Comment by akosyakov** [comment]
For code +1

**Comment by simark** [comment]
I changed it to remove the requirement of semicolons in interfaces.

**Comment by akosyakov** [comment]
I am not sure about running in on the cli as errors, even in code it is rare case that missing semicolons break anything. I afraid in practice it will more annoy people by breakin builds. We had it with missing spaces in comments.

**Comment by hexa00** [comment]
It's more about having a consistent code base than preventing errors IMO.

Also the way it is now... we add semi columns we see missing a bit randomly as we work and this makes our PRs touch unrelated code quite often which is quite annoying when reviewing.

Might as well just have 1 way to write the code and stick to it.

**Comment by akosyakov** [comment]
I am ok to have warnings in the editor and fix them with this PR. I think most of us fix it and they won’t pop up.
I am not ok with discovering after debugging that my change is not in a place because of failing linting rules which only make code look better. I think it is enough to run them in the editor.

**Comment by simark** [comment]
Well, if we treat it as an error from the start, your editor will show it as an error as soon as you type it, so you won't be able to forget it.

**Comment by lmcbout** [comment]
+1, I think it will standardise the code for all developers

**Comment by akosyakov** [comment]
ok, let's give it a try

**Pull request merged**
