### PR TITLE
Compute dirty diff without copying data.

### LINKED ISSUE #1471: Avoid `split` of document content
Split lines is quite expensive as it's done in `merge-conflicts` and `git/dirty-diff`, cf. 

screen shot 2018-03-09 at 12 31 27

cc. @akosyakov

### PR DESCRIPTION
**Pull request by AlexTugarev**
This should improve the performance of dirty diff computation (a lot!) Especially the editing experience with regular sized files should not suffer with this change set.

For large files (+1000L) I'd like to disable that feature, because even if we shave off the unnecessary overhead, the computational complexity still remains [O(ND)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.4.6927&rep=rep1&type=pdf). The limit of lines should be configurable, with a reasonable default.

Changes:

* uses `TextEditorDocument.getLineContent` to access lines of editor
* uses lineStart-based access for git resource contents
* uses eventually consistent diff computation based on non-copying line access
* throttles document change events
* throttles git change events
* delays computation and updates

Closes #1471

### CODE REVIEW

**Comment by AlexTugarev** [comment]
I've added the mentioned limit of lines for contents in editor and git resource. Otherwise usually large files like `yarn.lock` from theia repo are not able to open in worst case (which means having a total range change.)

**Comment by AlexTugarev** [comment]
I think the appveyor error is unrelated to this.

**Comment by svenefftinge** [comment]
I think the limit of 1000 is a fair choice, as it starts to become a bit sluggish around that size. 
I couldn't however change the limit through the settings as changes were not picked up. Could you check why that is?

**Comment by AlexTugarev** [comment]
> Could you check why that is? 

Sure. I'll look into that.

**Comment by AlexTugarev** [comment]
I see, only git events and document content change events are triggering updates.

**Comment by AlexTugarev** [comment]
@svenefftinge, changes of `linesLimit` preference will trigger updates now, like this:

**Comment by AlexTugarev** [comment]
Currently updating the branch.

**Pull request merged**
