### PR TITLE
Add Junit reporters to tests

### PR DESCRIPTION
**Pull request by MarkZ3**
Signed-off-by: Marc-Andre Laperle <marc-andre.laperle@ericsson.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Did you miss the [`mocha.opts`](https://github.com/theia-ide/theia/blob/aef8737c78bc499ae156e9837895ef7b0d0b4e04/configs/mocha.opts#L3) file on purpose? I can see you've added the reporter to the npm task but why not to the config file?

**Comment by MarkZ3** [comment]
@kittaakos Sorry I didn't know about mocha.opts. I'll look into it.

**Comment by marcdumais-work** [comment]
@MarkZ3 just to check if this PR has "fallen into a crack" ?

**Comment by MarkZ3** [comment]
I noticed that this shuts off the "spec" reporter, so it's not good. There is also "mocha-multi-reporters" but it also needs another config file. It's probably not worth all of this so I'll just close this.

**Pull request closed without merging**
