### PR TITLE
non-blocking upload API (streaming small chunks over WS)

### LINKED ISSUE #969: Drag & Drop large file not copied when the file exceed 60M
Drag & Drop large file. Follow up on issue #868 
Tried on Chrome and Firefox: was able to transfer file 60M and the md5sum is ok, but when I try to drag a file of 80M, the browser stops with the following error:
main.js:816 Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (main.js:816)
    at connection.ts:14
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at closeHandler (main.js:212)
    at CallbackList.invoke (events.js:71)
    at Emitter.fire (events.js:135)
    at WebSocketMessageReader.AbstractMessageReader.fireClose (messageReader.js:126)
    at WebSocketMessageReader.fireClose (reader.ts:72)
    at reader.ts:31

### LINKED ISSUE #4732: investigate how to use formidable to rewrite drag and drop upload in the navigator
A follow-up of https://github.com/theia-ide/theia/pull/4717
Also should resolve https://github.com/theia-ide/theia/issues/969

### LINKED ISSUE #4923: [quality] Move the upload service and its functionality to its own module
`packages/filesystem/src/browser/download/file-download-service.ts` should be responsible for the download only, as its name suggests.

Move the upload functionality to its own module.

### PR DESCRIPTION
**Pull request by akosyakov**
Upload via streaming small chunks over the web-socket.

- closes #5086 (superseded) - see https://github.com/theia-ide/theia/pull/5086#issuecomment-491733399
- fix #4732 - one should be able to upload files via drag and drop without blocking UI and crashing the browser with out-of-memory.
- fix #4923 - extract upload to own service
- fix #969 - uploading limitless amount of data is possible

It's breaking to redesign APIs. I've updated CHANGELOG with a record for it.

### CODE REVIEW

**Comment by akosyakov** [comment]
@AlexTugarev @geropl @elaihau @lmcbout could you try this PR instead?

**Comment by lmcbout** [comment]
@akosyakov  I started to test this PR. I Drag & Drop a 120 Meg file and it went ok
I Drag & Drop the "Theia" project and its completed the transfer.
Some observation:
- When I selected Theia and Drop it to the workspace folder, the front-end went "OFFline" when it started
- The browser froze for about ~20 sec, then it started to respond again
- Transferring Theia onto the workspace took ~ 8 minutes
This is my initial observation about this PR, I continue testing it.

**Comment by akosyakov** [comment]
Upload happens in 2 phases indexing files and streaming them. Indexing happens synchronously. 

@lmcbout Do you get `Offline` and 20 sec at the beginning? I could try to break indexing with `setImmediate` that UI gets a bit more responsive. My machine seems to be fast enough to make blocking during indexing invisible.

> Transferring Theia onto the workspace took ~ 8 minutes

Does it feel to slow? Or reasonable. The issue is that upload share web socket connection with other UI operations. More UI operations you do slower it is. I could try to have a temporary dedicated web socket for it. Not sure though there it is going to help.

**Comment by lmcbout** [comment]
@akosyakov I think it the browser was not going offline, the initial settings for indexing would be fine.So setImmediate could solve it.

Transferring Theia to workspace ~ 8 minutes.
I understand there are many files to transfer, but I find it slow even if the browser does not freeze.
[Suggestion] I am wondering, when indexing the files to transfer, if there are many files, would it be possible to compress it?, may be it could improve the transfer time

**Comment by akosyakov** [comment]
> I understand there are many files to transfer, but I find it slow even if the browser does not freeze.

Could you clarify against what you are comparing? What time would you expect?

**Comment by akosyakov** [comment]
@lmcbout I've reworked it to use a dedicated web socket. Could you please check how it affects upload speed for you?

**Comment by lmcbout** [comment]
@akosyakov  The last commit version (31ae348b2df) does not compile :(

**Comment by elaihau** [comment]
```
lerna ERR! [compile] src/node/filesystem-backend-contribution.ts(67,17): error TS2304: Cannot find name 'id'.
lerna ERR! [compile] src/node/filesystem-backend-contribution.ts(68,36): error TS2339: Property 'close' does not exist on type 'NodeFileUploadService'.
lerna ERR! [compile] src/node/filesystem-backend-contribution.ts(68,42): error TS2304: Cannot find name 'id'.
lerna ERR! [compile] theiaext compile exited with code 2

```

**Comment by akosyakov** [comment]
@lmcbout @elaihau sorry, i've pushed again

**Comment by lmcbout** [comment]
@akosyakov  It looks like the last commit ( 1e0ca1493369 ) is faster in indexing, but still takes time and we can see the "Offfline" on the status bar.  What is wrong with this version is the transfer of files, it does not transfer all the files, the progress  % is not updated either.
If I take the earlier commit ( 51b16307870484)  , indexing takes longer and the file transfer takes time ( ~ 8 min) but it completes the transfer, so between the two versions, the commit (51b16307870484) is the only one right now doing all the jobs.
Question: what should be an acceptable time to Drag & Drop Theia project? (I also have a few plugins with it for a total number of files ~ 65000 files)

**Comment by akosyakov** [comment]
> What is wrong with this version is the transfer of files, it does not transfer all the files, the progress % is not updated either.

Also noticed it, i don't handle empty files properly, going to push a fix soon.

**Comment by akosyakov** [comment]
@lmcbout should be good now

**Comment by lmcbout** [comment]
@akosyakov  Leaving in a few minutes, I will test it tomorrow

**Comment by akosyakov** [comment]
I've tested with uploading Theia repo (without running yarn) against google drive and this PR in Gitpod. In order to upload to google drive it takes 13m 34s. In order to upload to Gitpod it takes 2m 45s. I would say enough.

Also there is no such goal as to make upload fast for this PR, but stable with responsive UI during upload. I will try to make indexing less aggressive, e.g. read dirs one after another, not in parallel, in order to make UI more responsive.

**Comment by elaihau** [comment]
I tested the latest change it in gitpod.

- the browser had been very slow (but still responsive) for ~15 seconds since i drag-and-drop theia folder into my workspace. After that 15 seconds, it became faster and the experience as a user was back to normal.
- the status bar didn't became yellow.
- the percentage that indicates the uploading progress looked normal - it went from 0 all the way up to 100 on completion.

**Comment by akosyakov** [comment]
@lmcbout @elaihau i've reworked once again with indexing and uploading happens in parallel, so indexing should not create high pressure on the disk anymore. It makes progress reporting tricky since i cannot compute total size without indexing all files, so i report uploaded and total files in additional to the percentage. Please try again.

**Comment by lmcbout** [comment]
@akosyakov 
I don't see anymore the offline while indexing at the beginning +1  :)
Files transfer (Theia project) is a mid size project, so I think i is normal it takes a few minutes to upload. The first upload seems to take about the same time as before, but with the indication for the number of files out of Total, it gives the user that something is going on while he can still uses the browser +1
One thing I notice, it takes less time than before because I had the java LSP kicking in  at the same time.
I also notice the % is off with the numbers of files but it catches up and shows a proper % after.
So transferring about 60K files in about 4 minutes, I consider it good.
If someone else want to try before merging, 

Good job @akosyakov

**Comment by AlexTugarev** [comment]
It works really nice @akosyakov! 🎉 Thanks for tackling this!

One thing: I would be great to use a temporary filename which is considered as ignored in the navigator as well as for git. Otherwise it reports a lot of changes, as it updates continuously, which leads to a high cpu load.

Screen Shot 2019-05-14 at 15 09 40

**Comment by akosyakov** [comment]
@AlexTugarev good point, will have a look

**Comment by AlexTugarev** [comment]
Just for completeness: the high number of `onDidFilesChanged` events appears to happen if you try to upload a directory with many files.

**Comment by akosyakov** [comment]
@AlexTugarev exclude even reporting for temporary upload files, for git a user will need to add a pattern to gitignore file

good to merge?

**Pull request merged**
