### PR TITLE
theia-3437: Align terminal exit with Vscode.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Related issues: https://github.com/theia-ide/theia/issues/3437, https://github.com/eclipse/che/issues/11789

Screen-cast:

screencast-localhost-3000-2018 11 12-19-42-33

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
Hi, @svenefftinge. I took a look how task and debugger render process output. Task extension really uses terminalWidget, but this extension doesn't use taskWatcher with exit method inside terminal widget. Task extension use taskWatcher with "onTaskExit", "onTaskCreated" methods only to log events:

https://github.com/theia-ide/theia/blob/master/packages/task/src/browser/task-service.ts#L89
https://github.com/theia-ide/theia/blob/master/packages/task/src/browser/task-service.ts#L96

Debugger doesn't use terminal widget. Debugger console based on ConsoleWidget(this widget use Monaco editor inside to render output):

https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/console/debug-console-contribution.ts#L23
https://github.com/theia-ide/theia/blob/master/packages/console/src/browser/console-widget.ts#L44

So, I didn't see breaking changes. Please correct me, if I'm wrong.

**Comment by marcdumais-work** [comment]
> If I run a task that finishes or errors. Would I see the output? 

Yes. I tested killing the linux process spawned to execute a task, and the terminal was kept.

**Comment by marcdumais-work** [comment]
> VS Code doesn't close the terminals when tasks finished.
That needs to be covered.

I can confirm this is too is covered by the current PR.

**Comment by marcdumais-work** [comment]
@AndrienkoAleksandr Nice. I played a bit with this PR on Gitpod and I like getting rid of terminal widgets automatically. Will help reduce clutter on my workbench and the # of clicks I need to do.

**Comment by benoitf** [comment]
@marcdumais-work @akosyakov if it's fine for you, could you approve ?

**Comment by marcdumais-work** [comment]
@svenefftinge If I understood your concerns above correctly, I think they are addressed. Are you ok with merging this PR?

**Comment by AndrienkoAleksandr** [comment]
@svenefftinge Is it OK for you to merge this pull request or I need something improve?

**Pull request merged**
