### PR TITLE
Added tslint plugin to tsconfig

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

**Comment by akosyakov** [comment]
It is already added here: https://github.com/theia-ide/theia/blob/master/tsconfig.json#L98

**Comment by svenefftinge** [comment]
Interesting. It is not picked up for me. I might have to specify the tslint.confg file

**Comment by svenefftinge** [comment]
Mmmh, no it seems to be ok.

**Comment by svenefftinge** [comment]
Added a comment https://github.com/theia-ide/theia/issues/892#issuecomment-412048801

**Pull request closed without merging**
