### PR TITLE
Use ajv@6.5.4 instead of @6.5.3

### LINKED ISSUE #5292: Dependency issues around `ajv`.
### Description

Some warnings is shown on recent builds like this.

https://travis-ci.org/theia-ide/theia/jobs/538582706#L1758

### Reproduction Steps

Just run `yarn install`.

**OS and Theia version:**

the master branch.

**Diagnostics:** 

The link in the description above.

### PR DESCRIPTION
**Pull request by monaka**
fixes #5292 .

### CODE REVIEW

**Comment by kittaakos** [comment]
@monaka, did you modify the `yarn.lock` manually?

**Comment by marechal-p** [comment]
@monaka While we are at it, do you think it would be worth bumping the versions inside the different Theia extensions' package.json?

- `@theia/core`
- `@theia/keymaps`
- `@theia/workspace`

But since what you did already makes the project use `ajv@6.5.4`, I would be fine with how it is now.

**Comment by monaka** [comment]
@kittaakos Yes. Of course I see the good way is to delete and regenerate yarn.lock. But that way causes minor version level upgrade to may modules. (And as you know, upgrading minor version requires to pass Eclipse CQ.)

**Comment by marechal-p** [comment]
@monaka there is a `yarn upgrade-interactive ajv` command as well, I wonder how the different the output would be. I can try tomorrow.

**Comment by marcdumais-work** [comment]
I believe that it's unnecessary to go through the Eclipse IP process for a dependency update, when the change is only a bugfix release (stepping minor version number), like it's the case here for `ajv`. So looks good from an IP PoV.

**Comment by monaka** [comment]
@marechal-p  I tried on the master branch. Suggested to 6.10.0.
Screenshot 2019-05-31 at 09 53 15

I think it's better to use the `~` prefix instead of the `^` prefix. It's hard to keep Eclipse IP policy if we keep using `^`.
(refs: This suggestion was told by me at [the another issue in the another project](https://github.com/eclipse/che/issues/13298).)

**Comment by akosyakov** [comment]
> I think it's better to use the ~ prefix instead of the ^ prefix.

That's a bad idea from the technical perspective: Since yarn/npm cannot dedup node modules efficiently, overusing strict/exact version ranges can result in many different versions of the same module installed several times leading to:
- bigger bundle size to download for a user
- runtime errors because of incompatible classes
- build issues because of incompatible typings
- high maintenance effort since you have to update often to catch up

We've experimented with using strict version ranges before and because of reasons above decided to stick with yarn/npm defaults which is `^` ranges. If everybody start using strict versions very soon node_modules will become bloated and everybody will need to spend time resolving conflicts or updating dependencies to reduce the size.

Pinning can be fine if you are sure that you manage a dependency only in one place and your dependencies don't bring another version. But I would do it only temporary to overcome some bugs.

> It's hard to keep Eclipse IP policy if we keep using ^.

It has to be figure out with Eclipse then.

**Comment by monaka** [comment]
> That's a bad idea

If so, the second idea. With no prefix.
Anyway `package.json` in the master branch of Theia should have more strict dependencies.

Currently we can't build the master branch if we did `rm yarn.lock`. There is less merit by using versioning now.

**Comment by akosyakov** [comment]
> If so, the second idea. With no prefix. Anyway package.json in the master branch of Theia should have more strict dependencies.

As I explained more strict versions worse it gets. You cannot pin a dependency if it is not pined by your transitive dependencies, since everybody is using `^` by default it is not the case. The only sane approach to pin versions it is to [use yarn.lock file](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) Downstream projects should do the same to avoid relying on all transitive dependencies changes.

> Currently we can't build the master branch if we did rm yarn.lock. There is less merit by using versioning now.

We should try to remove it regularly and fix issues.

**Comment by monaka** [comment]
> The only sane approach to pin versions it is to use yarn.lock file

The point is. Your "sane approach" broke sane dependencies in `package.json`.

> We should try to remove it regularly and fix issues.

Yes. It's the goal.
I don't cling to my approach if current insane dependencies are fixed,  and also keep their version consistencies. For now, broken.

**Comment by monaka** [comment]
> I would not call it the "good way"..

Basically, the master piece is `package.json`. `And *.lock` is a cache for reduce dependency checking. The point of view dependency management., you don't need keep `package.json` if `yarn.lock` was a master piece, right? 

It might you members didn't notice about the breakage, the dependency management in this repo was broken. I don't want you accept my suggest, but you members should fix dependency failures by your "sane" approach, IMO.

**Comment by kittaakos** [comment]
> the dependency management in this repo was broken

I must be missing something; what exactly was broken?

**Comment by akosyakov** [comment]
> And *.lock is a cache for reduce dependency checking. 

@monaka It is not, please read the article which i've pointed you out before: https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/
Without lock files there is no ways to guarantee that another developer will install the same dependencies (even if he did not ever install them before).

There was not any real issues with our dependencies. It's fine in JS world to have 2 different versions of the same package. In our case we don't like it and have a script that reports when we have it. It's not an error from yarn. Thank you that you've spotted and cleaned it up.

**Comment by marechal-p** [comment]
@akosyakov speaking of the lock file, when publishing to npm the pinned versions are lost IIUC? It seems to only affect the main repo and not dependents/applications.

This is also what lead to the breakage of Theia applications with vscode-uri, it was pinned in the main repo, but new projects would pulll the new dependency.

Should we really use a lock file for the main repo? Or should we try upgrading our dependencies as much as possible? (given the range constraint used in the package.json file)

**Comment by akosyakov** [comment]
@marechal-p downstream projects should use lock files as well then they won't be broken. If something is wrong without lockfiles it is already detected in theia-apps, like it was the case for vscode-uri.

**Pull request merged**
