### PR TITLE
GH-454 added a PDF, SVG and idraw version of the BW logo

### PR DESCRIPTION
**Pull request by JanKoehnlein**

### CODE REVIEW

**Comment by AlexTugarev** [comment]
I think, we should remove width/height and add preserve aspect ratio, like https://jsfiddle.net/AlexTugarev/hsuqu9zx/1/

**Comment by svenefftinge** [comment]
It would be nice to move the fill color up, such that it is specified only once.

**Comment by JanKoehnlein** [comment]
My feeling is that we're never going to use the SVG file as is, but convert the logo to the appropriate format when we use it. It has been converted from the Adobe Illustrator format, which is kind of binary, to PDF and from there to SVG in order to be able to import it in Graphics (former iDraw) to fix some quirks and then reexported to SVG. So I'd treat it like a binary and avoid fiddling with the bits of it.

**Comment by JanKoehnlein** [comment]
The fact that SVG is textual suggest a bit too much for review.

**Comment by svenefftinge** [comment]
I actually wanted a white one just yesterday, so I changed the `fill` properties.

**Comment by JanKoehnlein** [comment]
@svenefftinge why not push it?

**Comment by svenefftinge** [comment]
Because I didn't want to force push on your branch.

**Comment by kittaakos** [comment]
I cannot wait to see this on the `master`.

**Pull request merged**
