### PR TITLE
[travis] auto sync cached directories

### PR DESCRIPTION
**Pull request by akosyakov**
Some new packages were not cached that broke travis caching. With this PR cached directories will be auto-synced by the prepare npm script.

Missing packages were json and tslint.

### CODE REVIEW

**Comment by kittaakos** [comment]
Wow, it is useful. Does this mean, if the `.travis.yml` file gets out of sync and one forgets to commit the changes to GIt, the build will fail due to this: https://github.com/theia-ide/theia/issues/2138? That would be the expected behavior right?

**Comment by kittaakos** [comment]
Can you please add a comment to the script, what it does and why? Or just reference the GH issue.

**Comment by akosyakov** [comment]
> Wow, it is useful. Does this mean, if the .travis.yml file gets out of sync and one forgets to commit the changes to GIt, the build will fail due to this: #2138? That would be the expected behavior right?

yes, it should be committed

**Comment by akosyakov** [comment]
@kittaakos I've added a comment to the script.

**Pull request merged**
