### PR TITLE
WIP: Add config values to monaco context key service

### PR DESCRIPTION
**Pull request by corneliusludmann**
#### What it does
VSCode plugins could use config values ('preferences') in 'when' expressions. This pull request adds all config values to the context key service to enable monaco to evaluate the 'when' expressions correctly.

Issue: theia-ide/theia#6082

#### Discussion and Open Concerns
- This fix adds the functionality that adds the config values to the context key service to the monaco context key service implementation. Probably there is a more appropriate and more generic place for this?
- The config values are gathered by subscribing to `onPreferenceChanged(...)`. Is it necessary to ask additionally for an initial set of config values, e.g. by adding the following code snipped?
```ts
const preferences = this.preferenceService.getPreferences();
for (const key in preferences) {
    if (preferences.hasOwnProperty(key)) {
        const value = preferences[key];
        this.addOrUpdateConfigContextKey(key, value);
    }
}
```
In my tests, by using this code snipped all config values has been added twice. So I decided that this is not necessary. True?
- **Open Bug:** For some reason, the context keys added during start up are overridden with null values. Therefore, the buttons in the maven VSCode plugin example mentioned in the issue are shown both as long as the first click sets the correct value again. I don't know which component set the the null values, but you can see that this happens by subscribing to `onDidChangeContext(...)`, e.g.:
```ts
this.contextKeyService.onDidChangeContext(e => {
    this.logger.info('onDidChangeContext:', e.affectsSome(new Set(['config.maven.view'])),
        this.configValues.has('config.maven.view'), this.configValues.get('config.maven.view')!.get());
});
```
Any idea how to figure out who writes null values and why?
- After the click on the maven view button, the 'when' expression is not evaluated immediately. The correct button is not shown until the user moves the mouse button away. Probably it needs a re-render call after the button click so that the changed config values affects the visibility of the buttons.

#### How to test
Add the maven VSCode plugin mentioned in issue theia-ide/theia#6082. Without this fix, the toolbar buttons that switch between flat and hierarchical view are shown both. With this fix, only one of the two buttons are shown (at least after the first click, see open bug above).

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by akosyakov** [comment]
`config.` context keys are already there (or should be) via hooking `PreferenceService` into underlying `MonacoContextKeyService`, see https://github.com/corneliusludmann/theia/blob/29d64fc3c015cc8f8cac345d856ecb07d7ec50bd/packages/monaco/src/browser/monaco-frontend-module.ts#L133-L170 and https://github.com/TypeFox/vscode/blob/c1dd5c86b7e1e55223831b1beb73f017bb19af94/src/vs/platform/contextkey/browser/contextKeyService.ts#L82-L142

I wonder why they did not get pick up?

**Comment by akosyakov** [comment]
I've noticed that `ContextKeyService` internals are changed in new version of Monaco, so it probably has to be reworked in the Monaco PR. I don't think it makes sense to work on it right now. cc @svenefftinge

**Comment by corneliusludmann** [comment]
Thanks for your very helpful feedback.

I tried the Maven VSCode plugin in #5901 and the problem of Issue #6082 with the toolbar icons is gone. Thus, it seems to work with that PR as expected?

The only remaining flaw is that the toolbar button icons are not changing immediately after click but when you move the mouse away and back to the toolbar.

So, I'm assuming for this issue there is nothing do to for me at the moment. Otherwise let me know …

**Comment by akosyakov** [comment]
> I tried the Maven VSCode plugin in #5901 and the problem of Issue #6082 with the toolbar icons is gone. Thus, it seems to work with that PR as expected?

That's strange, i did not try to fix it there. It would be good to understand what is different.

> The only remaining flaw is that the toolbar button icons are not changing immediately after click but when you move the mouse away and back to the toolbar.

Please file an issue for it, would be good to check when and how we can trigger rendering.

**Comment by corneliusludmann** [comment]
> > I tried the Maven VSCode plugin in #5901 and the problem of Issue #6082 with the toolbar icons is gone. Thus, it seems to work with that PR as expected?
> 
> That's strange, i did not try to fix it there. It would be good to understand what is different.

I'll take a look at it. I might notice something.

> > The only remaining flaw is that the toolbar button icons are not changing immediately after click but when you move the mouse away and back to the toolbar.
> 
> Please file an issue for it, would be good to check when and how we can trigger rendering.

#6102

**Pull request closed without merging**
