### PR TITLE
tslint: Enable trailing-comma

### PR DESCRIPTION
**Pull request by simark**
I like when people use a trailing comma in comma-separated definitions.
Turns out there is a tslint rule for it!  And it also has an autofixer,
so I ran tslint --fix to generate this patch.  I sampled a few files and
the results seems good.

For example, I would prefer this:

    const foo = [
      A,
      B,
      C,
    ];

rather than:

    const foo = [
      A,
      B,
      C
    ];

The main reason is that it simplifies diffs where you add a new item.
You don't need to change the line containing "C".

With the "multiline" setting, things like this are not affected:

    const foo = [ A, B, C ];

If you want to add "D", you'll need to change the line anyway, so the
comma would not help here.

Signed-off-by: Simon Marchi <simon.marchi@ericsson.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
How about asking the whole team first? changes in code styles should not be a preference of one person

**Comment by simark** [comment]
> How about asking the whole team first? changes in code styles should not be a preference of one person

Yep, this is the place to discuss it.

**Comment by kittaakos** [comment]
> Right, this is the place to discuss it.

I do not like it because it feels like you forgot something. But if the majority wants it, let's do it.

**Comment by akosyakov** [comment]
> Right, this is the place to discuss it.

I doubt that everybody is watching all PRs. Please discuss it on the dev meeting when everybody is back from vacations.

> I do not like it because it feels like you forgot something. But if the majority wants it, let's do it.

I agree with @kittaakos that it does not look nice and IMHO real value is minimal.

**Comment by MarkZ3** [comment]
One of the reason I like it is that it can help with merge conflicts. If two different commits add a last item then you don't need to fix the comma.
It also makes it a bit easier to add (copy/pasting) and to reorder things.
In the end, I don't think it's a big difference so I'm okay with either.
I agree that it makes sense to discuss this in the meeting as this can be controversial.

**Pull request closed without merging**
