### PR TITLE
Fixes to run dart and flutter vscode extensions

### PR DESCRIPTION
**Pull request by akosyakov**
#### What it does

Various fixes to run dart and flutter vscode extensions (https://github.com/theia-ide/theia/issues/3999):
- [x] https://github.com/Dart-Code/Dart-Code/issues/1948
- fixes https://github.com/theia-ide/theia/issues/6080

#### How to test

- dart testing
  - install dart and flutter sdk and configure PATH env variable properly
  - install dart and flutter vsix files in plugins folder
    - make sure to use 3.4.0-beta: https://github.com/Dart-Code/Dart-Code/releases/tag/v3.4.0-beta.2, an existing version has known issues, see https://github.com/Dart-Code/Dart-Code/issues/1948
  - start theia
  - use create new project command for flutter
  - open created project
  - use language features
  - debug dart code
  - run dart tests
- [ ] TBD: how to check that view nodes are cleaned up?

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by svenefftinge** [comment]
I tried it with https://github.com/flutter/flutter_web (my fork of it) and ran into multiple issues:
 - it asked me to install/update packages and ran `pub get` and did so but seemed to hang at some point.
 - at the same time the IDE was flooded with disgnostics (because of missing packages), which slowed the frontend down.
 - there were multiple errors in the console, complaining about usage of a disposed connection

**Comment by svenefftinge** [comment]
Interestingly, eventually everything seemed to be installed and working nicely.

**Comment by DanTup** [comment]
>  seemed to hang at some point.

As in the Dart process hanged, or something in the IDE? If it's the Dart process - it can be slow sometimes doing things like package resolution, but it shouldn't take forever. What's the simplest way for me to run this and see it?

> at the same time the IDE was flooded with disgnostics (because of missing packages), which slowed the frontend down.

How many do you mean by flooded? Are you still opening the whole flutter_web project, or just the example project? If just the example project I wouldn't expect many errors since there shouldn't be much code referencing the packages.

> there were multiple errors in the console, complaining about usage of a disposed connection

Are these issues you think in theia, or the extension? If you think the extension, do you still have the text?

Thanks!

**Comment by akosyakov** [comment]
@DanTup thank for your input! I will investigate it next day. Probably, just Theia needs a bit of optimizations.

**Comment by akosyakov** [comment]
@svenefftinge Could you try again?

**Comment by svenefftinge** [comment]
The diagnostics are updated weirdly.
I did the following:
 - open a file
 - make a syntactically invalid change (no errors)
 - save (still no errors)
 - close editor (errors in navigator)
 - reopen (errors)
 - fix syntax error (more errors on strange places (seems like the buffer in LS is corrupt)
 - copy all, clear editor and paste (no more errors)

**Comment by svenefftinge** [comment]
Also I noticed that after a change in the editor I can no longer apply any of the code actions proposed on components.
I get
```
winjs.base.js:1230 Uncaught (in promise) TypeError: e.offsetAt is not a function
    at t.RefactorCommands.<anonymous> (/tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1
    at new Promise (<anonymous>)
    at r (/tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1)
    at t.RefactorCommands.getRefactor (/tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1)
    at t.RefactorCommands.<anonymous> (/tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/dart-code-3.4.0-beta.3.vsix/extension/out/dist/extension.js:1
    at new Promise (<anonymous>)
```

**Comment by DanTup** [comment]
Let me know if it'd help much to have a build of the extension that isn't webpacked (we have to pack it to stop VS Code showing warnings due to slow sync module loading, but it probably makes understanding what's going on while debugging here harder).

`offsetAt` is a function on `TextDocument`, so ths error above is probably here:

https://github.com/Dart-Code/Dart-Code/blob/31340f4b9afedc7098bed7b10548aa4a25120dfc/src/extension/commands/refactor.ts#L68

**Comment by akosyakov** [comment]
Just noticed that with this PR, the flutter outline works:
Screen Shot 2019-09-03 at 14 00 17

**Comment by akosyakov** [comment]
@svenefftinge You can try again, now document changes and command args should be good. There is still an issue to resolve for code actions: https://github.com/theia-ide/theia/issues/6095 I will have a look tomorrow.

**Comment by akosyakov** [comment]
Code actions don't work with this PR anymore.

**Comment by DanTup** [comment]
As a heads up, I published a new Dart extension yesterday (v3.4.0) and it had a bug in running tests from Code Lens, so I also published a v3.4.1 with a fix this morning.

Release notes are here: https://dartcode.org/releases/v3-4/

I don't think there were any new APIs used in it, but I figured it worth calling out in case you see things failing that didn't before.

**Comment by akosyakov** [comment]
I've tested changes with following VS Code extensions
- java + java debug
- git
- sample tree views

Everything seems fine, i.e. code lenses and actions are there, git integration too, and tree view content is proper. Also tried with typescript extension, but it cannot function properly without exposing internal monaco commands.

I'm going to merge if the build is green and no objections.

**Comment by akosyakov** [comment]
@DanTup I was testing always against the latest master state of Dart extension, so it should be fine.

**Pull request merged**
