### PR TITLE
Fixed typo, moved generate-layout script

### PR DESCRIPTION
**Pull request by spoenemann**
The `generate-layout` script uses Electron and thus should be moved to a package that has a direct dependency to it.

### CODE REVIEW

**Comment by spoenemann** [comment]
Open question (copied from #4724):

Should we extract the script to a separate repository to make creating keyboard layouts easier, esp. for external contributors? We don't need to build the whole of Theia just to run a simple NodeJS script.

**Comment by akosyakov** [comment]
@spoenemann Together with generated layouts that other can contribute?

**Comment by akosyakov** [comment]
> The generate-layout script uses Electron and thus should be moved to a package that has a direct dependency to it.

We don't publish generate-layout script layout right now. And electron is always hoisted to root, so yarn can find it from any place in the project. Do you really want to move it?

**Comment by spoenemann** [comment]
> Together with generated layouts that other can contribute?

Those need to be in `@theia/core` so we can use them directly (unless we publish an external package dedicated to this purpose and depend on it).

> electron is always hoisted to root

Nevermind then.

**Pull request closed without merging**
