### PR TITLE
[plug-in] Move 'api' folder in to 'common' folder

### PR DESCRIPTION
**Pull request by evidolob**
Part of #3871
This pull only move files from 'plugin-ext/src/api' to 'plugin-ext/src/common'
Also it change name of 'model.ts' to 'plugin-api-rpc-model.ts' and 'plugin-api.ts' to 'plugin-api-rpc.ts'

Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
@vinokurig @mmorhun please add (generally) a review comment what your approve means. If it means that you've tested that a PR does not introduce any regressions and checked that no abstractions are broken then it should be enough and @evidolob can proceed with merging without waiting for my, @benoitf or anybody else approve.

**Comment by vinokurig** [comment]
Tested against vscode Git Extension, no regression found.

**Comment by akosyakov** [comment]
ok, please merge it, i don't have time to test it. Structurally the most important that dependencies are clear between module folders and to runtimes, in accordance with https://github.com/theia-ide/theia/wiki/Code-Organization. e.g. browser should not use any node apis and so on.

**Comment by evidolob** [comment]
Update to latest master changes.
Tested with VSCode extensions:
- https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer
- https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker
- https://marketplace.visualstudio.com/items?itemName=oderwat.indent-rainbow
- https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

**Pull request merged**
