### PR TITLE
[WIP] Travis cache

### PR DESCRIPTION
**Pull request by marcdumais-work**

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@vince-fugnitto Still testing. this might not fix the issue - CI passes the first time after clearing the cache, but might still fail when cache present.

**Comment by marcdumais-work** [comment]
@vince-fugnitto yep, it failed the second time on Linux.

**Comment by vince-fugnitto** [comment]
@marcdumais-work oh sorry I hadn't realized, I know Paul tried as well in https://github.com/theia-ide/theia/pull/5601 to try and fix the issue.

**Comment by marcdumais-work** [comment]
> Paul tried as well in #5601 to try and fix the issue.

Yes; at first I tried to push on top of that PR but it's easier to troubleshoot in insulation. I tried to open this PR on my fork, but it ended-up here :)  

Will close and if I find a way, I'll open a new PR.

**Comment by marcdumais-work** [comment]
> The PR was a WIP.

No worries - I added "WIP" after you commented, realising  I was not alone here ;)

**Comment by marcdumais-work** [comment]
will continue experimenting on my fork: https://github.com/marcdumais-work/theia/pull/1

**Pull request closed without merging**
