### PR TITLE
[Theia] Fix typo when pulling from/pushing to remote

### PR DESCRIPTION
**Pull request by vinayb21**
Fixes issue https://github.com/theia-ide/theia/issues/4365

### CODE REVIEW

**Comment by benoitf** [comment]
hello @vinayb21 you need to sign ECA / https://www.eclipse.org/legal/ECA.php so that we can approve your pull request.

**Comment by vinayb21** [comment]
> hello @vinayb21 you need to sign ECA / https://www.eclipse.org/legal/ECA.php so that we can approve your pull request.

**Comment by vinayb21** [comment]
> hello @vinayb21 you need to sign ECA / https://www.eclipse.org/legal/ECA.php so that we can approve your pull request.

@benoitf signed te ECA

**Comment by benoitf** [comment]
@vinayb21 I got `User not found.` when using your signed-off email. did you register with another email ?

**Comment by vinayb21** [comment]
Yes. Changing the signed off email address.

**Comment by benoitf** [comment]
@vinayb21 ok now ECA is green but DCO is red
https://github.com/theia-ide/theia/runs/69527190

commit email and SignedOff email need to be the same

**Comment by benoitf** [comment]
now ECA is failing again

**Comment by vinayb21** [comment]
It should work now. I created a new account with the email with which I signed off.

**Comment by vinayb21** [comment]
@benoitf Can you please try now.

**Comment by kittaakos** [comment]
@vinayb21, the ECA email and the sign-off-by should be the same.

_There is no valid ECA on file for vinay@hackerrank.com._

**Comment by vince-fugnitto** [comment]
What do we do regarding the other PR that attempted to fix the issue first ? #4413

**Comment by benoitf** [comment]
@vince-fugnitto I would close the other one as the commits are not fixing the issue :)

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I would close the other one as the commits are not fixing the issue :)

Yes I saw, I was trying to help him fix it, but it looks like his history got a little messed up :( 
I'll leave the decision up to you :)

**Comment by benoitf** [comment]
@vinayb21 as @kittaakos reported, you still don't have ECA signed so we can't merge your pull request

```
There is no valid ECA on file for vinay@hacker****.com.
```

**Comment by vinayb21** [comment]
> @vinayb21 as @kittaakos reported, you still don't have ECA signed so we can't merge your pull request
> 
> ```
> There is no valid ECA on file for vinay@hacker****.com.
> ```

I just checked. There is a valid ECA now for my email id. 
Can you please try again.

**Comment by kittaakos** [comment]
> There is a valid ECA now for my email id.

✅ Verified.

**Pull request merged**
