### PR TITLE
[publishing] add a warning in the tagging section

### PR DESCRIPTION
**Pull request by akosyakov**

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@akosyakov 
> If publishing of an individual package failed then publish it with `npm publish` from its root after resolving outstanding issues.

I believe that I did try that, without success. I probably just did it wrong. Can you provide a bit more details, or should the above, as-is, work?

**Comment by akosyakov** [comment]
i did:
```
cd packages/java
npm login
npm publish
```

Did you do the same?

**Comment by marcdumais-work** [comment]
Yes, but I think I added a "." at the end of the publish command. I tried to reproduce using a private npm registry, and I think I got the same result as I had, on public npm: 

```
/opt/ericsson-dev/theia/packages/java$ npm publish

> @theia/java@0.3.11 prepare .
> yarn run clean && yarn run build

yarn run v1.3.2
$ theiaext clean
Done in 0.49s.
yarn run v1.3.2
$ concurrently -n download,build -c red,blue "gulp download_java_server" "theiaext build"
/bin/sh: 1: concurrently: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/java@0.3.11 prepare: `yarn run clean && yarn run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @theia/java@0.3.11 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lmcmcds/.npm/_logs/2018-05-02T12_07_42_531Z-debug.log

``` npm

**Comment by marcdumais-work** [comment]
yes, just re-did it, to confirm. Same error. The same worked for you?

**Comment by marcdumais-work** [comment]
```
/opt/ericsson-dev/theia$ find . -name concurrently
./node_modules/.bin/concurrently
./node_modules/concurrently
```

It's there. But it doesn't seem to be found when running from the root of a package?

**Comment by akosyakov** [comment]
It looks good, could you try to update yarn? They changed how binaries looked up in latest versions, maybe yours is now fresh enough.

**Comment by marcdumais-work** [comment]
With the latest yarn, it worked. Thanks @akosyakov !

**Pull request merged**
