### PR TITLE
[WIP] GH-4874: Build the electron app from the source.

### LINKED ISSUE #4874: [electron] As a developer I want to build a bundled electron application from the source
Currently, we have a kind of working solution outside of the repository: https://github.com/theia-ide/theia-apps/tree/master/theia-electron.

For historical reasons, we had to move the electron bundling outside of the repository, because the `electron-builder` could not follow symlinks. In other words, and it is an oversimplification, the `package.json` of the electron application wasn't next to the `node_modules` folder where the real dependencies were: `examples/electron/package.json` and `node_modules`.

Make sure we can bundle and not just build an electron application from the source.
Otherwise, we have to merge changes to the `master`, then verify it in the bundled electron application. We could try it with [`deferSymlinks`](https://github.com/theia-ide/theia/pull/4826#issuecomment-481683235).

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #4874.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

----

Steps to build:
 - Clone Theia and run `yarn` to install the dependencies.
 - Run `yarn --cwd ./examples/electron/ package` to build the bundled electron application from the source.
 - Run `open ./examples/electron/dist/mac/Theia.app/` (on macOS)  to start the application.

The bundled application will be under `theia/examples/electron/dist`.
By default, the `electron-builder` builds an application based on your OS.

### CODE REVIEW

**Comment by kittaakos** [comment]
After installing it to the `/Applications/` I can see the following error:

```
messages.js:46 Uncaught (in promise) Error: Error: Failed to spawn node
Perhaps it is not on the PATH.
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at Immediate.<anonymous> (main.js:242)
    at runCallback (timers.js:696)
    at tryOnImmediate (timers.js:667)
    at processImmediate (timers.js:649)
main.js:825 Uncaught (in promise) Error: Connection got disposed.
    at Object.dispose (main.js:825)
    at TypeScriptClientContribution.<anonymous> (language-client-contribution.ts:158)
    at step (language-client-contribution.ts:15)
    at Object.throw (language-client-contribution.ts:15)
    at rejected (language-client-contribution.ts:15)
DevTools failed to parse SourceMap: file:///Applications/Theia.app/Contents/Resources/app/lib/9.bundle.js.map
```

It works when running from `theia/examples/electron/dist`, this must be a PATH issue although we call `fix-path` from the electron maim module. I will work on this a bit.

**Comment by akosyakov** [comment]
I wonder do you need email and homepage? It was failing for me without.
If I run `yarn package` i get:
> Error: Please specify author 'email' in the application package.json

**Comment by akosyakov** [comment]
I can verify that preview command works, nice!

Screen Shot 2019-04-15 at 07 36 20

Maybe we don't need `package` command. I don't think our example app is good example, it has so many unnecessary extensions for the simple app.

**Comment by kittaakos** [comment]
> If I run `yarn package` i get:
> 
> > Error: Please specify author 'email' in the application package.json

No, it was not failing to me, but this PR is wrong as is, sorry for the noise. Incorrect versions are picked up due to the way the electron-builder collects the hoisted dependencies.

**Pull request closed without merging**
