### PR TITLE
[tab-bars] compute tab sizes also during onAfterAttach

### PR DESCRIPTION
**Pull request by svenefftinge**
Signed-off-by: Sven Efftinge <sven.efftinge@typefox.io>

### CODE REVIEW

**Comment by hexa00** [comment]
Could you explain what issue this is fixing ? or the reason for the change?

**Comment by hexa00** [comment]
The change in initializeLayout also seems unrelated?

**Comment by svenefftinge** [comment]
The computation of tabsizes possibly happens before the shell got attached, resulting in `width` and `height` computation to be `0px`. So the tabs were not visible. 
This change ensures that the computation happens on update but also on after attach, so it no longer can happen. It was not reliably reproduceable (I could with a local configuration) but clear when analyzing the flow of events.

The change to `initializeLayout` is related in that any async code should return a promise so the caller can decide whether to wait for the execution to happen.

**Comment by hexa00** [comment]
@svenefftinge this explaination would make a nice commit log.

Also I think this may not work since:

For example on restore, what will restore the tabbar is:

`this.mainPanel.restoreLayout(mainPanel);`

This calls:

```typescript
    // Attach the new widgets to the parent.
    widgetSet.forEach(widget => {
      this.attachWidget(widget);
    });

```

Which then fire the onAttachEvent if the parent is attached.

```
  // Send an `'after-attach'` message if the parent is attached.
    if (this.parent!.isAttached) {
      MessageLoop.sendMessage(widget, Widget.Msg.AfterAttach);
    }
```

But in this case the parent is TheiaDockPanel and it's not attached (I've verified this in debug). And the onAttachEvent is not fired.

This seems weird to me since I don't see where the panels are attached to the shell,  would you know ?

I have the same problem with the terminal restore where it needs to be in the DOM as it restores to calculate its size but it's not on restore since we attach the shell at the end of the restore cycle.

**Comment by svenefftinge** [comment]
> I have the same problem with the terminal restore where it needs to be in the DOM as it restores to calculate its size but it's not on restore since we attach the shell at the end of the restore cycle.

But the `start`in `terminal-widget` runs `onafterAttach`, too. So it relies on the same life-cycle event. What is the issue with that?

**Comment by hexa00** [comment]
>The after-attach event is sent transitively once the shell gets attached.

Where is that done? I could not find the code for that in phospor...

**Comment by svenefftinge** [comment]
> Where is that done? I could not find the code for that in phospor...
It happens through the layouts.

**Pull request merged**
