### PR TITLE
package vsix together with debug extensions

### PR DESCRIPTION
**Pull request by akosyakov**
In order to avoid downloading them on postinstall by clients. Downloading turned out to be quite unreliable.

### CODE REVIEW

**Comment by svenefftinge** [comment]
@benoitf do you have a proposal for solving the unreliable builds differently?

**Comment by benoitf** [comment]
@svenefftinge binaries could be hosted somewhere else (not in main theia source repository) with CDN access)
(like https://www.jsdelivr.com/ or many others)

**Comment by akosyakov** [comment]
> This also has the additional (unwanted?) side effect that the debug adapters are no longer coming from their origins and have to be updated in the Theia codebase with any new version.

it is the same now. You had to change package.json to pull new versions.

I'm fine if someone work on cdn support. Could it be done separately? There was not stable build for Theia a week already.

**Comment by benoitf** [comment]
the think is that if binaries are added once even temporary, then the repository is bigger for the eternity :-)

**Comment by akosyakov** [comment]
Just discussed with @svenefftinge again. Before going with cdn, we will add a check to catch cases when adapters is not downloaded and if not there then retry it several times, similar to `travis_retry`. If it does not help, then we go with cdn.

**Pull request closed without merging**
