### PR TITLE
GH-958 removed go extension

### PR DESCRIPTION
**Pull request by JanKoehnlein**
(in favor of new separately maintained go extension)

### CODE REVIEW

**Comment by kittaakos** [comment]
Did you miss [this](https://github.com/theia-ide/theia/blob/316e03f1e5d6cccb5da298fc2c5415f95447ebdc/tsconfig.json#L69) on purpose? I assume yes because you will re-introduce it. But I am just guessing.

**Comment by JanKoehnlein** [comment]
@kittaakos no, good catch!

**Comment by hexa00** [comment]
Is this WIP ?

Should we replace the extension in the examples with the one from https://github.com/theia-ide/theia-go-extension in this PR ? like the issue suggests ?

**Comment by JanKoehnlein** [comment]
Replacing it doesn't work as the new one is an external extension.
I am preparing a separate theia app for go.

**Comment by hexa00** [comment]
Right OK.

**Comment by JanKoehnlein** [comment]
Theia-app docker image with latest go is ready.

**Pull request merged**
