### PR TITLE
Use all the type hierarchy levels the server sends (fixes #4540)

### LINKED ISSUE #4540: [Type Hierarchy] Support servers that want to compute the type hierarchy eagerly
The current implementation of Type Hierarchy appears to always ask for one level of the hierarchy at a time, and ignore additional levels even if the server chooses to send them.

I think it would be good to support language servers that want to compute the type hierarchy eagerly. Specifically, if the server sends more levels than requested, Theia should make use of the levels that were actually sent.

(For some context, I'm working on an [implementation for the C++ language server](https://reviews.llvm.org/D56370). There, at least for parents, the marginal cost of computing the entire parent hierarchy compared to just one level is negligible, while the cost of computing each level in a separate request is a lot higher. Therefore, we return the entire parent hierarchy in response to `textDocument/typeHierarchy`, and do not support `typeHierarchy/resolve` for parents. However, with the current Theia implementation, Theia will only display one level of the hierarchy.)

@kittaakos @marcdumais-work

### PR DESCRIPTION
**Pull request by HighCommander4**
Closes #4540.

### CODE REVIEW

**Comment by kittaakos** [comment]
@HighCommander4, you have to sign your commit and also the [ECA](https://github.com/theia-ide/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement).

**Comment by HighCommander4** [comment]
Updated to include signoff. Note, I do already have an ECA on file (I'm an Eclipse CDT committer).

**Comment by kittaakos** [comment]
> Updated to include signoff.

👍 

> have an ECA on file

✅ Confirmed.

**Comment by HighCommander4** [comment]
Thanks for merging!

> Please note, once we get some feedback/approval on the [`textDocument/typeHierarchy` proposal](https://github.com/Microsoft/vscode-languageserver-node/pull/426), we might change this behavior in Theia.

Understood. The C++ server implementation will be updated in line with any changes / clarifications in the spec as well.

**Pull request merged**
