### PR TITLE
Debug Model

### LINKED ISSUE #2817: [debug] Cannot scroll the `variables` panel
theia-debug-variables-noscroll

### LINKED ISSUE #2879: New concept for Theia views
Currently I'm implementing [View plugin API](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesviews) which gives the ability to the developer to embed his view to the UI. View can be displayed only inside view container. Theia does not support this kind of displaying the views, so I have implemented custom view container (displayed as view in Theia terms) which may display several views inside itself. This view container like Theia view has id, title and icon.

In VS Code plugin can embed his view container only to 'activitybar' which actually is left part of the layout. In Theia I did not set such restriction and plugin can show the view container in left, right and bottom parts.

See an example. Plugin describes 'Package Explorer' view container on the left, 'Comments' on the right and 'Remote' on the bottom. 'Package Explorer' contains 'Package Dependencies' and 'Package Outline' views, 'Comments' contains three automatically generated views (one per user, for example). 'Remote' view container at the bottom has only one view. Actually I'm not sure whether we need to describe view containers for the bottom parts. When I try to display several views inside of it, it become looking ugly.

views

For an instance, in the current version of Theia plugin cannot embed 'Opened Editors' view to the 'Files'/'Explorer' part and the functionality like in VS Code that displays opened editors can not be implemented. 

That's why I want to propose new view concept for Theia.

vs code views concept

Considering this concept views are displayed inside parts.

I still don't know whether we need to describe part for all the views or maybe part can be automatically generated if some code wants to open the view without specifying the part. 

I still haven't seen how it's implemented in VS Code and for me it is still not clear.
Let's discuss this together and find a solution.

Pros:
- it would allow to embed custom view to any Theia part

Cons:
- may be some issues with dragging and dropping the views

### LINKED ISSUE #2963: leaking node debug processes
I've noticed that after running the same debug configuration several times and closing all debug panels there are still some debug processes running:
screen shot 2018-09-25 at 10 39 04

### LINKED ISSUE #3008: [debug] Issues with debug toolbar
I've noticed a few issues with the new debug toolbar which could be addressed as part of the [debug epic](https://github.com/theia-ide/theia/issues/2843) being worked on.

- The `resume` button doesn't get enabled when when the debugger is suspended or a breakpoint is hit
- When resuming the debugger (using the context menu item), the `suspend` button isn't enabled
- [enhancement] There is no `restart` button for debuggers which support restarting

These were found during testing of the [debug-cortex adapter](https://github.com/theia-ide/theia/pull/3000) so may not be apparent in all adapters. I can supply videos if needed.

cc @tolusha

### LINKED ISSUE #3109: [debug] Track threads?
Currently the debug system relies on the adapter to report all threads for the purpose of [pausing and resuming](https://github.com/theia-ide/theia/blob/master/packages/debug/src/browser/debug-session.ts#L116).

Unfortunately [some debug adapters](https://github.com/Marus/cortex-debug/blob/3c429a7edb05f1156bc1000968684cb33d82359a/src/gdb.ts#L826) don't allow reading of the threads unless stopped.

Should we maintain a copy of all threads internally via the `thread started` and `thread exited` events.

cc @tolusha @jonahgraham @marechalp @akosyakov

### PR DESCRIPTION
**Pull request by akosyakov**
This PR decouples models objects from UI and encapsulate them in `DebugSession`.

There is no `DebugSelection` anymore, one can get everything from `DebugSessionManager`, i.e.:
`this.manager.currentSession.currentThread.currentFrame.resolveScopes()`.

debug

Fixes #3109, fixes #2879, fixes #3008, fixes #2817, fixes #2963

TODO:
- [x] keybindings
  - for f11 on mac: https://github.com/Microsoft/vscode/issues/5102
- [x] debug actions focus highlighting
- [x] horizontal layout - should be conifgurable per a view container
- [x] get rid of an extended protocol, i.e. variableUpdated, configurationDone, connected, loadedSource, capabilities - backend only should do forwarding, events should be introduced in the frontend
- [x] debug toolbar
  - [x] proper session status management
  - [x] better icons
  - [x] configurations drop-down
  - [x] proper variable resolution from a drop-down
  - [x] restart
  - [x] align action order
- [x] session
  - [x] revealing on stop event
  - [x] starting a session in a separate panel via debug configuration
  - [x] opening running sessions in a separate panel
  - [x] context menu
    - [x] `Restart`
    - [x] `Stop`
    - [x] `Pause All`
    - [x] `Continue All`
  - [x] breakpoinst are not properly rendered with multiple panels
- [x] threads
  - [x] mulitple configurations
  - [x] rendering with React
  - [x] smooth keyboard navigation
  - [x] context menu
    - [x] `Pause`
    - [x] `Continue`
    - [x] `Step Over`
    - [x] `Step Into`
    - [x] `Step Out`
    - [x] `Terminate Thread`
  - [x] preserve a frame selection
- [x] call stack
  - [x] update on continue
  - [x] revealing a source
  - [x] render as a tree
  - [x] smooth keyboard navigation
  - [x] lazy loading
  - [x] render errors, i.e StoppedDetails.framesErrorMessage
  - [x] context menu
    - [x] `Restart Frame`
    - [x] `Copy Call Stack`
  - [x] restart frame
  - [x] reveal source on step
  - [x] avoid flickering between stopped events
- [x] breakpoints:
  - [x] better styles
  - [x] editor
    - [x] hint decorations
    - [x] breakpoint decorations
      - [x] invalidate on a change
    - [x] stack frame decorations
    - [x] context menu
      - [x] `Remove Breakpoint`
      - [x] `Disable/Enable Breakpoint`
  - [x] widget
    - [x] content    
    - [x] context menu
      - [x] `Remove Breakpoint`
      - [x] `Remove All Breakpoints`
      - [x] `Enable All Breakpoints`
      - [x] `Disable All Breakpoints`
    - [x] toolbar
      - [x] `Deactivate/Activate Breakpoints`
      - [x] `Remove All Breakpoints`
    - [x] commands
  - [x] source
  - [x] storage
  - [x] enablement
    - [x] single
    - [x] all
- [x] review debug styles 
- [x] variables
  - [x] render variables as in the console
  - [x] smooth keyboard navigation
  - [x] context menu
    - [x] `Set Value`
    - [x] `Copy Value`
    - [x] `Copy as Expression`
- [x] view container
  - [x] collapsible part
  - [x] toolbar part
  - [x] attach/detach
- [x] files are empty on activation -> https://github.com/theia-ide/theia/issues/3115
- [x] tree widget
  - [x] optional virtualization
    - [x] keyboard navigation
    - [x] proper scrolling
  - [x] tree source
- [x] session termination
  - [x] exited twice because of a closed WS channel
  - [x] leaking debug adapter process -> https://github.com/theia-ide/theia/issues/2963
- [x] focused session management, check:
  - [x] editor
  - [x] console
- [x] performance optimization
- [x] memory leaks profiling

Follow-up TODO:
- threads: step back, reverse continue
- breakpoints: conditional, functional, exception
- ~breakpoints: handling source code changes while debugging~ - fixed
- configurations: snippets
- editor: variable hover
- variables: the same state for the debug console and the variables view

### CODE REVIEW

**Comment by akosyakov** [comment]
It's ready for the review.

@thegecko it would be interesting if you can try cortex-debugger on the top of this PR and see whether you still have races.

**Comment by tolusha** [comment]
That's really cool!

**Comment by tolusha** [comment]
@akosyakov 
As far as I understand you are going to get rid of `SessionState` and `DebugSessionStateAccumulator`.
I've introduced these entities to be able to restore debug session when browser is refreshed.
Do you have any suggestion how it is supposed to be when PR is merged?

**Comment by svenefftinge** [comment]
Awesome progress, Anton! ❤️ 
Things I noticed:
 - Adding a breakpoint during a running session, feels sluggish because not icon is added on click but only after the breakpoint got validated by the session.
 - breakpoints indicated as inactive with message 'Breakpoint ignored because generated code not found (source map problem?).'. Although they hit.
screen shot 2018-10-18 at 11 10 22
 - the prompt in the debug console is black in dark mode:
screen shot 2018-10-18 at 11 11 14
 - An expanded node with no contents, should have an emptiness-place holder.
screen shot 2018-10-18 at 11 26 37
E.g. similar to dev tools:
screen shot 2018-10-18 at 11 27 39

**Comment by svenefftinge** [comment]
- The variables is empty when a breakpoint hits. I have to explicitly select the stack frame to see variables.
 - The console view should be opened made visible on process start.

**Comment by akosyakov** [comment]
@tolusha good point! I was thinking that sessions exist only within the page lifetime, but sharing all sessions between all clients for same backend is certainly what we want to have, especially for the case with shared workspaces, i.e. for shared debugging.

It sounds very involving though for the first usable implementation. Ideally we want to allow all clients to see and control all sessions for opened workspaces in parallel. In order to achieve it, the backend should allow to fetch sessions for given workspaces and connecting to the same adapter by several clients. It is not something implemented yet. We want to look into it later after EclipseCon. With that, indeed we need to pull shared debug session state to the backend, maybe by reintroducing `SessionState`. I cannot say for sure now.

BTW I've realized now a root cause of https://github.com/theia-ide/theia/issues/2963: we close a page but does not stop associated sessions, and there is no way to see/stop them later after refresh. For now, sessions can be closed when a client connnection is lost.

//cc @svenefftinge

**Comment by akosyakov** [comment]
@svenefftinge I've addressed all your comments except:

> Adding a breakpoint during a running session, feels sluggish because not icon is added on click but only after the breakpoint got validated by the session.

For me it feels fine. Can you clarify what you do?

**Pull request merged**
