### PR TITLE
GH-584 Wired `git checkout` into the status bar.

### LINKED ISSUE #584: [git] Add Git status bar
Just like in VSCode.
Should list the remotes (maybe not) and the known branches. Also: ahead and behind.

When clicking on the branch, it should trigger a command with the `quick open widget` that helps in switching to and creating a new branch.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #584.

### CODE REVIEW

**Comment by svenefftinge** [comment]
Cool, it looks and works very well! 
In case the checkout doesn't succeed, we should inform the user through a notification displaying the error. A common one seems to be `The following untracked working tree files would be overwritten by checkout ... `

**Comment by kittaakos** [comment]
> we should inform the user through a notification displaying the error

I completely agree. But this applies in general to all Git failures. Can we do that in a separate PR and task?

**Comment by svenefftinge** [comment]
> I completely agree. But this applies in general to all Git failures. Can we do that in a separate PR and task?

Ok. Could you look into it next?

**Comment by kittaakos** [comment]
> Ok. Could you look into it next?

👍 https://github.com/theia-ide/theia/issues/896

**Pull request merged**
