### PR TITLE
[filesystem] Fixes #4792 XSS vulnerability.

### LINKED ISSUE #4792: [filesystem] XSS vulnerability on /files endpoint
### Description

There is an XSS vulnerability that allows remote control execution on the /files endpoint of Theia. 

### Reproduction Steps

Use the following payload to reproduce:

/files/?uri=%3Cscript%3E&uri=,alert(1)%3C/script%3E

### PR DESCRIPTION
**Pull request by caseyflynn-google**
Mitigates the issue by removing all unsanitized information from the
response.

Signed-off-by: Casey Flynn <caseyflynn@google.com>

### CODE REVIEW

**Comment by kittaakos** [comment]
Thanks for taking care of this, @caseyflynn-google. I do not have experience with XSS vulnerabilities, so you have to help me here; I guess the problem is that we send back the sensitive information as part of the response, and it is unrelated to the logging, right? If so, I still would like to see the "reasons" in the log. Otherwise, the logging is useless. Thoughts?

**Comment by caseyflynn-google** [comment]
> I guess the problem is that we send back the sensitive information as part of the response

Not quite, the issue is that an attacker could trick a user into run arbitrary javascript under whichever domain an instance of Theia is running on: https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)

tl;dr 
It allows attackers to steal cookies, session tokens, impersonate user actions, etc. by clicking a seemingly innocuous link. 

> If so, I still would like to see the "reasons" in the log. 

Sounds good to me, would it be alright if we send a generic message back to the user, maybe a generic "Unable to download file." with a 400 response code?

**Comment by kittaakos** [comment]
> would it be alright if we send a generic message back to the user, maybe a generic "Unable to download file." with a 400 response code?

Sure. The only thing I do not want to lose with this change is the possibility to read the log and see what went wrong. You can adjust the APIs if it is a must.

**Comment by caseyflynn-google** [comment]
> > would it be alright if we send a generic message back to the user, maybe a generic "Unable to download file." with a 400 response code?
> 
> Sure. The only thing I do not want to lose with this change is the possibility to read the log and see what went wrong. You can adjust the APIs if it is a must.

Done.

**Pull request merged**
