### PR TITLE
Initial WhiteSource configuration file

### PR DESCRIPTION
**Pull request by IO137**
azure®intergrated>vlob

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
@IO137 I'm assuming this PR was mistakenly pushed to the main repository?

**Comment by IO137** [comment]
Yes are You able to null action/?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IO137** [comment]
@vince-fugnitto
  Use the control in pull request discussions, commit comments, changeset comments, and shelveset comments.

_

**Comment by vince-fugnitto** [comment]
@IO137 I'm not sure I understand what you mean?

**Comment by IO137** [comment]
Disregard. Delete accounts

**Pull request closed without merging**
