### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vince-fugnitto**
The `README` is often the first thing a new user or developer sees when searching for Theia or looking through the main repo, I propose we brand it better for better visibility and showcase our identity.

- Updated `README.md` to include Theia's logo
- Updated styling of badges, screenshot, and header
- Effort to increase visibility of the Theia platform and brand ourselves better

|Current|New|
|:---:|:---:|
|screen shot 2018-11-25 at 7 59 21 pm|screen shot 2018-11-25 at 7 59 06 pm|

Signed-off-by: Vincent Fugnitto <vincent.fugnitto@ericsson.com>

### CODE REVIEW

**Comment by marcdumais-work** [comment]
@vince-fugnitto I believe we will soon need to start using "Eclipse Theia" in such official documentation. I do not think we have such a logo yet? Would you create one and include it in this patch? 

Also I would suggest adding a screenshot of the current README, for easy comparison.

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto I believe we will soon need to start using "Eclipse Theia" in such official documentation. I do not think we have such a logo yet? Would you create one and include it in this patch?
> 
> Also I would suggest adding a screenshot of the current README, for easy comparison.

@marcdumais-work yes I'll see if I can create a simple logo for the moment to reflect `Eclipse Theia` instead of our current one, and I'll add the extra screenshot for comparison.

**Comment by uniibu** [comment]
I think the `Roadmap` section should be updates as well, as we are nearing the end of 2018 already. Imo, it should be updated with a `2019 Roadmap` instead.

**Comment by svenefftinge** [comment]
Can we please have a screenshot of the browser version instead of Electron?
Alternatively something that communicates browser/native support like I did for the website.

**Comment by vince-fugnitto** [comment]
@svenefftinge thanks for your feedback, I made the appropriate changes. I do agree with @uniibu that we should probably update the roadmap and main features as we have greatly progressed over the year :)

**Pull request merged**
