### PR TITLE
Fixed #5734 correct workspace path variables on windows

### LINKED ISSUE #5734: ${workspaceFolder} variable starts with slash on windows
### Description
${workspaceFolder} starts with slash on windows system e.g. /c:/Users/Vineg/theia-workspace

### Reproduction Steps
Run browser example on windows OS, open any local workspace

windows 7, theia 0.8.0

**Diagnostics:** 
image

I debugged this issue a little and can see that workspace url fragment uses URI("file:///c:/Users/...").path which leaves first slash untouched.

This issue causes 

> Attribute 'program' does not exist ('{path}'). error.

### PR DESCRIPTION
**Pull request by Vineg**

### CODE REVIEW

**Comment by akosyakov** [comment]
@Vineg how one can verify correctness?

**Comment by Vineg** [comment]
@akosyakov I checked that node js simple app configuration such as

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  "version": "0.2.0",
  "configurations": [
      {
          "type": "node",
          "request": "launch",
          "name": "Launch Program",
          "program": "${workspaceFolder}/app.js"
      }
  ]
}
```

starts fine on windows.

It caused 
> Attribute 'program' does not exist ('{path}').
error before.

**Comment by kittaakos** [comment]
I am trying this now.

**Comment by kittaakos** [comment]
@akosyakov, any remarks? If no, please press the merge button ;) Thanks!

**Pull request merged**
