### PR TITLE
new extension to post message to window.parent in case of conn. loss

### PR DESCRIPTION
**Pull request by ariel-bentu**
This new suggested extension, posts a message to a parent-window in case one exists and notify it of Connection changes:
* 'Connection: ACCESS_DENIED', when attempt to connect to the server returns http-status-code 401 or 403
* 'Connection: SERVER_ERROR', for error 500
* 'Connection: SERVER_UNAVAILABLE', for error 502, 503 or for not being able to establish connection at all
* 'Connection: OK', when web-socket is established 

When Theia is embedded inside a parent HTML, this parent HTML (potentially also from different domain/origin) can receive these messages and react.
For example: in case a security session is maintained, the outer window can notify the user about session expiration and offer ways to recreate it.

Signed-off-by: Ariel Bentolila <ariel.bentolila@gmail.com>

### CODE REVIEW

**Comment by akosyakov** [comment]
Could you create a separate extension for it: https://www.theia-ide.org/doc/Authoring_Extensions.html

If at some point we decide to have a support of Theia as iframe in core, we would have a look at it. Right now it is hard to judge how generic and good the proposed solution. For example we don't use strings to communicate usually but JSON-RPC that a protocol is extendable. The current solution seems to be very specific, maybe you even can integrate just for your product.

**Comment by ariel-bentu** [comment]
I am not sure what you mean - this is a separate extension, one can choose to include it or not.
I will modify it to use message which is a JSON. JSONRPC does not apply here as this is not a two-way communication but one sided posting a message to the parent window, which it turn can be even from different domain.

As for the use-case, as far as I know, also Che is using Theia in IFrame. Once you introduce Theia as part of a bigger picture, like a landing page, overview page, or simple frame with login/logout etc, IFrame becomes very handy.

If you find it useful accept, if not, we will keep it local to our needs
Thanks

**Comment by akosyakov** [comment]
I meant that an extension does not need to be added to this repo in order to be accessible for others. You can set it up as an external Theia extension, publish to npm, take responsibility of maintaining it, similarly to https://github.com/theia-ide/theia-timeline-extension for example.

We don't have capacity now to create an iframe example and think through design, later we can reconsider it and include. Or just use your extension. Otherwise this repo will end up as a sink of all kind of useful code without internal clients and coherent design.

**Comment by ariel-bentu** [comment]
What is the process to create a new repo under theia-ide for such External theia extension?
Thanks :)

**Comment by akosyakov** [comment]
> What is the process to create a new repo under theia-ide for such External theia extension?

You can create your own repo and when it is ready to open an issue with suggestion moving it under theia-ide org.

I wonder can we create something like awesome-theia repo where we list all Theia extensions/plugins/images/app/products. cc @svenefftinge @marcdumais-work instead of moving repos under theia-ide

**Comment by svenefftinge** [comment]
> What is the process to create a new repo under theia-ide for such External theia extension?

We can create the repo for you and give you access rights. I'm a bit sceptical, though, this extension would be useful for anyone but your specific use case. But we will see. Should I create a repo? What name?

**Comment by akosyakov** [comment]
please open an issue if you want to have a separate repo

**Pull request closed without merging**
