### PR TITLE
[mobile] Prevent the IDE from scrolling along with the text (e.g. on iPad)

### PR DESCRIPTION
**Pull request by jankeromnes**
Part of #3557 (thanks a lot @EricRabil for the tip! 💯)

## Screencasts

Current scrolling behavior (IDE scrolls with code editor): https://youtu.be/T0So5v0GQBA

New scrolling behavior (fixed IDE): https://youtu.be/Q3oURvM4Dh0

### CODE REVIEW

**Comment by akosyakov** [comment]
I don't have iPad to verify, but we should at least check that `absolute` -> `fixed` does not break anything. Maybe someone has an idea why we had `absolute` in the first place, after 2 years it is hard to remember 🤔

**Comment by akosyakov** [comment]
It would be good to get one more opinion before merging. At least that other agree, will merge it on Monday if no objections.

**Comment by jankeromnes** [comment]
Thanks for the review!

I believe that the main difference between `fixed` and `absolute` is that `fixed` is positioned relatively to the viewport, while `absolute` is positioned inside the closest `position: relative` element.

I noticed that changing `body` to `position: fixed` broke the loading indicator, which I fixed by changing its position from `absolute` to `fixed`.

It's totally possible that my PR other absolutely positioned elements downstream. I'll try to fix the overlay widgets you mentioned (thanks for catching these!)

**Comment by akosyakov** [comment]
@jankeromnes the main issue with this PR that in the future it won't allow to append Theia shell somewhere in the page, not to the body. I wonder is there a way to avoid switching to `fixed`.

**Comment by lmcbout** [comment]
Nice to have Theia working on a tablet.
Playing with Theia on Ubuntu and Chrome (I don't have a IPAD to test :( ) 
First thing I see is the quick palette, It shows offset to the left and unable to see the data. Even resizing the browser to full screen, the data is display off to the left.

quickPalettePosition

**Comment by jankeromnes** [comment]
Switched to @vince-fugnitto's `touchmove` approach from #5759 -- nice & simple, and works like a charm!

**Comment by jankeromnes** [comment]
(Not sure what `eclipsefdn/eca` is complaining about, but if it's related to the `Co-authored-by` annotation, I can remove it if that's what it expects.)

**Comment by vince-fugnitto** [comment]
I think the issue is the `co-authored-by`, you can see that the following [PR](#4603) doesn't have the issue.
I think it's fine excluding the `co-authored-by` :)

**Comment by jankeromnes** [comment]
(`eclipsefdn/eca` negociation attempt: removed one `Signed-off-by` but kept the `Co-authored-by`.)

**Comment by jankeromnes** [comment]
All green! @vince-fugnitto or @akosyakov please take another look when you have time. 😄

**Pull request merged**
