### PR TITLE
DiffEditor  is not decorated by Search In Workspace extension anymore.

### PR DESCRIPTION
**Pull request by jbicker**
Fixes theia-ide/theia#2539

Signed-off-by: Jan Bicker <jan.bicker@typefox.io>

### CODE REVIEW

**Comment by kittaakos** [comment]
I am doing the review now...

**Comment by kittaakos** [comment]
Does this mean we want to disable the SIW decoration in the diff editors at all? This feature works in VS Code. Please describe what this PR intended to do.

**Comment by kittaakos** [comment]
> as it seems to decorate only file:// resources and not git revisions.

Yeah, it does not make much sense to search among the historical revisions, they are not on the FS as physical files anyway.

**Comment by jbicker** [comment]
> Exactly, but it does not show the query hits. it should, just as the editor in VS Code.
I see, we are talking about different things. I was talking about the diff editor which opens when you click on a search result which should get replaced. That looks good. 
screen shot 2018-09-10 at 09 32 45

**Pull request merged**
