### PR TITLE
Fix cyclic dependency in plugin-ext

### PR DESCRIPTION
**Pull request by vinokurig**
is needed for https://github.com/theia-ide/theia/pull/5239

### CODE REVIEW

**Comment by kittaakos** [comment]
Looks good to me. May I ask why do we have `"@types/diff"` as a dependency but not the `diff`? Wouldn't it make sense to fix this as well in one PR?

**Comment by kittaakos** [comment]
Ohh, I have just noticed, we have duplicate modules and they are identical. Why is that?
 - packages/git/src/browser/dirty-diff/diff-computer.ts
 - packages/scm/src/browser/dirty-diff/diff-computer.ts

**Comment by vinokurig** [comment]
@kittaakos 
> May I ask why do we have "@types/diff" as a dependency but not the diff? Wouldn't it make sense to fix this as well in one PR?

done

**Comment by AlexTugarev** [comment]
@vinokurig, nope, both are needed. Please take care of the cleanup. Why did you copy `dirty-diff` to `scm` in the first place?

**Comment by vinokurig** [comment]
@AlexTugarev I don't mind to take care of clean up but can we go with this and then I'll prepare a clean up?

**Comment by vinokurig** [comment]
@AlexTugarev 
> nope, both are needed 

Do you mean both `@types/diff` and `diff` dependencies?

**Comment by AlexTugarev** [comment]
> The one from scm is used to handle decorations from plugin-Api.

@vinokurig, that's not true. Only `ScmDecorationsService` uses it in `editorManager.onCreated` and scm events, cf. https://github.com/theia-ide/theia/blob/master/packages/scm/src/browser/decorations/scm-decorations-service.ts#L45-L65

Also, having `applyEditorDecorations(editor: TextEditor)` as public API seems to be not a perfect fit, as it only takes care of dirty diff. 

Besides that, the main issue is that it's not just the duplicate of modules, but the main diff-manager is still active. As long as there are no callers via Plugin API, please remove this from scm again or move the manager as well. 

+1 for a separate PR, BTW

**Comment by kittaakos** [comment]
Why cannot you take care of the fix in this PR? The dependency issue does not cause a runtime issue, right?

**Comment by AlexTugarev** [comment]
> Do you mean both @types/diff and diff dependencies?

yes

**Comment by vinokurig** [comment]
@AlexTugarev Added second dependency

 @kittaakos 
>Why cannot you take care of the fix in this PR? The dependency issue does not cause a runtime issue, right?

Looks like we have problems with this in our project https://github.com/eclipse/che-theia that uses Theia

**Comment by kittaakos** [comment]
> Looks like we have problems with this in our project https://github.com/eclipse/che-theia that uses Theia

Got it, 👍
Let's get the fix to the `master` ASAP, but please make sure you clean up the code duplication you have introduced right after the merge.

**Comment by vinokurig** [comment]
@AlexTugarev 
> Besides that, the main issue is that it's not just the duplicate of modules, but the main diff-manager is still active. As long as there are no callers via Plugin API, please remove this from scm again or move the manager as well.

There is a call from `decorations-main` (Pluign-Api) https://github.com/theia-ide/theia/blob/2011dfb23097064154d881b2db28d1ba949f33f8/packages/plugin-ext/src/main/browser/decorations/decorations-main.ts#L62

**Comment by AlexTugarev** [comment]
@vinokurig, right, but that's `fireNavigatorDecorationsChanged` only. I'm talking about `applyEditorDecorations` which in fact updates dirty-diffs, right? I'd consider this to be something one  would turn on/off, but not call explicitly.

**Comment by vinokurig** [comment]
@AlexTugarev Could you clarify please: Do you want me to use Decorations in SCM from Git package?

**Pull request merged**
